### ISSUE TITLE
Fix tab spacing

### ISSUE THREAD

**Issue by knynkwl** [barrelstrength/craft-sprout-forms#100]
### Description
When there are a lot of tabs, there is no way to access the gear icon. I better solution might be to have it scrollX.

<img width="773" alt="screenshot 2018-05-19 at 12 46 44 pm" src="https://user-images.githubusercontent.com/4225771/40270896-23563a9e-5b63-11e8-985e-988d80d7d9ca.png">

**Comment by BenParizek** [comment]
@knynkwl Thanks for the visual. We're working on this issue if you'd like to follow this task:
https://github.com/barrelstrength/craft-sprout-forms/issues/97
