### ISSUE TITLE
Internal Server Error - Custom Email template

### ISSUE THREAD

**Issue by Geestig** [barrelstrength/craft-sprout-forms#102]
### Description
So last time I've used Sprout Forms everything went quite smooth. However when I try to add my custom template this time I get an Internal Server Error upon trying to send a test.

set custom template

![image](https://user-images.githubusercontent.com/9035369/40408231-224b478c-5e67-11e8-85c2-5a68e2d32e23.png)

add email.html on that position.

![image](https://user-images.githubusercontent.com/9035369/40408241-284d6bd8-5e67-11e8-9cb0-fcd49a440ef0.png)

try to "send test"

![image](https://user-images.githubusercontent.com/9035369/40408250-2fcd102a-5e67-11e8-9dfa-1e693feb8a84.png)

PS: I've tried both the standard email template with or without the 'entry / form'. Error only concurrs when trying a custom path. Standard templates work fine.

### Steps to reproduce

1. copy mail template to _mail folder in templates and name it email.html
2. set _mail as custom template and press "send test"

### Additional info

- Craft version: 3
- PHP version: 7.1.12
- Database driver & version: Mysql, 4.7.7
- Plugins & versions: Sprout-Forms

**Comment by BenParizek** [comment]
Thanks for reporting @Geestig 

I've just pushed an update in `Sprout Forms v3.0.0-beta.16` that should fix this issue.
