### ISSUE TITLE
Using the options object doesn't affect fields

### ISSUE THREAD

**Issue by darylknight** [barrelstrength/craft-sprout-forms#103]
### Description
If you use an options object to customise the form field ids and classes using the example from the docs, the form inherits the correct attributes, but it doesn't affect input fields.

### Steps to reproduce
```
{% set options = {
  "id": "myform",
  "fields": {
    "phone": {
      "class": "my-fancy-class",
    }
  }
} %}

{{ craft.sproutForms.displayForm("contactForm", options) }}```

This outputs the form with no class attached to the `input`.

### Additional info

- Craft version: 3.0.9
- PHP version: 7.1.15
- Database driver & version:
- Plugins & versions: Sprout Forms 3.0.0-beta.16

**Comment by BenParizek** [comment]
@darylknight We just released v3.0.0-beta.17 which should resolve this issue. 

https://sprout.barrelstrengthdesign.com/docs/forms/rendering-options.html
