### ISSUE TITLE
FieldLayoutEditor.js? Uncaught ReferenceError: el is not defined

### ISSUE THREAD

**Issue by nicholashu** [barrelstrength/craft-sprout-forms#106]
### Description
Adding standard fields causes error
FieldLayoutEditor.js? Uncaught ReferenceError: el is not defined

### Steps to reproduce

1. Add standard field to new form

### Additional info

fixed by changing FieldLayoutEditor.js 581:40 from el to $fieldDiv

- Craft version: 3.10
- Plugins & versions: 3.0.0-beta.16

**Comment by BenParizek** [comment]
@nicholashu We just released v3.0.0-beta.17 which includes this fix. Thanks for reporting.
