### ISSUE TITLE
Error when viewing response

### ISSUE THREAD

**Issue by ryangittings** [barrelstrength/craft-sprout-forms#125]
### Description
TypeError: Argument 1 passed to barrelstrength\sproutforms\fields\formfields\BaseOptionsFormField::optionLabel() must be of the type string or null, array given

### Steps to reproduce

1.
2.

### Additional info

- Craft version: Latest
- PHP version: 7.1
- Database driver & version:
- Plugins & versions:

**Comment by BenParizek** [comment]
@ryangittings Can you be more specific? What response are you viewing? Where? What fields are you trying to display? What version of Sprout Forms are you on?

**Comment by ryangittings** [comment]
Version v3.0.0-beta.17

Trying to view an entry, I click on the title to view the entry, get an internal server error with that error in the logs.

It seems to be any form that has been submitted since updating to the latest version. Fields include text, select, checkbox.

**Comment by ryangittings** [comment]
Full error, 

`Argument 1 passed to barrelstrength\sproutforms\fields\formfields\BaseOptionsFormField::optionLabel() must be of the type string or null, array given, called in /vendor/barrelstrength/sprout-forms/src/fields/formfields/BaseOptionsFormField.php on line 166`

**Comment by BenParizek** [comment]
This should be resolved in Sprout Forms v3.0.0-beta.18, now in the plugin store.
