### ISSUE TITLE
Hardcoded non-breaking space in default template

### ISSUE THREAD

**Issue by kotyy** [barrelstrength/craft-sprout-forms#127]
### Description
_Very_ minor issue. The default template includes `&nbsp;` in checkbox labels, but not within radio button labels. It would be nice if they were consistent, either with or without the space.

**Comment by BenParizek** [comment]
Thanks @kotyy 

Minor issue but worth cleaning up. This is on our list. I'll close this ticket out and you can follow the issue here if you'd like: https://github.com/barrelstrength/craft-sprout-forms/issues/95

**Comment by kotyy** [comment]
Thanks. I didn't notice the open issue!

**Comment by BenParizek** [comment]
@kotyy fyi, we've decided to remove the `&nbsp;` in the default checkbox labels in v3.0.0-beta.28 (in the plugin store).
