### ISSUE TITLE
TypeError when cp view entry with checkboxes

### ISSUE THREAD

**Issue by AmandaLutzTO** [barrelstrength/craft-sprout-forms#128]
Trying to view/edit an entry with checkboxes (and maybe radios?) in craft admin throws TypeError.

Argument 1 passed to barrelstrength\sproutforms\fields\formfields\BaseOptionsFormField::optionLabel() must be of the type string, array given, called in /home/seineriv/vendor/barrelstrength/sprout-forms/src/fields/formfields/BaseOptionsFormField.php on line 166

in /home/seineriv/vendor/barrelstrength/sprout-forms/src/fields/formfields/BaseOptionsFormField.php at line 166 – barrelstrength\sproutforms\fields\formfields\BaseOptionsFormField::optionLabel(['label' => 'Not wearing required PPE', 'value' => 'notWearingRequiredPpe', 'selected' => true])

### Steps to reproduce

1. create form with checkboxes
2. fill in form to create entry
3. try to view/edit entry in craft admin

### Additional info

- Craft version: Craft CMS 3.0.15
- PHP version:
- Database driver & version:
- Plugins & versions: Sprout Forms 3.0.0-beta.16

**Comment by AmandaLutzTO** [comment]
Never mind, duplicate of https://github.com/barrelstrength/craft-sprout-forms/issues/125

**Comment by andrelopez** [comment]
@AmandaLutzTO I'm on it :)

**Comment by BenParizek** [comment]
@AmandaLutzTO This is resolved in Sprout Forms v3.0.0-beta.18, now in the plugin store.
