### ISSUE TITLE
can't update 3.0.0-beta.16 to 3.0.0-beta.18

### ISSUE THREAD

**Issue by AmandaLutzTO** [barrelstrength/craft-sprout-forms#130]
### Description
Click the Update button. Receive following message:

```
Composer was unable to install the updates.

Error: An error occurred

Output: Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

Problem 1
- Installation request for barrelstrength/sprout-forms 3.0.0-beta.18 -> satisfiable by barrelstrength/sprout-forms[3.0.0-beta.18].
- barrelstrength/sprout-forms 3.0.0-beta.18 requires barrelstrength/sprout-base ^2.0.7 -> satisfiable by barrelstrength/sprout-base[2.0.8, 2.0.7] but these conflict with your requirements or minimum-stability.
```

If I try to run update again, even a day or 2 later, I get 
```
It looks like someone is currently performing a system update.
Only continue if you’re sure that’s not the case.
```

Running ssh
`composer update barrelstrength/sprout-forms`
says there's nothing to update.

I already have 
```
  "minimum-stability": "dev",
  "prefer-stable": true,
```
in composer.json

### Steps to reproduce

1. Click Update button
2. Or try to update via ssh command line

### Additional info

- Craft version: Craft CMS 3.0.15
- PHP version: 7.0.30
- Database driver & version: MySQL 10.1.31
- Plugins & versions: Sprout Forms 3.0.0-beta.16

**Comment by BenParizek** [comment]
This turned out to be a composer-related issue that was resolved via another channel.
