### ISSUE TITLE
Validation doesn't happen when not storing entries in the db

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-forms#135]
- [x] <img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_cxyr)
- [x] <img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_cc7v)

**Comment by andrelopez** [comment]
This is fixed in Craft CMS 3.
