### ISSUE TITLE
Parser Error when editing entry statuses

### ISSUE THREAD

**Issue by jerome2710** [barrelstrength/craft-sprout-forms#140]
### Description

The JavaScript of the entryStatus edit page throws a parser error because it has an extra closing tag: https://github.com/barrelstrength/craft-sprout-forms/blob/v3/src/templates/settings/entrystatuses/_edit.html#L106

### Steps to reproduce

1. Edit an form entry status

### Additional info

- Craft version: Pro 3.0.18
- PHP version: 7.1.18
- Database driver & version: MySQL 5.5.56
- Plugins & versions: _lots_

**Comment by BenParizek** [comment]
Thanks for reporting this @jerome2710. Just released a fix in v3.0.0-beta.22
