### ISSUE TITLE
Notification Emails not sending?

### ISSUE THREAD

**Issue by alexr8** [barrelstrength/craft-sprout-forms#144]
### Description
I'm struggling to get confirmation emails working - i'm new to this plugin so might be missing something obvious. 

When i click 'Send test' on the notification i have created i get `count(): Parameter must be an array or an object that implements Countable`. Similarly submitting my form in the front end sends no notification but the entry does get saved. 

My notification is set to send when an entry is created, and is linked to the form i am trying to submit.

### Steps to reproduce

1. Create a notification
2. Hit the 'Send test' button

### Additional info

- Craft version: 3
- PHP version: 7.1
- Database driver & version: MySQL
- Plugins & versions:

**Comment by BenParizek** [comment]
Hi Alex,

This issue typically relates to some code not passing stricter requirements with PHP 7.2. Please make sure you are updated to the latest, as we have resolved similar bugs in past releases, and we'll let you know when we have a fix in place.

Ben

**Comment by alexr8** [comment]
I'm currently running `3.0.0-beta.21` which i think is the latest? i think it's probably ok for the client for now to just have entries in the admin without any notification emails, as they'll be logging in every day so can just check for new entries manually.

**Comment by BenParizek** [comment]
@alexr8 This should be resolved in v3.0.0-beta.26, now available in the Plugin Store.
