### ISSUE TITLE
Payload forwarding not sending any payload

### ISSUE THREAD

**Issue by stigzelm** [barrelstrength/craft-sprout-forms#145]
### Description

I am trying to use the payload forwarding in a form. I want to send the form data to my custom controller that parses it and does an API request. But when I try to get the form data, it is always 'null';

The way I try to get the data in the controller is the following.

Craft::$app->request->getBodyParams();

Is it a bug or am I getting the body params the wrong way?

### Steps to reproduce

1. Set a custom submit url in the form (payload forwarding).
2. Submit that form.
3. Try to output the payload.

### Additional info

- Craft version: 3
- PHP version: 7.0
- Database driver & version: mysql 5.7.21
- Plugins & versions: Sprout Forms 3.0.0-beta.21

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_ddr7)

**Comment by BenParizek** [comment]
Thanks for reporting this @stigzelm. We believe this is a bug and we're working on a fix. We'll let you know once we get it released.

**Comment by BenParizek** [comment]
@stigzelm This issue should be resolved in Sprout Forms v3.0.0-beta.28 (now in the plugin store)
