### ISSUE TITLE
Deleting a Sprout Forms fields that shares a handle with other fields removes the content column

### ISSUE THREAD

**Issue by OscarBarrett** [barrelstrength/craft-sprout-forms#147]
### Description

On one of our sites that uses Sprout Forms we have multiple fields with a `phone` handle - several under Sprout Forms and one not. We accidentally created one of the Sprout Forms fields with a number type so wanted to delete it and recreate with the correct type. Deleting the field removed the `field_phone` column from the `content` table and broke the other fields that use this handle.

### Steps to reproduce

e.g have the following `phone` fields in the `fields` table

| id            | groupId       | name          | handle        | context           | type                                                  |
| ------------- | ------------- | ------------- | ------------- | ----------------- | ----------------------------------------------------- |
| 62            | 3             | Phone         | phone         | global            |  craft\fields\PlainText                               |
| 101           | NULL          | Contact phone | phone         | sproutForms:187   |  barrelstrength\sproutforms\fields\formfields\Phone   |
| 94            | NULL          | Contact phone | phone         | sproutForms:2     |  barrelstrength\sproutforms\fields\formfields\Number  |
| 112           | NULL          | contact Phone | phone         | sproutForms:232   |  barrelstrength\sproutforms\fields\formfields\Phone   |

In the `content` table, there is a `field_phone` column.

Go to `/admin/sprout-forms/forms/edit/2`, edit the Contact phone field and hit Delete.

After doing so, the `phone` fields in the DB are correct:

| id            | groupId       | name          | handle        | context           | type                                                  |
| ------------- | ------------- | ------------- | ------------- | ----------------- | ----------------------------------------------------- |
| 62            | 3             | Phone         | phone         | global            |  craft\fields\PlainText                               |
| 101           | NULL          | Contact phone | phone         | sproutForms:187   |  barrelstrength\sproutforms\fields\formfields\Phone   |
| 112           | NULL          | contact Phone | phone         | sproutForms:232   |  barrelstrength\sproutforms\fields\formfields\Phone   |

However the `field_phone` column no longer exists in the `content` table and other fields that use this handle (and entries that use these fields) are now broken.

### Additional info

- Craft version: 3.0.19
- PHP version: 7.2.8
- Database driver & version: MySQL 5.7.21
- Plugins & versions: Sprout Forms 3.0.0-beta.21

It looks like you're just [calling the Craft fields service](https://github.com/barrelstrength/craft-sprout-forms/blob/541636e1d2775bb57faa7bc7acfa8de127f08195/src/controllers/FieldsController.php#L334) so this might be a bug in Craft? But I thought I'd report it here first.

**Comment by BenParizek** [comment]
Thanks for reporting @OscarBarrett. We'll let you know when we have a fix out.

**Comment by BenParizek** [comment]
@OscarBarrett This issue was solved in Sprout Forms v3.0.0-beta.23.

Thanks for reporting.
