### ISSUE TITLE
Creating a field after deleting a new tab results in inaccessible fields in the db

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-forms#149]
There is a bug when you create a new tab in a form, delete it afterwards, and create new fields for the deleted tab.

The tab `select` doesn't update  in the fields edit modal (no matter if the fields are new or if they already existed) so you are able to create fields for non existing tabs. Sprout Forms stores those fields but clients/non developers can't delete them anymore since there is no visual effect for them but their block fields with the same `handle`

Steps to recreate:

- new form
- create tab 2
- delete tab 2
- create a field with handle `test` -> store it for tab 2
- see no field is created
- create another field with the same handle `test` and see validation error because the handle is already in use

Make sure we also write a migration to clean up unused fields.

### Notify

- [x] Robin on Slack

**Comment by andrelopez** [comment]
The fix will delete the tab via ajax

**Comment by BenParizek** [comment]
Fixed in v3.0.0-beta.22
