### ISSUE TITLE
Unable to change form settings on Craft 2.7.0 and PHP 7.2

### ISSUE THREAD

**Issue by jmcgaha** [barrelstrength/craft-sprout-forms#151]
### Description
count(): Parameter must be an array or an object that implements Countable

/Users/username/plugins/sproutforms/controllers/SproutForms_FormsController.php(81)

```
69 
70         if ($form->saveAsNew)
71         {
72             $fieldLayout = sproutForms()->fields->getDuplicateLayout($duplicateForm, $fieldLayout);
73         }
74 
75         $fieldLayout->type = 'SproutForms_Form';
76         $form->setFieldLayout($fieldLayout);
77 
78         // Delete any fields removed from the layout
79         $deletedFields = craft()->request->getPost('deletedFields');
80 
81         if (count($deletedFields) > 0)
82         {
83             // Backup our field context and content table
84             $oldFieldContext = craft()->content->fieldContext;
85             $oldContentTable = craft()->content->contentTable;
86 
87             // Set our field content and content table to work with our form output
88             craft()->content->fieldContext = $form->getFieldContext();
89             craft()->content->contentTable = $form->getContentTable();
90 
91             $currentTitleFormat = null;
92             foreach ($deletedFields as $fieldId)
93             {
```

### Steps to reproduce

1. Sprout Forms -> Forms -> Choose any form -> Click Save
2. Switching PHP back to a 7.1.x version fixes the problem.
3. (I had a similar issue on Sprout Reports and a separate issue was filed there)

### Additional info

- Craft version: 2.7.0
- PHP version: 7.2.7
- Database driver & version:
- Plugins & versions: 0.10.0

**Comment by BenParizek** [comment]
Thanks, Jonathan. Now that Craft 2 has added PHP 7.2 support we're reviewing our Craft 2 plugins and adding support. We'll let you know when we get a release out with a fix.

**Comment by BenParizek** [comment]
@jmcgaha This is fixed in https://github.com/barrelstrength/craft-sprout-forms/releases/tag/v2.6.1
