### ISSUE TITLE
Error upgrading from Craft 2 => 3: Unknown column 'sproutforms_forms.saveData'

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-forms#152]
See: https://craftcms.stackexchange.com/questions/25893/database-exception-with-sprout-forms-after-updating-to-craft-3

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_ddqr)

**Comment by andrelopez** [comment]
This issue is caused because users need first update Sprout Forms to 2.5.1 before the upgrade to Craft 3.
