### ISSUE TITLE
Default success message in template after submission

### ISSUE THREAD

**Issue by michaelhue** [barrelstrength/craft-sprout-forms#153]
### Description

I'd like to add a default "thank you" confirmation inside the main form template in case the client forgets to create a custom "thank you" page when creating forms.

Is there any way to check if a form has just been submitted in order to display a message?

Thank you!

### Additional info

- Plugin version: 3.0.0-beta.22

**Comment by BenParizek** [comment]
@michaelhue You can check for the [craft.sproutForms.lastEntry()](https://sprout.barrelstrengthdesign.com/docs/forms/entries.html#lastentry) in your templates. It will only exist for the page request after a form is submitted. There is a longer example in the docs.
