### ISSUE TITLE
Unable to submit form without disabling Duplicate Submission Captcha & Javascript Captcha under Spam Protection.

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-forms#154]
<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_dhoj)

**Comment by andrelopez** [comment]
If you're using template overrides please add the next line of code inside the `<form>` tag of your template:

{% hook 'sproutForms.modifyForm' %}

This hook allows Sprout Forms insert the captcha HTML code.

Best,
