### ISSUE TITLE
How do I submit a front-end form using AJAX?

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-forms#159]
<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_dmur)

**Comment by andrelopez** [comment]
A complete example is available [here](https://sprout.barrelstrengthdesign.com/docs/forms/submitting-a-form-via-ajax.html)

However, if the user is using template overrides and spam protection is enabled in the plugin settings please make sure that the next line is within the `<form> .. </from>` tag

`
{% hook 'sproutForms.modifyForm' %}
`

**Comment by BenParizek** [comment]
An example using React is in the Front conversations. Consider adding to docs.
