### ISSUE TITLE
Email dropdown issue

### ISSUE THREAD

**Issue by amos-whitewolf** [barrelstrength/craft-sprout-forms#171]
### Description
I'm having trouble with the email drop-down field. I'm using the displayForm function and entries are being created.

Every time I make a submission, the entry doesn't always display the option I selected on the email dropdown field in the craft admin. All other fields come through correctly. I've looked at the post request and it has a number value for the email drop-down field. I assume this is the correct behavior to avoid email spam.

The second issue when I used the {emailDropdownField} in the notifications, I get the number value of the option instead of the email value. This issue is also present in the notification rather than displaying the field the user selected it shows a number value.

<img width="291" alt="screen shot 2018-10-18 at 1 23 31 pm" src="https://user-images.githubusercontent.com/9377462/47127493-106b3e00-d2d9-11e8-9bd5-044905db2822.png">

The screenshot is of the notification in my email, under the interested in label it's showing a number.

### Additional info

- Craft version: Craft Pro 3.0.27.1
- PHP version: 7.1.12
- Database driver & version: MySQL 5.6.38
- Plugins & versions: Sprout Forms | 3.0.0-beta.26

**Comment by amos-whitewolf** [comment]
Hey @andrelopez, 

Do you have an ETA on this one?

Kind regards,
Amos

**Comment by BenParizek** [comment]
@amos-whitewolf We can recreate the issue. We're working on a solution. We'll update this thread as soon as we have it release – it may be early next week.

**Comment by BenParizek** [comment]
@amos-whitewolf We just released Sprout Forms v3.0.0-beta.28 which should solve the email notification issue you were experiencing. 

We have not been able to recreate the first issue you outlined where the wrong value is selected in the CP. Can you test the latest and if you are still seeing issues with the value being stored in the CP, open another ticket and provide any more info you can that might help us recreate the issue.
