### ISSUE TITLE
Required "Name" field is not validated

### ISSUE THREAD

**Issue by michaelhue** [barrelstrength/craft-sprout-forms#172]
### Description

Submitting an empty `Name` field will pass validation.

### Steps to reproduce

1. Create a form.
2. Add a "Name" field with "First name" and "Last name" enabled.
3. Make field required.
4. Remove "required" attributes from field's HTML output to test backend validation.
5. Submit empty form.
6. Name field is valid and will be submitted.

### Additional info

- Craft version: Craft Pro 3.0.27.1
- PHP version: 7.2.6
- Database driver & version: 	MySQL 5.5.5
- Plugins & versions: Sprout Forms 3.0.0-beta.26

**Comment by BenParizek** [comment]
Thanks for the detailed steps @michaelhue. We'll look into this.

**Comment by BenParizek** [comment]
@michaelhue The name field will now fail validation if blank (v3.0.0-beta.28, now in the plugin store). The initial implementation is a bit broad – if any fields are filled the whole name field will be considered valid. We'll aim to add more granular support in the future so you could specifically require something like first and last name but not the middle name.
