### ISSUE TITLE
Non admins cannot make reports

### ISSUE THREAD

**Issue by Rias500** [barrelstrength/craft-sprout-forms#175]
### Description

A non-admin, even with all permissions for Sprout Forms, cannot make reports.

Notify: https://github.com/barrelstrength/craft-sprout-forms/issues/178

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_gk7n)

**Comment by BenParizek** [comment]
@rias We've added additional Reports permissions in the latest Sprout Forms. Settings are now restricted to admins and there is are View Reports and Edit Reports permissions that can be assigned to user groups.
