### ISSUE TITLE
PHP warning caused by SproutForms_SaveEntryEvent.php in devMode

### ISSUE THREAD

**Issue by jamesmacwhite** [barrelstrength/craft-sprout-forms#179]
### Description

Similar to the reported issue with Sprout Emails omitting a PHP warning with devMode on. Sprout Forms for Craft 2 will display the following message:

> Warning: Declaration of Craft\SproutForms_SaveEntryEvent::validateOptions($options, Craft\SproutForms_EntryModel $entry, array $params = Array) should be compatible with Craft\SproutEmailBaseEvent::validateOptions($options, $eventData, array $params = Array) in /app/plugins/sproutforms/integrations/sproutemail/SproutForms_SaveEntryEvent.php on line 136

### Steps to reproduce

1. Install Sprout Forms 2.6.1
2. Enable devMode
3. Observe the warning error displayed

### Additional info

- Craft version: 2.7.3
- PHP version: 7.1
- Plugins & versions: 2.6.1

**Comment by jamesmacwhite** [comment]
The easy fix would be to also remove the class parameter, but I'll let you investigate to make sure that is also a valid fix for it:

https://github.com/barrelstrength/craft-sprout-email/commit/19b61820da7acad75e8ee137adea07113c06b1c9

**Comment by andrelopez** [comment]
Hi @jamesmacwhite ,

Thanks for following up. We have fixed this error in v2.6.2 available here: https://github.com/barrelstrength/craft-sprout-forms/archive/v2.6.2.zip

Please let us know if that works.

Best,
