### ISSUE TITLE
Deprecation error for craft.sections.getSectionById

### ISSUE THREAD

**Issue by rinusvandam** [barrelstrength/craft-sprout-forms#184]
### Description

Getting a deprecation error on multiple Craft installations after installing the Sprout Forms plugin.

#### Message
`craft.sections.getSectionById() has been deprecated. Use craft.app.sections.getSectionById() instead.`

#### Location
`/craft-site/vendor/barrelstrength/sprout-forms/src/templates/_components/formtemplates/accessible/fields/entries/input.twig:35`

### Steps to reproduce

1. Install Craft CMS
2. Install Sprout Forms from the Plugin Store
3. Create a form and open the form on the front-end

### Additional info

- Craft version: Craft Pro 3.0.29
- PHP version: 7.2.7
- Database driver & version: MySQL 5.7.21
- Plugins & versions: Latest Sprout Forms

**Comment by BenParizek** [comment]
@rinusvandam These deprecation warnings have been fixed in v3.0.0-beta.32
