### ISSUE TITLE
Documentation not accurate

### ISSUE THREAD

**Issue by exophunk** [barrelstrength/craft-sprout-forms#191]
**Redirect hidden field:**

In your [documentation page about the "Thank you Page"](https://sprout.barrelstrengthdesign.com/docs/forms/thank-you-page.html#using-a-query-string-to-display-a-custom-thank-you-message), you describe how to  add a hidden redirect field.

`<input type="hidden" name="redirect" value="contact?message=thankyou">`

This actually doesn't work, because the value of the field needs to be hashed, as a deeper look in your template shows:

https://github.com/barrelstrength/craft-sprout-forms/blob/v3/src/templates/_components/formtemplates/accessible/form.twig#L19-L26

```
    {%- if redirectUri is not empty %}
        {% if redirectUri|slice(0, 1)|lower == '?' %}
            {%- set redirectUri = craft.app.request.getUrl()~redirectUri %}
        {% endif %}

        <input type="hidden" aria-hidden="true" name="redirect"
               value="{{ redirectUri|hash }}">
    {% endif %}
```

You should update this in the documentation.

-----

**Action hidden field:**

The action field needs to be lower kebab-case: 
https://github.com/barrelstrength/craft-sprout-forms/blob/v3/src/templates/_components/formtemplates/accessible/form.twig#L15-L16

Some parts of the documentation still show the old camelCase version:

- https://sprout.barrelstrengthdesign.com/docs/forms/custom-html.html#working-with-a-custom-html-form
- https://sprout.barrelstrengthdesign.com/docs/forms/custom-html.html#example-code-to-manually-manage-all-default-fields-in-your-templates

You should update this in the documentation or make a clear distinction between Craft 2 & 3.

------

**Captcha fields:**

Custom forms simply don't work without disabling the captcha options, It silently fails. It only works if you add the correct captcha fields to the custom form HTML. This can be done by adding this hook:

`{% hook 'sproutForms.modifyForm' %}`
https://github.com/barrelstrength/craft-sprout-forms/blob/v3/src/templates/_components/formtemplates/accessible/form.twig#L34

according to your base form HTML.

This need to be mentioned somewhere in the documentation. Also, how do I get an error when captcha validation failed?

Thanks for your awesome plugin!

Best, Robert

**Comment by BenParizek** [comment]
Thanks for reporting @exophunk. Still more to do, but the docs have been improved with these updates!
