### ISSUE TITLE
Deprecation Warnings

### ISSUE THREAD

**Issue by ryangittings** [barrelstrength/craft-sprout-forms#196]
### Description

**vendor/barrelstrength/sprout-forms/src/templates/_integrations/sproutemail/emailtemplates/basic/email.twig:66**
`Looping through element queries directly has been deprecated. Use the all() function to fetch the query results before looping over them.`

### Steps to reproduce

1. Go to CMS utility area after form submission
2.

### Additional info

- Craft version: 3.0.29
- PHP version: 7.2.6
- Database driver & version: MySQL 5.6.39
- Plugins & versions: 3.0.0-beta.32

**Comment by andrelopez** [comment]
This is a false positive, that variable is not an element.
