### ISSUE TITLE
Phone Validation Error Message Consistency

### ISSUE THREAD

**Issue by tplassman** [barrelstrength/craft-sprout-forms#201]
### Description
When a form is submitted w/ an empty and required phone input, the error message omits a period at the end of the message that is present on similar error messages for other inputs.

https://github.com/barrelstrength/craft-sprout-forms/blob/v3/src/fields/formfields/Phone.php#L221

### Steps to reproduce

1. Submit form containing required phone input w/ empty value.

### Additional info

- Craft version: 3.0.27.1
- PHP version: 7.1.24
- Database driver & version: MySQL
- Plugins & versions: N/A

**Comment by BenParizek** [comment]
Thanks for reporting @tplassman. We just pushed Sprout Forms v3.0.0-beta.35 which resolves this.

**Comment by tplassman** [comment]
Thanks @BenParizek.  Our very thorough proofreader will be pleased :)
