### ISSUE TITLE
Unable to install plugin on Craft 3.1

### ISSUE THREAD

**Issue by jerome2710** [barrelstrength/craft-sprout-forms#202]
### Description
I am unable to install/enable the Sprout Forms plugin after installing it from the plugin store. A red notification of `Couldn’t install plugin.` pops up.

### Steps to reproduce

1. Install plugin from the Craft back-end CMS
2. Enable the plugin

### Additional info

- Craft version: 3.1.0-beta.4
- PHP version: 7.2.11
- Database driver & version: MySQL 5.5.5

**Comment by BenParizek** [comment]
@jerome2710 That's a fairly generic error. If you have a more specific error or info from the logs, feel free to post it. 

We've got a few more Sprout releases in the works and planned for this year and currently plan to begin reviewing Craft 3.1 more closely and adding support in the new year.

**Comment by BenParizek** [comment]
@jerome2710 As we haven't heard back we're going to close out this request as we haven't heard anybody else bring this up. If you are still running into issues, drop us a note with more info and we'll reopen this thread to help figure it out.
