### ISSUE TITLE
Swift_RfcComplianceException when Reply To references a field that doesn't exist

### ISSUE THREAD

**Issue by kotyy** [barrelstrength/craft-sprout-forms#203]
### Description
When submitting a form that generates a notification, if the notification references a field that doesn't exist on the form, the user is given an Internal Server Error.

### Steps to reproduce

1. Create a form.
2. Create a Notification for that form, set Reply To to `{foo}`.
3. Submit the form. You will receive an Internal Server Error, the response will be saved, and a notification will not be sent.

### Additional info

- Craft version: 3.0.32
- PHP version: 7.0.32
- Database driver & version: MySQL 5.6.36

2018-12-07 14:18:29 [-][1][578a488e5e7abdf10fd9e0b1bc1b40c5][error][sprout-forms] Failed to save element: Address in mailbox given [] does not comply with RFC 2822, 3.6.2.
2018-12-07 14:18:29 [-][1][578a488e5e7abdf10fd9e0b1bc1b40c5][error][Swift_RfcComplianceException] Swift_RfcComplianceException: Address in mailbox given [] does not comply with RFC 2822, 3.6.2. in /home/site/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php:355
Stack trace:
#0 /home/site/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(272): Swift_Mime_Headers_MailboxHeader->assertValidAddress('')
#1 /home/site/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(117): Swift_Mime_Headers_MailboxHeader->normalizeMailboxes(Array)
#2 /home/site/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(74): Swift_Mime_Headers_MailboxHeader->setNameAddresses(Array)
#3 /home/site/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleHeaderFactory.php(61): Swift_Mime_Headers_MailboxHeader->setFieldBodyModel(Array)
#4 /home/site/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleHeaderSet.php(71): Swift_Mime_SimpleHeaderFactory->createMailboxHeader('Reply-To', Array)
#5 /home/site/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMessage.php(268): Swift_Mime_SimpleHeaderSet->addMailboxHeader('Reply-To', Array)
#6 /home/site/vendor/yiisoft/yii2-swiftmailer/src/Message.php(121): Swift_Mime_SimpleMessage->setReplyTo('')
#7 /home/site/vendor/barrelstrength/sprout-base/src/app/email/base/Mailer.php(513): yii\swiftmailer\Message->setReplyTo('')
#8 /home/site/vendor/barrelstrength/sprout-base/src/app/email/mailers/DefaultMailer.php(91): barrelstrength\sproutbase\app\email\base\Mailer->getMessage(Object(barrelstrength\sproutbase\app\email\elements\NotificationEmail))
#9 /home/site/vendor/barrelstrength/sprout-base/src/app/email/services/NotificationEmails.php(119): barrelstrength\sproutbase\app\email\mailers\DefaultMailer->sendNotificationEmail(Object(barrelstrength\sproutbase\app\email\elements\NotificationEmail))
#10 /home/site/vendor/barrelstrength/sprout-base/src/app/email/services/NotificationEmailEvents.php(199): barrelstrength\sproutbase\app\email\services\NotificationEmails->sendNotificationViaMailer(Object(barrelstrength\sproutbase\app\email\elements\NotificationEmail))
#11 /home/site/vendor/barrelstrength/sprout-base/src/app/email/services/NotificationEmailEvents.php(154): barrelstrength\sproutbase\app\email\services\NotificationEmailEvents->handleDynamicEvent('barrelstrength\\...', Object(barrelstrength\sproutforms\events\OnSaveEntryEvent), Object(barrelstrength\sproutforms\integrations\sproutemail\events\notificationevents\SaveEntryEvent))
#12 [internal function]: barrelstrength\sproutbase\app\email\services\NotificationEmailEvents->barrelstrength\sproutbase\app\email\services\{closure}('barrelstrength\\...', Object(barrelstrength\sproutforms\events\OnSaveEntryEvent), Object(barrelstrength\sproutforms\integrations\sproutemail\events\notificationevents\SaveEntryEvent))
#13 /home/site/vendor/barrelstrength/sprout-base/src/app/email/services/NotificationEmailEvents.php(124): call_user_func(Object(Closure), 'barrelstrength\\...', Object(barrelstrength\sproutforms\events\OnSaveEntryEvent), Object(barrelstrength\sproutforms\integrations\sproutemail\events\notificationevents\SaveEntryEvent))
#14 [internal function]: barrelstrength\sproutbase\app\email\services\NotificationEmailEvents->barrelstrength\sproutbase\app\email\services\{closure}(Object(barrelstrength\sproutforms\events\OnSaveEntryEvent))
#15 /home/site/vendor/yiisoft/yii2/base/Event.php(310): call_user_func(Object(Closure), Object(barrelstrength\sproutforms\events\OnSaveEntryEvent))
#16 /home/site/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('barrelstrength\\...', 'afterSave', Object(barrelstrength\sproutforms\events\OnSaveEntryEvent))
#17 /home/site/vendor/barrelstrength/sprout-forms/src/services/Entries.php(505): yii\base\Component->trigger('afterSave', Object(barrelstrength\sproutforms\events\OnSaveEntryEvent))
#18 /home/site/vendor/barrelstrength/sprout-forms/src/services/Entries.php(317): barrelstrength\sproutforms\services\Entries->callOnSaveEntryEvent(Object(barrelstrength\sproutforms\elements\Entry), true)
#19 /home/site/vendor/barrelstrength/sprout-forms/src/controllers/EntriesController.php(153): barrelstrength\sproutforms\services\Entries->saveEntry(Object(barrelstrength\sproutforms\elements\Entry))
#20 /home/site/vendor/barrelstrength/sprout-forms/src/controllers/EntriesController.php(133): barrelstrength\sproutforms\controllers\EntriesController->saveEntryInCraft(Object(barrelstrength\sproutforms\elements\Entry))
#21 [internal function]: barrelstrength\sproutforms\controllers\EntriesController->actionSaveEntry()
#22 /home/site/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#23 /home/site/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#24 /home/site/vendor/craftcms/cms/src/web/Controller.php(104): yii\base\Controller->runAction('save-entry', Array)
#25 /home/site/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-entry', Array)
#26 /home/site/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('sprout-forms/en...', Array)
#27 /home/site/vendor/craftcms/cms/src/web/Application.php(542): craft\web\Application->runAction('sprout-forms/en...', Array)
#28 /home/site/vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#29 /home/site/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#30 /home/site/web/index.php(21): yii\base\Application->run()
#31 {main}

**Comment by andrelopez** [comment]
Issue moved to [barrelstrength/craft-sprout-email #90](https://github.com/barrelstrength/craft-sprout-email/issues/90) via [**ZenHub**](https://www.zenhub.com/)

**Comment by BenParizek** [comment]
@kotyy What is your desired behavior here if there is a syntax error in one of your email templates?

If a notification fails, would you prefer it fails silently and you have to look in the logs? Is there a reason you'd want to be able to have a field that doesn't exist in your templates?

**Comment by kotyy** [comment]
I think ideally, there would be a EM when saving a notification that references a non-existent field, if that's possible. If not, I think silently failing on the notification and logging that the notification failed for "invalid reply-to address" or something, when a visitor submits the form is more elegant than displaying a ISE to the visitor, because, ultimately, the form did save.


In this particular case, our client duplicated a notification and changed the related form, but didn't notice the reply-to field didn't exist on the form it was now referencing. This resulted in the notifications "inexplicably" not working.

**Comment by BenParizek** [comment]
@kotyy Thanks for the additional context. We'll explore our options here and see what we come up with.

**Comment by BenParizek** [comment]
@kotyy This issue has been addressed in Sprout Email v4.0.0-beta.10.

We've improved how errors are thrown in several scenarios to attempt to indicate when there may be issues when saving as much as possible.
