### ISSUE TITLE
Unable to find component class 'SproutForms_Forms'.

### ISSUE THREAD

**Issue by davist11** [barrelstrength/craft-sprout-forms#204]
### Description
I'm updating a site from Craft 2 > 3. We have a section that has a **Sprout Forms Forms** field, but it doesn't look like the field type was correctly migrated in the Craft 3 update. When I visit an entry form for that section I get the following error in place of the field:

```
Unable to find component class 'SproutForms_Forms'.
```

### Steps to reproduce

1. On Craft 2, create a field of Sprout Forms Forms type
1. Assign that field to a section
1. Update to Craft 3
1. Visit an entry form for that section

### Additional info

- Craft version: Craft Pro 3.0.34
- PHP version: 7.1.20
- Database driver & version: MySQL 5.7.23
- Plugins & versions: Sprout Forms 3.0.0-beta.34

**Comment by BenParizek** [comment]
@davist11 We just pushed Sprout Forms v3.0.0-beta.35 which resolves this issue.
