### ISSUE TITLE
Calling unknown method: craft\fields\MissingField::getExampleInputHtml()

### ISSUE THREAD

**Issue by m8brgarc** [barrelstrength/craft-sprout-forms#209]
### Description
Twig_Error_Runtime: Calling unknown method: craft\fields\MissingField::getExampleInputHtml() in /<project_directory>/vendor/barrelstrength/sprout-forms/src/templates/_includes/formbuilder.twig:52
Stack trace:
#0 /<project_directory>/storage/runtime/compiled_templates/18/1880655a289348be1ffcb1c5a4cbd6f415184a3bd2eaeb69f0635ca1c57a0196.php(200): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(craft\fields\MissingField), 'getExampleInput...', Array, 'method')
#1 /<project_directory>/storage/runtime/compiled_templates/18/1880655a289348be1ffcb1c5a4cbd6f415184a3bd2eaeb69f0635ca1c57a0196.php(71): __TwigTemplate_63538e1142764d0804921a8b33e75b21302356987b7680b01475d08dba28d953->macro_field(Object(craft\fields\MissingField), 'active', Object(craft\models\FieldLayoutTab))
#2 /<project_directory>/storage/runtime/compiled_templates/f6/f67b56279f89212163970bea2c76023fb618b590b6f3dce8d404267fd38d63c1.php(240): __TwigTemplate_63538e1142764d0804921a8b33e75b21302356987b7680b01475d08dba28d953->macro_tab(Object(craft\models\FieldLayoutTab), Array, false)
#3 /<project_directory>/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_be1fd141a5595c343a477c807c2a34624f617cdc4697ff0b07f976524179029c->block_content(Array, Array)
#4 /<project_directory>/storage/runtime/compiled_templates/52/52b94a686b6521ea3604007880687427ad6e16cc57285848e39ae6a286b02f10.php(648): Twig_Template->displayBlock('content', Array, Array)
#5 /<project_directory>/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_d3cd7cd974a7d0e89286ead0294a6ce436c31cf7838ff1b2a500faadcba23c6e->block_main(Array, Array)
#6 /<project_directory>/storage/runtime/compiled_templates/52/52b94a686b6521ea3604007880687427ad6e16cc57285848e39ae6a286b02f10.php(533): Twig_Template->displayBlock('main', Array, Array)
#7 /<project_directory>/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_d3cd7cd974a7d0e89286ead0294a6ce436c31cf7838ff1b2a500faadcba23c6e->block_body(Array, Array)
#8 /<project_directory>/storage/runtime/compiled_templates/80/804001ff7dd9f93f3af81862158dc4b50ed4e97515b24aa037f3b0a34dfab263.php(60): Twig_Template->displayBlock('body', Array, Array)
#9 /<project_directory>/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_a8e4c415af73b46a7b6524e2a6d11197b3c9663f73d84a6347b5d7fd9b4e22b7->doDisplay(Array, Array)
#10 /<project_directory>/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#11 /<project_directory>/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#12 /<project_directory>/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#13 /<project_directory>/storage/runtime/compiled_templates/ca/ca93de2e3c4deb3eacda279b48149d387885122b2eed2fa4a5865456a9d71c99.php(40): craft\web\twig\Template->display(Array, Array)
#14 /<project_directory>/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_7a419d8fcaa9d5b6cfba8d52a3428310a9c2014cc42083e62f8fa58c4d32c965->doDisplay(Array, Array)
#15 /<project_directory>/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#16 /<project_directory>/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#17 /<project_directory>/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#18 /<project_directory>/storage/runtime/compiled_templates/52/52b94a686b6521ea3604007880687427ad6e16cc57285848e39ae6a286b02f10.php(95): craft\web\twig\Template->display(Array, Array)
#19 /<project_directory>/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_d3cd7cd974a7d0e89286ead0294a6ce436c31cf7838ff1b2a500faadcba23c6e->doDisplay(Array, Array)
#20 /<project_directory>/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#21 /<project_directory>/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#22 /<project_directory>/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#23 /<project_directory>/storage/runtime/compiled_templates/5e/5e0630267a6886c226823b8b785f637aea50dc25facd832192a59b3b4e421cbe.php(34): craft\web\twig\Template->display(Array, Array)
#24 /<project_directory>/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_6d60a9e9a494c78daddba8b6bcff765d0ff4268f250feb2827ad68f8f65b16e3->doDisplay(Array, Array)
#25 /<project_directory>/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#26 /<project_directory>/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#27 /<project_directory>/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#28 /<project_directory>/storage/runtime/compiled_templates/f6/f67b56279f89212163970bea2c76023fb618b590b6f3dce8d404267fd38d63c1.php(118): craft\web\twig\Template->display(Array, Array)
#29 /<project_directory>/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_be1fd141a5595c343a477c807c2a34624f617cdc4697ff0b07f976524179029c->doDisplay(Array, Array)
#30 /<project_directory>/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#31 /<project_directory>/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#32 /<project_directory>/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#33 /<project_directory>/vendor/twig/twig/lib/Twig/Template.php(375): craft\web\twig\Template->display(Array)
#34 /<project_directory>/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#35 /<project_directory>/vendor/craftcms/cms/src/web/View.php(331): Twig_Environment->render('sprout-forms/fo...', Array)
#36 /<project_directory>/vendor/craftcms/cms/src/web/View.php(378): craft\web\View->renderTemplate('sprout-forms/fo...', Array)
#37 /<project_directory>/vendor/craftcms/cms/src/web/Controller.php(156): craft\web\View->renderPageTemplate('sprout-forms/fo...', Array)
#38 /<project_directory>/vendor/barrelstrength/sprout-forms/src/controllers/FormsController.php(195): craft\web\Controller->renderTemplate('sprout-forms/fo...', Array)
#39 [internal function]: barrelstrength\sproutforms\controllers\FormsController->actionEditFormTemplate(3593, Object(barrelstrength\sproutforms\elements\Form))
#40 /<project_directory>/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#41 /<project_directory>/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#42 /<project_directory>/vendor/craftcms/cms/src/web/Controller.php(104): yii\base\Controller->runAction('edit-form-templ...', Array)
#43 /<project_directory>/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit-form-templ...', Array)
#44 /<project_directory>/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('sprout-forms/fo...', Array)
#45 /<project_directory>/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('sprout-forms/fo...', Array)
#46 /<project_directory>/vendor/craftcms/cms/src/web/Application.php(271): yii\web\Application->handleRequest(Object(craft\web\Request))
#47 /<project_directory>/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#48 /<project_directory>/web/index.php(21): yii\base\Application->run()
#49 {main}

### Steps to reproduce

1.  I copied the entire database from the staging server to my local environment.

This is the first time I've had this issue.

### Additional info

- Craft version: 3.0.36
- PHP version: 7.1.12
- Database driver & version: MySQL 5.6.38
- Plugins & versions: "barrelstrength/sprout-forms": "3.0.0-beta.35"

**Comment by BenParizek** [comment]
Thanks for reporting @m8brgarc.

@andrelopez Let's consider creating a Sprout Forms missing field that matches Craft's Missing Field behavior so we don't throw an error in this instance but instead render the page and show that a field doesn't exist: http://share.barrelstrength.co/468782841ad6

**Comment by BenParizek** [comment]
@m8brgarc While we get a solution in place for this, if you still need to resolve this the issue is that at some point in time you added a field to the Craft db that is no longer present in Craft. Perhaps you installed a plugin with a custom field, added it to a Form, and then uninstalled the plugin, or something like that.

To resolve the issue manually, you can look through the `craft_fields` table and try to identify the field that appears to be missing and either reinstall whatever plugin makes it available again or, if you are comfortable doing so, delete the row to clean things up.

We'll let you know when we have a better error message in place to reveal more about what might be happening.

**Comment by BenParizek** [comment]
@m8brgarc We've improved the error messages around missing fields in Sprout Forms v3.0.0-beta.37. Let us know if you run into any other issues.
