### ISSUE TITLE
Stalled SproutSeo_Delete404 task

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-forms#213]
<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_gk83)

**Comment by andrelopez** [comment]
Issue moved to [barrelstrength/craft-sprout-seo #129](https://github.com/barrelstrength/craft-sprout-seo/issues/129) via [**ZenHub**](https://www.zenhub.com/)
