### ISSUE TITLE
Twig_Error_Runtime: Calling unknown method: lewisjenkins\craftdynamicfields\fields\Dropdown::getExampleInputHtml()

### ISSUE THREAD

**Issue by kgi-cwells** [barrelstrength/craft-sprout-forms#217]
### Description
I'm in the middle of upgrading a Craft 2.7.4 site to 3.0.37, and on one particular form I have a dynamic field that was created with the Craft Dynamic Fields plugin. When I try to edit the form in Sprout Forms, I get this error. I've tried uninstalling and reinstalling the Dynamic Fields plugin. I noticed a similar issue #209  but my error at least references another plugin's field rather than "MissingField", so I figured I'd add this new issue.

### Steps to reproduce

1. Create a form that uses a dynamic Dropdown field ('lewisjenkins\craftdynamicfields\fields\Dropdown') 
 in Craft 2
2. Migrate that craft 2 site to Craft 3, update your plugins and try to edit that form.

### Additional info

Craft version: 3.0.37
PHP version: 7.1.25
Database driver & version: MySQL 5.5.5
Plugins & versions: 
"barrelstrength/sprout-forms": "3.0.0-beta.35"
"lewisjenkins/craft-dynamic-fields": "3.0.6"

### Error
Full Stack Trace here:
[https://gist.github.com/kgi-cwells/8d85cc6a922fd83f742473c41ad75259](https://gist.github.com/kgi-cwells/8d85cc6a922fd83f742473c41ad75259)

**Comment by BenParizek** [comment]
We've rebuilt the Sprout Forms Form Field API from the ground up in Craft 3 so the way the plugin handles custom fields has changed and is going to require that you (or the author of the plugin) build a custom LG Dynamic Fields Form Field to get things working in the same way or find another way to address how you are using it.

In Craft 2, Sprout Forms was piggybacking on the Craft Field API and UI. This got us moving quickly but limited a lot of the newer functionality that we've been adding. In Craft 3, we still extend the Craft 2 Field behavior on the back end but all Front-End Field behavior is handled through our own Front-End Form Field API.

You can read more about the Form Field API here:
https://sprout.barrelstrengthdesign.com/docs/forms/custom-form-fields.html

There are example Form Field plugins linked on the doc page that might be a good starting point. I'm not too familiar with the field so if you'd like to elaborate on what you're trying to use it for I might be able to offer more specific alternatives to consider.

As we don't intend to add support for any 3rd party fields I'm going to close this issue, but feel free to follow up if you have additional questions on building a Form Field or are interested in custom development to help get things upgraded.
