### ISSUE TITLE
File Upload Field not referencing Asset Volumes correctly in Craft 3.1

### ISSUE THREAD

**Issue by SamLNL** [barrelstrength/craft-sprout-forms#221]
### Description
Whenever I try to submit a form with a file input, I get the error `The {field} field’s {setting} setting is set to an invalid volume.`.

My twig code for displaying the form:
`{{ craft.sproutForms.displayForm('form4') }}`

I'm not using any custom form templates, all is just basic.
Upload folder also exists.

Anyone with same problem? 

### Steps to reproduce

1. Create a simple form with (I used a name field and file upload field)

![screenshot at jan 23 14-50-34](https://user-images.githubusercontent.com/21331474/51611171-e1d7b180-1f1e-11e9-903b-ae65a4c8f88c.png)

2. Submit form

### Additional info

- Craft version: Craft Solo 3.1.3
- PHP version: 7.1.26
- Database driver & version: MySQL 5.7.24
- Plugins & versions: Sprout Forms 3.0.0-beta.35

**Comment by BenParizek** [comment]
@SamLNL Do you have any volumes created in Settings->Assets->Volumes?

**Comment by SamLNL** [comment]
I do:

![screenshot at jan 23 15-05-56](https://user-images.githubusercontent.com/21331474/51611872-8f979000-1f20-11e9-87ac-0d99ebb6485b.png)

I also tried it with 'public' urls enabled. No difference.

**Comment by SamLNL** [comment]
I also did a trace to find out where the Exception was given. I found out that it is calling the method METHODE and it exploding my SINGLESOURCEPATHDINGIETS. The second value in the list(array) is expected to be numeric but is an uid (which is a string). Just a brainfart

**Comment by BenParizek** [comment]
@SamLNL Ok. Silly question. You do and it's called Uploads and exists, as you said.

I'm unable to recreate this bug yet in my tests.

Can you confirm the type of Asset Source you are using with Uploads? Is it Local?

Does the form fail to submit just when you try to submit a file or anytime you try to submit?

If you are comfortable looking at the database, can you share the settings for your File Upload field and the ID of your Asset Source? It seems that those IDs don't match for some reason:

File Upload field settings would be in `fields.settings` (they are stored as JSON)
The ID of your Volume is in the URL of that Asset settings page: http://share.barrelstrength.co/f6d3f7c8dc94

**Comment by BenParizek** [comment]
@SamLNL Ah, ok. Your last comment points out the issue. You are using Craft 3.1 and we have not yet added Craft 3.1 support. Craft changes the way they store references to other Elements. 

We're working on adding support for this and I can update this thread once we get this out but we still need to get through a few other releases this week before we turn our attention to that. In the meantime, you would need to roll back to a Craft release prior to 3.1 to use Sprout Forms until we get that out.

**Comment by SamLNL** [comment]
Thanks for the quick response. I will try a roll back for now.

**Comment by SamLNL** [comment]
A roll back would be a problem, Craft doesn't accept the roll back because of some database changes. I will lose a lot of content when replacing this database.

I have two websites scheduled to go live next week. Any idea when I can expect a fix (new update) for this issue? Or do I need to think of a temporary solution?

**Comment by BenParizek** [comment]
@SamLNL I can't promise any release dates. We're wrapping through some updates we need to complete first. We hope to have out those out this week. After that, we'll turn our attention to 3.1. We'll do our best to have the updates out soon, but if you need a sure thing for a launch, you may need to consider a temporary solution.

**Comment by BenParizek** [comment]
@SamLNL We've added initial Craft 3.1 support in Sprout Forms v3.0.0-beta.37. Let us know if you run into any other issues.
