### ISSUE TITLE
Calling unknown method: barrelstrength\sproutforms\fields\formfields\SingleLine::getField()

### ISSUE THREAD

**Issue by darylknight** [barrelstrength/craft-sprout-forms#230]
### Description

I can see there's an issue for this already (https://github.com/barrelstrength/craft-sprout-forms/issues/169), but there's no description for it other than "Front conversations" which I can't access, so I can't tell what caused it or if it was resolved in a release.

If I follow the migration docs which say to add `.one()` to the end of `craft.sproutForms.form(form.handle)` then I get this error:

    Calling unknown method: barrelstrength\sproutforms\elements\Form::one()

If I don't add `.one()`, and try to use the template code from the docs, I get this error:

![image](https://user-images.githubusercontent.com/1250017/52335165-5e33bf80-2a0a-11e9-87bf-68bf132306a6.png)

### Steps to reproduce

1. Upgraded Craft from 2.7.4 to 3.0.40
2. Migrate using the guide from the Sprout Forms docs

### Additional info

- Craft version: 3.0.40
- PHP version: 7.3.0
- Database driver & version: MySQL
- Plugins & versions: Sprout Forms 3.0.0-beta.36 (I tried beta 37 and 38, but the migrations failed)

**Comment by andrelopez** [comment]
Hi @darylknight 

You may need also update your custom templates to use either the `basic` folder (you'll found fewer changes if you come from Craft 2) or the `accessible` folder.

The `getField()` method is not available in Craft 3 anymore, please take a look at the `tab.twig` template.

Please let me know if you have any questions.

**Comment by darylknight** [comment]
Thanks for replying Andre! I'm using the documentation on the Sprout Forms website here: https://sprout.barrelstrengthdesign.com/docs/forms/custom-html.html#loop-through-all-fields-dynamically which contains `{% set field = field.getField() %}`.

Is the documentation wrong? If I flick between the craft 3 / craft 2 version, literally the only thing that changes is adding `.one()` to the form method, which actually causes it to break (see second issue above).

**Comment by BenParizek** [comment]
@darylknight I'd recommend using the suported [Template Overrides](https://sprout.barrelstrengthdesign.com/docs/forms/template-overrides.html#customizing-templates) if possible. They are designed to be pretty flexible and custom HTML gets into a lot more complexity.

I think we've got two things going on above.

1. I can recreate the error that you are seeing when you add `.one()` to the form statement: `craft.sproutForms.form(form.handle).one()`. I expect this is a bug and we'll look into that. For now, it does seem you can just remove the .one and get things working.
2. The Craft 3 Custom HTML example has not been updated completely yet. I'll get a change pushed to that shortly. For now, here's an example you can work with below (and just to note it again, [Template Overrides](https://sprout.barrelstrengthdesign.com/docs/forms/template-overrides.html#customizing-templates) would allow you to override just the parts of the code you need to below without needing to get into maintaining the whole dynamic form template architecture on your own, which you will have to do going the Custom HTML route) 

```{% set form = craft.sproutForms.form('contact').one() %}

{%- for tab in form.getFieldLayout().getTabs() %}
    {%- for tab in tabs -%}
    
        {%- set layoutFields = tab.getFields() %}
    
        <section class="tab">
    
            {% if form.displaySectionTitles -%}
                <h3>{{ tab.name|t }}</h3>
            {%- endif %}
    
            {% for field in layoutFields -%}
            
                {%- do craft.sproutForms.addFieldVariables(_context) -%}
                
                {%- set label            = field.name ?? null %}
                {%- set instructions     = field.instructions ?? null %}
                {%- set name             = field.handle ?? null %}
                {%- set required         = field.required is defined and field.required ? true : false %}
                {%- set renderingOptions = attribute(renderingOptions.fields, name) is defined ? renderingOptions.fields[name] : {} %}
                
                {%- set id               = renderingOptions.id ?? name %}
                {%- set class            = renderingOptions.class ?? name ~ '-field' %}
                {%- set value            = entry is not empty ? entry.getFieldValue(name) : null %}
                {%- set errors           = entry is not empty ? entry.getErrors(name) : null %}
                {%- set errorClass       = renderingOptions.errorClass ?? 'errors' %}
                {%- set fieldCssClasses  = field['cssClasses'] is defined and not null ? field.cssClasses : '' %}
                
                {%- namespace field.getNamespace() -%}
                    {%- if field.isPlainInput() -%}
                
                        {{ input|raw }}
                
                    {%- else %}
                
                        {% set fieldHtmlTag = field.hasMultipleLabels() ? 'fieldset' : 'div' -%}
                
                        <{{ fieldHtmlTag }}
                        {%- if id %} id="{{ id }}-field"{% endif %} class="field {{ field.getFieldInputFolder() }}
                        {%- if class %} {{ class }}{% endif -%}
                        {%- if fieldCssClasses %} {{ fieldCssClasses }}{% endif -%}
                        {%- if errors %} {{ errorClass }}{% endif -%}
                        {%- if required %} required{% endif -%}
                        ">
                        {% if (label or instructions) and field.displayLabel() -%}
                            <div class="heading">
                                {% if label -%}
                                    {%- if field.hasMultipleLabels() -%}
                                        <legend>{{- label|raw|t('site') -}}</legend>
                                    {%- else -%}
                                        <label{% if name %} for="{{ name }}"{% endif %}>
                                            {{- label|raw|t('site') -}}
                                        </label>
                                    {%- endif -%}
                                {%- endif -%}
                                {% if instructions %}
                
                                    <p id="{{ id }}-instructions"
                                       class="instructions">{{ instructions|t('site')|raw }}</p>
                                {%- endif %}
                
                            </div>
                        {% endif -%}
                
                        <div class="input">
                            {{ input|raw }}
                        </div>
                        {% include "errors" with {
                            errors: errors,
                            name: name
                        } %}
                
                        </{{ fieldHtmlTag }}>
                    {%- endif -%}
                {%- endnamespace -%}
                
            {%- endfor %}
    
        </section>
    
    {%- endfor -%}
{% endfor -%}```

**Comment by BenParizek** [comment]
I've opened another ticket for the `.one()` bug. 
https://github.com/barrelstrength/craft-sprout-forms/issues/236

I've got the example above queued for release in the docs alongside some other updates. Closing this out for now.

**Comment by BenParizek** [comment]
@darylknight For what it's worth, we've decided that the `.one()` tag is not needed for this use case and have removed references for it from the documentation.

The correct usage is what you had in your first example: `craft.sproutForms.form(form.handle)`

**Comment by darylknight** [comment]
Got it - thank you
