### ISSUE TITLE
Visiting 'Reports' causes a Database Exception error

### ISSUE THREAD

**Issue by darylknight** [barrelstrength/craft-sprout-forms#231]
### Description
I just clicked on 'reports' in the Sprout Forms sidebar entry, and got this:

![image](https://user-images.githubusercontent.com/1250017/52399839-183c3180-2ac6-11e9-909b-53e2f536b99e.png)

### Additional info

- Craft version: 3.0.40
- PHP version: 7.3
- Database driver & version: MySQL
- Plugins & versions: Sprout Forms 3.0.0-beta.36

**Comment by andrelopez** [comment]
Hi @darylknight 

Could you please confirm us if the error persists on Craft 3.1 and Sprout Forms v3.0.0-beta.41 ?

Best

**Comment by darylknight** [comment]
Yep, still happening

**Comment by andrelopez** [comment]
@darylknight it looks like a migration never was executed. Are you able to send us your DB to support@barrelstrengthdesign.com ?
