### ISSUE TITLE
Accessible templates labels

### ISSUE THREAD

**Issue by missmatsuko** [barrelstrength/craft-sprout-forms#235]
#### Opt-in fields
The Opt-in field is using the same ID for its `input` element and wrapper `div` element. 

This makes the hit area for the opt-in field very small since the label text can no longer be clicked to toggle its input.

It's also invalid markup since the same ID should not be used more than once on a page.

```
<!-- Optin example -->
<div id="fields-optIn2-field" class="field optin optIn2-field">
    <div class="input">
        <div id="fields-optIn2" class="optIn2">
            <input type="hidden" aria-hidden="true" name="fields[optIn2]" value="">
            <label for="fields-optIn2">
                <input type="checkbox" name="fields[optIn2]" id="fields-optIn2" value="1" aria-checked="false"> Agree to terms?</label>
        </div>
    </div>
</div>
```

#### Name field
The labels in the name fields aren't attached to their inputs either implicitly (wrapped) or explicitly (for/id).

### Steps to reproduce

1. Create a form using the Accessible Template and an Opt-in field

### Additional info

- Craft version: 3.0.40
- PHP version:
- Database driver & version:
- Plugins & versions: 3.0.0-beta.36 (latest one before Craft 3.1 required)

**Comment by BenParizek** [comment]
Thanks for reporting @missmatsuko 

We'll address this shortly. In the meantime, if you'd like a workaround you can override the HTML for the Opt-in field (or any fiedl) using [Template Overrides](https://sprout.barrelstrengthdesign.com/docs/forms/template-overrides.html)

**Comment by missmatsuko** [comment]
@BenParizek Thanks, will do. I added another field to this issue that has a similar problem with labels not attached to their inputs.

**Comment by BenParizek** [comment]
@missmatsuko We've updated our default Form Templates in the latest release to address the items you listed above about the Opt-in and Name field:

- https://github.com/barrelstrength/craft-sprout-forms/blob/v3.0.0-beta.44/src/templates/_components/formtemplates/accessible/fields/optin/input.twig
- https://github.com/barrelstrength/craft-sprout-forms/blob/v3.0.0-beta.44/src/templates/_components/formtemplates/accessible/fields/name/input.twig

Thanks for catching those details.
