### ISSUE TITLE
File Upload field: Integrity constraint violation

### ISSUE THREAD

**Issue by darylknight** [barrelstrength/craft-sprout-forms#237]
### Description

Using the `{{ craft.sproutForms.displayForm('blogPostSubmission') }}` tag with an image upload field, submitting the form works if I don't upload anything, but if I attach a small image file, I get this:

![image](https://user-images.githubusercontent.com/1250017/52709685-1d055780-2f96-11e9-81aa-5d9be8a0eece.png)

### Additional info

- Craft version: 3.1.8
- PHP version: 7.3
- Database driver & version: MySQL

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_hixv)

**Comment by BenParizek** [comment]
Thanks @darylknight. We'll look into this as soon as we can.

**Comment by andrelopez** [comment]
Hi @darylknight 

This looks like a db error. Are you able to save images in your Assets section on the CP?

**Comment by darylknight** [comment]
Yes - they're in S3

**Comment by andrelopez** [comment]
Hi @darylknight 
We are currently unable to recreate this issue and think it is due to an error that occurred during a migration. As you've moved on from the issue and we can't recreate it, we'll close this out for now but please reopen if it becomes an issue again and we may need to dig into your database more specifically to track down what is going on.

**Comment by ogilv** [comment]
Might be of interest: I got the exact same database error when trying to upload an asset from the front-end in a `<form>` that lacked `enctype="multipart/form-data"` attribute. 

I wasn't using Sprout Forms, but this might fix your issue just the same. (See also at [StackOverflow](https://craftcms.stackexchange.com/a/2349/37).)
