### ISSUE TITLE
Tab navigation is not responsive in CP

### ISSUE THREAD

**Issue by darylknight** [barrelstrength/craft-sprout-forms#238]
### Description

The site I'm upgrading from Craft 2 to 3 at the moment has a form with 13 tabs. With the current design / layout, tabs are not editable depending on how large your screen is

![image](https://user-images.githubusercontent.com/1250017/52714864-a707ed00-2fa3-11e9-84ee-60b4006c431a.png)

### Additional info

- Craft version: 3.1.8
- PHP version: 7.3

**Comment by BenParizek** [comment]
Thanks for reporting @darylknight. I can recreate this. We'll look into getting a fix out soon.

**Comment by BenParizek** [comment]
@darylknight This has been fixed in Sprout Forms v3.0.0-beta.44.

Tabs will now allow you to scroll if you have more tabs than the available space in the tab bar.

**Comment by darylknight** [comment]
Great, thanks!
