### ISSUE TITLE
OnBeforeSaveEntryEvent handler: if fail

### ISSUE THREAD

**Issue by wei2go** [barrelstrength/craft-sprout-forms#241]
### Description

Hi Ben,

First of all, the doc on this page seems to be a bit confusing on the 'Before a Form Entry is Saved' section: 

https://sprout.barrelstrengthdesign.com/docs/forms/events-and-hooks.html#events

It shows the same code & params as the OnSaveEntryEvent

Also, I think the example code should be something like:

```
use barrelstrength\sproutforms\services\Entries;
use barrelstrength\sproutforms\elements\Entry;
use barrelstrength\sproutforms\events\OnBeforeSaveEntryEvent;

Event::on(Entries::class, Entry::EVENT_BEFORE_SAVE, function(OnBeforeSaveEntryEvent $event) {
// ...
});
```

Otherwise, the $event variable we get is actually an instance of ModelEvent, instead of OnBeforeSaveEntryEvent

-------------------------

Anyway, I'm struggling with this thing which I couldn't get my heads around:

Basically speaking, I'm trying to figure out what's the best way to skip the entry saving process and return to the form page with errors within the OnBeforeSaveEntryEvent handler (e.g. when doing a payment inside OnBeforeSaveEntryEvent handler but the payment fails).

I've spotted this chunk of code in the entry service, after the OnBeforeSaveEntryEvent is triggered but before entry is saved:

```
$event = new OnBeforeSaveEntryEvent([
            'entry' => $entry
        ]);

        $this->trigger(EntryElement::EVENT_BEFORE_SAVE, $event);

        $db = Craft::$app->getDb();
        $transaction = $db->beginTransaction();

        try {
            if (!$event->isValid) {
                foreach ($event->errors as $key => $error) {
                    $entry->addError($key, $error);
                }

                SproutForms::error('OnBeforeSaveEntryEvent is not valid');

                if ($event->fakeIt) {
                    SproutForms::$app->entries->fakeIt = true;
                }

                return false;
            }

            $success = Craft::$app->getElements()->saveElement($entry);
      
            // ...
```

But I'm not quite familiar with the whole Event system in Craft. I thought I could do something like:

```
$event->isValid = false;
$event->errors = array('attr' => 'err message');
```

But that doesn't really work. The entry is still saved.

So, can you suggest what's the best way to achieve that please?

### Steps to reproduce

1.
2.

### Additional info

- Craft version: Craft 3.1.10
- PHP version: 7.0
- Database driver & version: 
- Plugins & versions: 3.0.0-beta.44

**Comment by BenParizek** [comment]
@wei2go Thanks for the detailed message. You're right about the documentation. I'll get that updated. I've just tested the following code and I'm seeing the error get returned and no entry get saved. At first glance, I feel you are using the same code and are saying you are getting different results (the entry being saved) so if that's the case, we'll probably need to dig in more to your other settings and why that may be happening.

```
use barrelstrength\sproutforms\services\Entries;
use barrelstrength\sproutforms\elements\Entry;
use barrelstrength\sproutforms\events\OnBeforeSaveEntryEvent;

Event::on(Entries::class, Entry::EVENT_BEFORE_SAVE, function(OnBeforeSaveEntryEvent $event) {
  $event->isValid = false;
  $event->errors['whoops'] = 'Not Having it.';
});
```

As the error we're adding isn't associated with any existing field name in my example, I also have to add a generic way to just show all errors that are happening in my templates:

```
{% if contact.getErrors()|length %}
    {{ dump(contact.getErrors()) }}
{% endif %}
```

If that still doesn't work for you, can you try to add a few `die()` statements around that `if (!$event->isValid) {` code and see what conditions are passing and failing? If easier to troubleshoot in real time, feel free to book a half hour with me and we can dig into it together: https://sprout.barrelstrengthdesign.com/docs/support/training.html

**Comment by wei2go** [comment]
Hi @BenParizek,

Thanks for looking into this. Appreciate that.

I explained a bit in my pull request https://github.com/barrelstrength/craft-sprout-forms/pull/243, the reason I'm getting $event->isValid === true eventually is probably because I have this [Google reCaptcha for Sprout Forms plugin](https://plugins.craftcms.com/sprout-forms-google-recaptcha) installed. I believe it listens to the same OnBeforeSaveEntryEvent but its handler gets executed later than mine and that probably overrides the $event->isValid value after doing a validation.

So, I wonder, when you do the test, did you have the reCaptcha plugin enabled? If you have that in use, but still getting $event->isValid === false, then it might be something else.

I still think the best solution is adding additional param to the event class like my pull request suggests so we can have more control of it without worrying the isValid param getting overridden. Can you consider pulling or doing something similar to that please?

Cheers,

**Comment by wei2go** [comment]
Or, in the following code in services/Entries.php => saveEntry()

```
$event = new OnBeforeSaveEntryEvent([
            'entry' => $entry
        ]);

        $this->trigger(EntryElement::EVENT_BEFORE_SAVE, $event);

        $db = Craft::$app->getDb();
        $transaction = $db->beginTransaction();

        try {
            if (!$event->isValid) {
                foreach ($event->errors as $key => $error) {
                    $entry->addError($key, $error);
                }

                SproutForms::error('OnBeforeSaveEntryEvent is not valid');

                if ($event->fakeIt) {
                    SproutForms::$app->entries->fakeIt = true;
                }

                return false;
            }

            $success = Craft::$app->getElements()->saveElement($entry);
```
Instead of doing `if (!$event->isValid)`, can you consider doing `if (!$event->isValid or !empty($event->errors))`?

**Comment by wei2go** [comment]
> Or, in the following code in services/Entries.php => saveEntry()
> 
> ```
> $event = new OnBeforeSaveEntryEvent([
>             'entry' => $entry
>         ]);
> 
>         $this->trigger(EntryElement::EVENT_BEFORE_SAVE, $event);
> 
>         $db = Craft::$app->getDb();
>         $transaction = $db->beginTransaction();
> 
>         try {
>             if (!$event->isValid) {
>                 foreach ($event->errors as $key => $error) {
>                     $entry->addError($key, $error);
>                 }
> 
>                 SproutForms::error('OnBeforeSaveEntryEvent is not valid');
> 
>                 if ($event->fakeIt) {
>                     SproutForms::$app->entries->fakeIt = true;
>                 }
> 
>                 return false;
>             }
> 
>             $success = Craft::$app->getElements()->saveElement($entry);
> ```
> Instead of doing `if (!$event->isValid)`, can you consider doing `if (!$event->isValid or !empty($event->errors))`?

Hi @BenParizek , kindly following up on this post.

**Comment by BenParizek** [comment]
@wei2go We've added a check for errors in the latest release (v3.0.0-beta.50)
https://github.com/barrelstrength/craft-sprout-forms/blob/v3.0.0-beta.50/src/services/Entries.php#L296

Thanks for your patience on this one.
