### ISSUE TITLE
Unable to set Dynamic 'Reply To' email

### ISSUE THREAD

**Issue by andrelopez** [barrelstrength/craft-sprout-forms#247]
<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_hitv)

**Comment by pdaleramirez** [comment]
@BenParizek This commit on sprout-base-email https://github.com/barrelstrength/craft-sprout-base-email/commit/d73ae5052609971379dd3b899ca2a74bcfa08d8a should fix the issue on the next release
