### ISSUE TITLE
"Cannot drop index" Error on migration from Craft 2 to Craft 3

### ISSUE THREAD

**Issue by andrelopez** [barrelstrength/craft-sprout-forms#250]
<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_hmgr)

**Comment by BenParizek** [comment]
This has been resolved. A script timed out and lead to a broken database migration scenario.
