### ISSUE TITLE
Exception "Calling unknown method: craft\console\Request::getBodyParam()" during upgrade from Craft 2

### ISSUE THREAD

**Issue by mklishevych** [barrelstrength/craft-sprout-forms#252]
### Description

Issue is pretty much the same as in #207

**Comment by BenParizek** [comment]
@mklishevych The ticket you linked to references Craft 3.0.35 and unspecific version numbers for Sprout Forms and Sprout Fields. Can you upgrade to the latest of Craft (3.1.x) and the Sprout Plugins and confirm if you are still getting the issue and the specific plugin versions you are getting the issue with?

**Comment by mklishevych** [comment]
This can be closed as I've completed the migration to Craft 3.
