### ISSUE TITLE
Sprout Forms settings not loaded from project.yaml when installing the plugin

### ISSUE THREAD

**Issue by boboldehampsink** [barrelstrength/craft-sprout-forms#254]
### Description

Sprout Forms uses its default settings in stead of the settings saved in the project config when installing from project config. It then overwrites the project config settings with the default settings.

### Steps to reproduce

1. Install Sprout Forms and save settings to Project Config
2. Install new Craft site with that Project Config
3. Sprout Forms settings in project.yaml are back to default

### Additional info

- Craft version: 3.1.18
- PHP version: 7.3.3
- Database driver & version: PostgreSQL 10.7
- Plugins & versions: Sprout Forms 3.0.0-beta.46

**Comment by BenParizek** [comment]
Thanks @boboldehampsink. We'll look into it.

**Comment by boboldehampsink** [comment]
This is because Sprout Forms always installs default data on install: https://github.com/barrelstrength/craft-sprout-forms/blob/v3/src/migrations/Install.php#L207

It should propably check if there are Project Config settings already in place first.

**Comment by BenParizek** [comment]
@boboldehampsink This has been resolved in the latest release (v3.0.0-beta.50)
