### ISSUE TITLE
Missing return statement in migration

### ISSUE THREAD

**Issue by yaychris** [barrelstrength/craft-sprout-forms#257]
### Description

A change introduced in `3.0.0-beta.46` adds return type annotations to migration files. However, [src/migrations/m180417_000000_sproutforms_craft3_schema_changes.php](https://github.com/barrelstrength/craft-sprout-forms/blob/v3.0.0-beta.46/src/migrations/m180417_000000_sproutforms_craft3_schema_changes.php) does not have a return value. This causes an error when the migration attempts to run.

### Additional info

- Craft version: 3.1.18
- PHP version: 7.2.15
- Database driver & version:
- Plugins & versions:

**Comment by boboldehampsink** [comment]
This is related to #260 and #255
