### ISSUE TITLE
Error visiting Notifications index

### ISSUE THREAD

**Issue by engram-design** [barrelstrength/craft-sprout-forms#261]
### Description
Getting the attached error when visiting Sprout Forms > Notifications. I do not have Sprout Email installed.

### Additional info
<img width="1318" alt="Screen Shot 2019-03-19 at 10 14 29 pm" src="https://user-images.githubusercontent.com/1221575/54602051-a8da3a00-4a94-11e9-89ee-877829ecba25.png">

- Craft version: 3.1.18
- PHP version: 7.0
- Plugins & versions: 3.0.0-beta.47

**Comment by BenParizek** [comment]
Looking into it.

**Comment by BenParizek** [comment]
@engram-design This should be resolved in the latest release: Sprout Forms v3.0.0-beta.48

Thanks for reporting.
