### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by MarcelWeidum** [barrelstrength/craft-sprout-forms#262]
### Description
Every time I try to create a new form it is loading very long and at the end i'm getting a 504 Gateway Time-out error.

### Steps to reproduce

1. Install sprout forms (tried beta 46, 47, 48)
2. Try to create a new form

### Additional info

- Craft version: 3.1.19
- PHP version: 7.2.15
- Database driver & version: MySQL 5.5.5
- Plugins & versions:
- Craft commerce 2.1.2
- FeedMe 3.1.12

**Comment by andrelopez** [comment]
Hi @MarcelWeidum 

We're unable to recreate this issue. Could you please recreate the issue and send back to us an email to support@barrelstrengthdesign.com with a zip file of the next folder: storage/logs

Best,

**Comment by BenParizek** [comment]
A Gateway Timeout probably means the server the site is on doesn't have enough resources dedicated to the processes necessary for the action and is like a server configuration issue.

Craft has a help doc with some suggestions here:
https://craftcms.com/guides/504-gateway-timed-out-error
