### ISSUE TITLE
Notifications Tab displays nothing in IE 11

### ISSUE THREAD

**Issue by riusi88** [barrelstrength/craft-sprout-forms#265]
A client of mine is unable to modify the Notifications tab, as it renders nothing in Internet Explorer 11. Unfortunately it's one of those clients that are locked into using IE 11, so asking them to use Chrome, Firefox or Edge is out of the question. I've duplicated the issue locally as well by browsing to the Notifications tab in IE 11. Again, nothing showed up, and yes I've successfully created and sent notifications in Chrome and Firefox in the same staging environment. 

The fix may be adding some polyfills to catch any errors that would prevent JS from executing in IE 11. 

- Craft version: 3.1.20.1
- PHP version: 7.2.8
- Plugins & versions:

**Comment by BenParizek** [comment]
Thanks for reporting @riusi88. We'll try to recreate and let you know when we have an update.

**Comment by BenParizek** [comment]
@riusi88 This has been resolved in v3.0.0-beta.51
