### ISSUE TITLE
Address field throws error after updating to 3.0.0-beta.49

### ISSUE THREAD

**Issue by riusi88** [barrelstrength/craft-sprout-forms#266]
I recently updated Sprout Forms to the latest release, and can no longer load any of my pages that use the Address field within a Sprout Form. I was previously using 3.0.0-beta.44 with no issue.

### Steps to reproduce

1. Install 3.0.0-beta.49
2. Create Form with Address Field
3. Place said form inside an Entry, and render it within a template
4. Load page (no problem)
5. Update Sprout Forms to 3.0.0-beta.49
6. Reload page with Form + Address field. Get Error

### ENV Info
- Craft version:3.1.20.1
- PHP version:7.2.13
- Database driver & version:
- Plugins & versions:3.0.0-beta.49

### Full Error:
`Error: Class 'barrelstrength\sproutforms\fields\formfields\Template' not found in /home/runcloud/webapps/site-name/vendor/barrelstrength/sprout-forms/src/fields/formfields/Address.php:122
Stack trace:
#0 /home/runcloud/webapps/site-name/vendor/barrelstrength/sprout-forms/src/web/twig/variables/SproutFormsVariable.php(203): barrelstrength\sproutforms\fields\formfields\Address->getFrontEndInputHtml(NULL, NULL)
#1 /home/runcloud/webapps/site-name/vendor/twig/twig/src/Extension/CoreExtension.php(1681): barrelstrength\sproutforms\web\twig\variables\SproutFormsVariable->displayField(Object(barrelstrength\sproutforms\elements\Form), Object(barrelstrength\sproutforms\fields\formfields\Address), Array)
#2 /home/runcloud/webapps/site-name/vendor/craftcms/cms/src/helpers/Template.php(79): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(barrelstrength\sproutforms\web\twig\variables\SproutFormsVariable), 'displayField', Array, 'method', false, false)
#3 /home/runcloud/webapps/site-name/storage/runtime/compiled_templates/4f/4fd1f0b19ae115e28f1086f8b2551098fd1db30c6d78a135d5951faa63f1b2e9.php(60): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(barrelstrength\sproutforms\web\twig\variables\SproutFormsVariable), 'displayField', Array, 'method')
#4 /home/runcloud/webapps/site-name/vendor/twig/twig/src/Template.php(379): __TwigTemplate_5c586ade1a5e236c73254bb195928f24184c7fd949a86b442ac181b274f1051e->doDisplay(Array, Array)
#5 /home/runcloud/webapps/site-name/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#6 /home/runcloud/webapps/site-name/vendor/twig/twig/src/Template.php(356): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#7 /home/runcloud/webapps/site-name/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#8 /home/runcloud/webapps/site-name/vendor/twig/twig/src/Template.php(364): craft\web\twig\Template->display(Array)
#9 /home/runcloud/webapps/site-name/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#10 /home/runcloud/webapps/site-name/vendor/twig/twig/src/Environment.php(319): Twig\TemplateWrapper->render(Array)
#11 /home/runcloud/webapps/site-name/vendor/craftcms/cms/src/web/View.php(343): Twig\Environment->render('tab', Array)
#12 /home/runcloud/webapps/site-name/vendor/barrelstrength/sprout-forms/src/web/twig/variables/SproutFormsVariable.php(141): craft\web\View->renderTemplate('tab', Array)
#13 /home/runcloud/webapps/site-name/vendor/twig/twig/src/Extension/CoreExtension.php(1681): barrelstrength\sproutforms\web\twig\variables\SproutFormsVariable->displayTab(Object(barrelstrength\sproutforms\elements\Form), 1573, Array)
#14 /home/runcloud/webapps/site-name/vendor/craftcms/cms/src/helpers/Template.php(79): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(barrelstrength\sproutforms\web\twig\variables\SproutFormsVariable), 'displayTab', Array, 'method', false, false)
#15 /home/runcloud/webapps/site-name/storage/runtime/compiled_templates/06/0649cb9e20060e1252875d6b001492949d55b64d4c736c077fcdb58056bab286.php(87): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(barrelstrength\sproutforms\web\twig\variables\SproutFormsVariable), 'displayTab', Array, 'method')
#16 /home/runcloud/webapps/site-name/vendor/twig/twig/src/Template.php(379): __TwigTemplate_ecab7a7c95519ae3ff5427b5063690f58d404d4084de0aa9b08381e5047487b0->doDisplay(Array, Array)
#17 /home/runcloud/webapps/site-name/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#18 /home/runcloud/webapps/site-name/vendor/twig/twig/src/Template.php(356): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#19 /home/runcloud/webapps/site-name/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#20 /home/runcloud/webapps/site-name/vendor/twig/twig/src/Template.php(364): craft\web\twig\Template->display(Array)
#21 /home/runcloud/webapps/site-name/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#22 /home/runcloud/webapps/site-name/vendor/twig/twig/src/Environment.php(319): Twig\TemplateWrapper->render(Array)
#23 /home/runcloud/webapps/site-name/vendor/craftcms/cms/src/web/View.php(343): Twig\Environment->render('form', Array)
#24 /home/runcloud/webapps/site-name/vendor/barrelstrength/sprout-forms/src/web/twig/variables/SproutFormsVariable.php(83): craft\web\View->renderTemplate('form', Array)
#25 /home/runcloud/webapps/site-name/vendor/twig/twig/src/Extension/CoreExtension.php(1681): barrelstrength\sproutforms\web\twig\variables\SproutFormsVariable->displayForm('form3', Array)
#26 /home/runcloud/webapps/site-name/vendor/craftcms/cms/src/helpers/Template.php(79): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(barrelstrength\sproutforms\web\twig\variables\SproutFormsVariable), 'displayForm', Array, 'method', false, false)
#27 /home/runcloud/webapps/site-name/storage/runtime/compiled_templates/f6/f6b0d94999ec343c0a7fd3742e8a34304e00a2e3f82fedafd11ec84841275a6b.php(45): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(barrelstrength\sproutforms\web\twig\variables\SproutFormsVariable), 'displayForm', Array, 'method')
#28 /home/runcloud/webapps/site-name/vendor/twig/twig/src/Template.php(379): __TwigTemplate_9c5b52d57cb4e72165c7e5519403f6543a37fbe9c0dc176b9a8da50a407b3945->doDisplay(Array, Array)
#29 /home/runcloud/webapps/site-name/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#30 /home/runcloud/webapps/site-name/vendor/twig/twig/src/Template.php(356): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#31 /home/runcloud/webapps/site-name/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#32 /home/runcloud/webapps/site-name/storage/runtime/compiled_templates/89/89776d316185108e7cca8c7510b212a9dcd20f93444e272b192576e598ae24f7.php(243): craft\web\twig\Template->display(Array)
#33 /home/runcloud/webapps/site-name/vendor/twig/twig/src/Template.php(379): __TwigTemplate_067a4600c6d0e67de22199e64c3b0b4728ef011ff1e28c28317c3928d3df0666->doDisplay(Array, Array)
#34 /home/runcloud/webapps/site-name/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#35 /home/runcloud/webapps/site-name/vendor/twig/twig/src/Template.php(356): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#36 /home/runcloud/webapps/site-name/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#37 /home/runcloud/webapps/site-name/storage/runtime/compiled_templates/88/8872173e2b62d917e12d6e67a6447195968b747c22ce7d0e61a1b42c8d58b88a.php(35): craft\web\twig\Template->display(Array)
#38 /home/runcloud/webapps/site-name/vendor/twig/twig/src/Template.php(379): __TwigTemplate_52f70f013675c29febd2f6d6e776ed15eada1b968b66ecde48308c4b73106ad7->doDisplay(Array, Array)
#39 /home/runcloud/webapps/site-name/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#40 /home/runcloud/webapps/site-name/vendor/twig/twig/src/Template.php(356): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#41 /home/runcloud/webapps/site-name/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#42 /home/runcloud/webapps/site-name/storage/runtime/compiled_templates/da/daeaf40ad6ae0b7b5fecc35b6b1e2b1aa7f069695455c292349bf5e53a9acbe4.php(50): craft\web\twig\Template->display(Array)
#43 /home/runcloud/webapps/site-name/vendor/twig/twig/src/Template.php(184): __TwigTemplate_df028ad7fddf61dbb4ff2980eb20510144f09323957e6efb4e2b6116d45ba3d0->block_content(Array, Array)
#44 /home/runcloud/webapps/site-name/storage/runtime/compiled_templates/b7/b72887d6e60aed6ad3cef5da302e1eda45fd7bf743280a714411f16772c4f953.php(87): Twig\Template->displayBlock('content', Array, Array)
#45 /home/runcloud/webapps/site-name/vendor/twig/twig/src/Template.php(379): __TwigTemplate_8a6f1118fe7242acf88807fdad0598abd94f70fdfec54a5b9c9289978cc7d133->doDisplay(Array, Array)
#46 /home/runcloud/webapps/site-name/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#47 /home/runcloud/webapps/site-name/vendor/twig/twig/src/Template.php(356): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#48 /home/runcloud/webapps/site-name/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#49 /home/runcloud/webapps/site-name/storage/runtime/compiled_templates/da/daeaf40ad6ae0b7b5fecc35b6b1e2b1aa7f069695455c292349bf5e53a9acbe4.php(40): craft\web\twig\Template->display(Array, Array)
#50 /home/runcloud/webapps/site-name/vendor/twig/twig/src/Template.php(379): __TwigTemplate_df028ad7fddf61dbb4ff2980eb20510144f09323957e6efb4e2b6116d45ba3d0->doDisplay(Array, Array)
#51 /home/runcloud/webapps/site-name/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#52 /home/runcloud/webapps/site-name/vendor/twig/twig/src/Template.php(356): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#53 /home/runcloud/webapps/site-name/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#54 /home/runcloud/webapps/site-name/vendor/twig/twig/src/Template.php(364): craft\web\twig\Template->display(Array)
#55 /home/runcloud/webapps/site-name/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#56 /home/runcloud/webapps/site-name/vendor/twig/twig/src/Environment.php(319): Twig\TemplateWrapper->render(Array)
#57 /home/runcloud/webapps/site-name/vendor/craftcms/cms/src/web/View.php(343): Twig\Environment->render('views/pages/_en...', Array)
#58 /home/runcloud/webapps/site-name/vendor/craftcms/cms/src/web/View.php(393): craft\web\View->renderTemplate('views/pages/_en...', Array)
#59 /home/runcloud/webapps/site-name/vendor/craftcms/cms/src/web/Controller.php(161): craft\web\View->renderPageTemplate('views/pages/_en...', Array)
#60 /home/runcloud/webapps/site-name/vendor/craftcms/cms/src/controllers/TemplatesController.php(78): craft\web\Controller->renderTemplate('views/pages/_en...', Array)
#61 [internal function]: craft\controllers\TemplatesController->actionRender('views/pages/_en...', Array)
#62 /home/runcloud/webapps/site-name/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#63 /home/runcloud/webapps/site-name/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#64 /home/runcloud/webapps/site-name/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('render', Array)
#65 /home/runcloud/webapps/site-name/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#66 /home/runcloud/webapps/site-name/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('templates/rende...', Array)
#67 /home/runcloud/webapps/site-name/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#68 /home/runcloud/webapps/site-name/vendor/craftcms/cms/src/web/Application.php(286): yii\web\Application->handleRequest(Object(craft\web\Request))
#69 /home/runcloud/webapps/site-name/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#70 /home/runcloud/webapps/site-name/web/index.php(42): yii\base\Application->run()
#71 {main}`

**Comment by BenParizek** [comment]
Thanks for the details @riusi88. We'll look into this and let you know what we find.

**Comment by MarcelWeidum** [comment]
When will the update be pushed?

**Comment by MarcelWeidum** [comment]
@BenParizek in `sprout-forms/src/fields/formfields/Address.php` you are using `Template::raw()` instead of your `TemplateHelper`.

On line `122` and `123` change `Template::raw()` to `TemplateHelper::raw()`

**Comment by BenParizek** [comment]
@MarcelWeidum We'll have a release out to fix this shortly.

**Comment by BenParizek** [comment]
@riusi88 @MarcelWeidum This has been resolved in the latest release (v3.0.0-beta.50)
