### ISSUE TITLE
Unknown method for Sprout Forms Notifications

### ISSUE THREAD

**Issue by riladant** [barrelstrength/craft-sprout-forms#267]
### Description
Visiting the notifications section in the CP returns an unknown method error
```
Calling unknown method: barrelstrength\sproutbase\services\Settings::getSharedPermissions()
```

The notifications page worked fine and I was able to create a notification until I assigned some permissions to a user group. 

Even accessing the page as an admin, I still get the error.

### Steps to reproduce

1. Install sprout forms
2. add form & notification
3. assign form entry view only permission to another user group
4. try to view the notifications page

### Additional info

- Craft version: Craft Pro 3.1.19
- PHP version: 7.1.26
- Database driver & version: MySQL 5.5.5
- Plugins & versions:

Name | Version
-- | --
Contact Form | 2.2.3
Contact Form Extensions | 1.1.1
Contact Form Templates | 1.0.1
Imager | v2.1.7
Redactor | 2.3.2
Spoon | 3.3.5
Sprout Forms | 3.0.0-beta.49

**Comment by BenParizek** [comment]
@riladant I haven't been able to recreate this yet but we just pushed a release that may fix the issue. Can you update to 3.0.0-beta.50 and let me know if the issue still happens for you? If it does, can you provide a longer stack trace of the error you are seeing?

**Comment by riladant** [comment]
That latest update appears to have fixed the issue.
