### ISSUE TITLE
Unable to locate message source for category 'sprout-forms' for OptIn field

### ISSUE THREAD

**Issue by missmatsuko** [barrelstrength/craft-sprout-forms#268]
### Description
I'm trying to update from 3.0.0-beta.43 to v3.0.0-beta.50 and I get this error when trying to access the Craft CMS dashboard:
```
Unable to locate message source for category 'sprout-forms'.
```

My form templates don't use 'sprout-forms' as the category for translation filters.
One of my forms does use the opt-in field.

I narrowed down the source of the error to the 'Yes' and 'No' strings in OptIn.php [here](https://github.com/barrelstrength/craft-sprout-forms/blob/c4ff0161dae7eda53bd56622edf8a965c6ec0f06/src/fields/formfields/OptIn.php#L52). When I change these values to hard-coded strings, the dashboard loads fine.

I tried to delete the opt-in field from my form after this to see if the error persists, but I got an error saying the field could not be deleted.

### Steps to reproduce
Not too sure, probably use an opt-in form on v3.0.0-beta.50? 
Maybe the error doesn't exist for newly made ones, though.

### Additional info

- Craft version: 3.1.22
- PHP version: 
- Database driver & version:
- Plugins & versions: v3.0.0-beta.50

**Comment by BenParizek** [comment]
@missmatsuko Thanks for the detailed ticket, however, I haven't been able to reproduce this in my tests. Is there any chance you have more detailed logs to share? Do you have any custom widgets or anything on the Dashboard?

From what you're pointing at, I would guess it has something to do with the translation tags being used in the init method. We could potentially look into refactoring that, but I haven't been able to create a scenario where I can get this to happen yet either.

**Comment by missmatsuko** [comment]
I'll try to look into a bit more. I was thinking it might have something to do with the Yes/No entries not existing in the database for the OptIn field since it was created before those were options? I'm not sure where to look for that in the database, though. I was just thinking I might try deleting the OptIn field and then upgrading.

**Comment by jaydensmith** [comment]
I have the same issue.

**Comment by BenParizek** [comment]
@missmatsuko @jaydensmith I trust you folks are running into an issue here but I haven't yet been able to recreate it, even when trying to simulate the upgrade path with the specific version numbers referenced above. Would either of you be available to ping me on Craft Discord (BenParizek) or drop a note to support@barrelstrengthdesign.com so we could coordinate and troubleshoot on a screenshare?

**Comment by BenParizek** [comment]
@jaydensmith I was able to connect with Matsuko on this and it appears the issue may stem from a migration that got missed somewhere. We'll work on a fix but in the meantime if you'd like to fix this manually in the db you can go to the `craft_fields` table. Look for all fields that have the `type` column set to `barrelstrength\sproutforms\fields\formfields\OptIn`

And then update the settings value for that field to include `optInValueWhenTrue` and optInValueWhenFalse` values. You can just set them to an empty string and that should probably get things working again:

```{"cssClasses":"","optInMessage":"","selectedByDefault":"","optInValueWhenTrue":"","optInValueWhenFalse":""}```

**Comment by BenParizek** [comment]
@missmatsuko @jaydensmith The latest release of Sprout Forms (v3.0.0-beta.52) fixes this issue.
