### ISSUE TITLE
Craft 2 to Craft 3.1 form groups are not migrated correctly

### ISSUE THREAD

**Issue by jamesmacwhite** [barrelstrength/craft-sprout-forms#274]
### Description

From testing a Craft 2 project with existing form groups, the groups are not correctly setup in Craft 3.

Existing Craft 2 form groups with forms:

![image](https://user-images.githubusercontent.com/8067792/56734975-2c560d80-675c-11e9-9f3e-a121480a85e1.png)

Craft 3 form groups and forms after migration:

![image](https://user-images.githubusercontent.com/8067792/56735087-68896e00-675c-11e9-99f9-c2840e13abc0.png)

It looks like first group is missing entirely and because of that causes everything else to be out of sequence, it also looks like the ordering is not maintained either. Looking at the `sproutforms_formgroups` table, the missing group does still exist as a row in the database, but it is not visible and cannot be found in the entries menu under Craft 3.

### Steps to reproduce

1. Setup form groups with forms attached in a Craft 2 project
2. Migrate the Craft 2 project to Craft 3
3. Observe the form groups being out of sequence compared to Craft 2.

### Additional info

- Craft version: 3.1.24
- PHP version: 7.1
- Database driver & version: MySQL 5.6
- Plugins & versions: Sprout Forms v3.0.0-beta.52 

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_j8aj)

**Comment by jamesmacwhite** [comment]
In addition. Adding new a entry source heading in `/sprout-forms/entries`, a flash message appears after saving, saying the change has been made but the created heading does not show up and isn't present.

**Comment by BenParizek** [comment]
@jamesmacwhite Can you confirm that you upgraded to the latest version of Sprout Forms on Craft 2 before upgrading to Craft 3?

If possible, would you be able to send over your database or at least the `sproutforms_` tables in your database to sprout@barrelstrengthdesign.com?

**Comment by jamesmacwhite** [comment]
@BenParizek I can confirm the Craft 2 DB is from a site which is running the latest Craft 2 plugin version.

I'll certainly aim to provide that to you. Would you like just the Craft 3 DB tables or the Craft 2 DB prior to a migration as well?

I don't get an errors from what I can see but the entry sources on the form page seems to not be working properly though.

**Comment by BenParizek** [comment]
@jamesmacwhite If you can provide both dbs we'd be happy to take a look at both.

**Comment by jamesmacwhite** [comment]
@BenParizek Thanks. I've provided both to sprout@barrelstrengthdesign.com. Let me know if there's anything else I can help with.

**Comment by BenParizek** [comment]
@jamesmacwhite We've taken a look at this and believe the issue may be a combination of things happening in Craft.

Regarding the heading not displaying after you hit save, this is just how the sidebar customization feature works in Craft. You should be able to recreate and see the same behavior in any other Element Listing if you had a header with no sub-items. In order to have a header display, it will need to have items listed under it.

Regarding the migration, Sprout Forms does not do anything specific when migrating regarding the Entries sidebar. That data is stored in a separate Craft table and managed by Craft. It looks like it stores a reference to the Sprout Forms IDs in deciding how to organize things but it's not clear to us yet where that data may be changing in the migration process. We don't change the IDs in the migration process.

I believe there is no issue of data changing here aside from how the sidebar UI is handled. The quickest resolution will be to just update the sidebar to how you'd like to have it display again. Let me know if that can work for you for now.

**Comment by BenParizek** [comment]
@jamesmacwhite We're still not sure what happened here but the best path to resolution is mentioned above – just updating your sidebar in the new UI.

If new information comes to light on what may be going on here, we'll reopen.

**Comment by jamesmacwhite** [comment]
Sorry for my lack of response on this, I can confirm it still happens when going from Craft 2 -> 3, however based on your explanation it sounds like this is touching on core Craft CMS rather than anything being done by Sprout in it's migration track?

The easiest solution is to re-do the sidebar in Craft 3, but the issue is the project this is related to is still a live Craft 2 site and is changing in terms of it's live DB, so the Craft 3 version has it's DB refreshed a lot, so rebuilding the menu isn't really any option as it will just be lost on the next DB migration test, I have tended to do content migrations where things are repeatable but messing around with element index layouts in a content migration will be painful, but I have done it before.

I may have to dig into this a bit more and figure out what is causing them to be messed up in the first place.

**Comment by jamesmacwhite** [comment]
@BenParizek So looking into this a bit more. The forms themselves are assigned to the right groups as you said. It does appear to be an element index setting related problem.

![image](https://user-images.githubusercontent.com/8067792/108871384-0405f700-75f1-11eb-985a-81e2ec44556c.png)

From migration a Craft 2 site with Sprout Forms and also Sprout Email, we can see the type value is the old Craft 2 type, not Craft 3. I tested re-saving the element index settings within Sprout Forms > Entries and noticed a element index was created:

![image](https://user-images.githubusercontent.com/8067792/108871691-4d564680-75f1-11eb-8001-a505a5e138be.png)

At this point, perhaps the easiest thing to do for me would be to save the element index settings as JSON and import into the DB to fix the problem. It would seem by default no element index data exists after migrating from Craft 2.
