### ISSUE TITLE
Reports bug

### ISSUE THREAD

**Issue by SamLNL** [barrelstrength/craft-sprout-forms#281]
### Description
Whenever I try to run a report, a couple entries will be shown. Unfortunately not all the entries.
I was wondering myself how this could be, so I tried some debugging.

I noticed that the function in the `EntriesDataSource.php` wasn't working properly. The query thats is used to retrieve all of my form entries, contains a bug.

`$formQuery = $query
                ->select('*')  
                ->from($contentTable.' AS entries')  
                ->innerJoin('{{%elements}}', '[[entries.id]] = [[elements.id]]')  
                ->where(['elements.dateDeleted' => null]);`  

The innerJoin is used for comparing the `entries.id` with the `elements.id`. This `entries.id` should be `entries.elementId`. Whenever I run that query I receive the right amount of form entries.

### Steps to reproduce

1. Save some form entries
2. Check if the form entries contain a id that isn't present as a element.id
3. Run Sprout reports
4. Check for the entry that is missing

### Additional info

- Craft version: 3.1.27
- PHP version: 7.0.33
- Database driver & version: MySQL 5.5.52
- Plugins & versions: 3.0.0-beta.56

**Comment by BenParizek** [comment]
@SamLNL Thanks for reporting. We recently fixed this bug in v3.0.0-beta.57.

Please update to the latest version and you should see this resolved.
