### ISSUE TITLE
Error when creating or viewing Notification

### ISSUE THREAD

**Issue by phrichards** [barrelstrength/craft-sprout-forms#285]
### Description

I'm getting this error when I create a new notification. If I go back to the notifications index after getting the error I see it created (as Notification 1, Notification 2, etc) but clicking on one of them to edit it produces the same error. See screenshot below for error details.

### Steps to reproduce

1. Click on the Notifications tab under Sprout Forms in the Craft admin
2. Click "New Notification"
3. Alternatively, click on a notification title to edit it.

### Additional info

![Screen Shot 2019-06-06 at 2 42 19 PM](https://user-images.githubusercontent.com/8181255/59057969-912b7a00-8869-11e9-8230-661987003d65.png)

- Craft version: 3.1.28
- PHP version: 7.1.28
- Database driver & version: MySQL 5.5.5
- Plugins & versions: 3.0.0-beta.57

Thanks!

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_lf9f)

**Comment by BenParizek** [comment]
Thansk for reporting @phrichards. This sounds similar to another report we recently got and that we're looking into. Is this a fresh install of Sprout Forms or an upgrade? If you upgraded, do you know from what version of Craft or Sprout Forms you upgraded?

**Comment by phrichards** [comment]
Hi @BenParizek. It was an upgrade from 3.0.0-beta.45. Sprout was working fine at that version. I'm not sure which exact version of Craft it was at the time, just that it was ^3.0.0. We upgraded to 3.0.0-beta.57 on Craft 3.1.28, and it stopped working at that point.

**Comment by andrelopez** [comment]
H @phrichards Could you please recreate the issue and send back to us a zip file of the next folder: `storage/logs`

Please email us to support@barrelstrengthdesign.com

**Comment by phrichards** [comment]
Hi @andrelopez, I've sent a zip of the logs folder.

**Comment by BenParizek** [comment]
@phrichards This should be resolved in the latest release (Sprout Forms v3.0.0). 

Let us know if you still experience any issues.

**Comment by phrichards** [comment]
@BenParizek this update seems to have fixed the issue. Thanks for taking care of it so quickly!
