### ISSUE TITLE
Sprout Forms fields of type "checkboxes" no longer display usable data in Reports

### ISSUE THREAD

**Issue by bentilden** [barrelstrength/craft-sprout-forms#287]
### Description

When running a report for data source type "Sprout Forms Entries," data for fields with field type "Checkboxes" is displayed in the report as series of "1"s, without indication of what values the user has checked.

### Additional info

- Craft version: 3.1.29
- PHP version: 7.2.15
- Database driver & version: MySQL 5.7.25
- Plugins & versions: Sprout Forms 3.0.0-beta.57, Sprout Reports 1.1.7

**Comment by BenParizek** [comment]
@bentilden This is fixed in the latest release of Sprout Forms (v3.0.0)
