### ISSUE TITLE
Craft DB table prefix causes SQL error

### ISSUE THREAD

**Issue by bentilden** [barrelstrength/craft-sprout-forms#288]
### Description
In file /vendor/barrelstrength/sprout-forms/src/integrations/sproutreports/datasources/EntriesDataSource.php, on lines 74 and 75, the table names in the SQL join statement don't work if you have table prefixes set in the Craft database.

            ->innerJoin('{{%elements}}', '[[formcontenttable.elementId]] = [[elements.id]]')
            ->where(['elements.dateDeleted' => null]);

I was able to fix it temporarily by changing this code to include the prefix we're using, which is "craft_".

            ->innerJoin('{{%elements}}', '[[formcontenttable.elementId]] = [[craft_elements.id]]')
            ->where(['craft_elements.dateDeleted' => null]);

### Additional info

- Craft version: 3.1.29
- PHP version: 7.3.1
- Database driver & version: MySQL 5.7.25
- Plugins & versions: Forms 3.0.1, Reports 1.1.7

**Comment by BenParizek** [comment]
Thanks @bentilden. Looks like an oversight on our end. Will get that fixed up and let you know when we do.

**Comment by andrelopez** [comment]
Hi @bentilden We just released Sprout Forms v3.0.2 with a fix to this issue. Please let us know how it goes.

**Comment by bentilden** [comment]
Yep - that fixed it! Thanks!!
