### ISSUE TITLE
Deleting notification sends you to wrong url

### ISSUE THREAD

**Issue by marionnewlevant** [barrelstrength/craft-sprout-forms#294]
### Description

Created a new notification, and then deleted it with out ever saving it. I got redirected to /notifications (on the front end).

### Steps to reproduce

1. Create a new notification (first one if that matters)
2. From the `Save` dropdown, pick `Delete`

### Additional info

- Craft version: 3.1.30
- PHP version: 7.0.13
- Plugins & versions: Sprout Forms 3.0.0-beta.57 & a bunch of others

**Comment by marionnewlevant** [comment]
Updated to 3.0.2 (Sprout Forms), and this still happens
Also, and unrelated, the Sprout Website link in the repo readme is out of date.

**Comment by BenParizek** [comment]
Thanks @marionnewlevant. We'll get this fixed.

**Comment by BenParizek** [comment]
@marionnewlevant This has been fixed in Sprout Forms v3.2.2

We've also improved/fixed README links and some redirects, so they should get you to the right place now. Thanks for reporting.
