### ISSUE TITLE
Incorrect state list in address field

### ISSUE THREAD

**Issue by jaydensmith** [barrelstrength/craft-sprout-forms#299]
### Description (screenshots, logs, ...)
In the address field, when selecting Australia, there is an option that is not an official Australian state or territory (Jervis Bay Territory).

<img width="361" alt="Screen Shot 2019-06-25 at 10 16 55 pm" src="https://user-images.githubusercontent.com/16344913/60097801-88a6cf00-9797-11e9-8d0d-0f7ff54bca1c.png">

### Steps to reproduce

1. Add an address field.
2. Choose Australia as the Country
3. View the state select field.

### Additional info

- Craft version: 3.2.0-beta.3
- PHP version: 7.0.33
- Database driver & version:  Mysql 5.7.25
- Plugins & versions: Sprout Forms 3.1

_For some issues, we may request that you send the following items to Support <sprout@barrelstrengthdesign.com>. If you feel your issue may fall in that category, feel free to send things over after you post this issue and reference the issue in your email._

- `composer.json`
- `storage/logs/web.log` (or a zip of the whole log folder)
- An export of your database (or, if you can't share the whole db, the specific Sprout tables)

**Comment by BenParizek** [comment]
Hi @jaydensmith

The Address Field uses the [addressing](https://github.com/commerceguys/addressing) library which cites that it uses data _powered by CLDR and Google's address data._ (sourced linked in the README of that repo)

The latest version of their data set does include Jervis Bay Territory:
https://github.com/commerceguys/addressing/blob/master/resources/subdivision/AU.json#L9

We'll continue to rely on that data set so if you have a situation where you don't wish to list that as an option you may need to address it with a custom address field or hide that item from the list via JS or something like that.

Can you share more about the use case where that doesn't work for you? I can't promise that we'll be able to address it as we heavily rely on that data set, but understanding the situation more could help us consider our options.
