### ISSUE TITLE
Can't create new forms on development site.

### ISSUE THREAD

**Issue by jaydensmith** [barrelstrength/craft-sprout-forms#300]
### Description (screenshots, logs, ...)
Since the 3.2.x update, I cannot create new forms in our development environment even while owning a valid license for the pro version. The error I receive is: 'Please upgrade to Sprout Forms Pro Edition to create unlimited forms.'

If it helps, all our testing domains are either .local, .dev or .test depending on how old the sites are.

### Steps to reproduce

1. Create a new form in development environment with a valid pro license

### Additional info

- Craft version: 3.2.0-beta.3
- PHP version: 7.0.33
- Database driver & version:  Mysql 5.7.25
- Plugins & versions: Sprout Forms 3.2.1

_For some issues, we may request that you send the following items to Support <sprout@barrelstrengthdesign.com>. If you feel your issue may fall in that category, feel free to send things over after you post this issue and reference the issue in your email._

- `composer.json`
- `storage/logs/web.log` (or a zip of the whole log folder)
- An export of your database (or, if you can't share the whole db, the specific Sprout tables)

**Comment by BenParizek** [comment]
Hi @jaydensmith. We recently introduced a Lite and Pro edition to Sprout Forms so it seems something is off in your environment that isn't recognizing that you have a Pro edition of the plugin.

I'm currently unable to recreate this in my development environment. Can you provide a bit more info about how you upgraded to the latest (composer/CP)? Do you happen to be using the Project Config `project.yaml`? If so, can you check if your Edition is set to `pro`? It also may be worth clearing cache.

If we can't resolve this we can pull in Craft support to help us diagnose what is going on.

**Comment by jaydensmith** [comment]
Hey @BenParizek, I had to manually go into the project config and add the `edition` key.

**Comment by BenParizek** [comment]
Thanks for the update @jaydensmith. I'll consider this issue resolved for now but we'll keep our eyes out for additional odd behavior like this.
