### ISSUE TITLE
PHP Compile Error yii\base\ErrorException with message A function with return type must return a value

### ISSUE THREAD

**Issue by engram-design** [barrelstrength/craft-sprout-forms#308]
Getting an error when trying to migrate to the latest Sprout Forms

```
Status: Internal Server Error

Response: <pre>PHP Compile Error &#039;yii\base\ErrorException&#039; with message &#039;A function with return type must return a value&#039;

in /Users/craft/vendor/barrelstrength/sprout-forms/src/migrations/m190628_000000_update_default_to_pro_edition.php:24

Stack trace:
#0 [internal function]: yii\base\ErrorHandler-&gt;handleFatalError()
#1 {main}</pre>
```

https://github.com/barrelstrength/craft-sprout-forms/blob/v3/src/migrations/m190628_000000_update_default_to_pro_edition.php#L24 seems to be missing a return boolean.

I blame @brandonkelly and [his commit](https://github.com/barrelstrength/craft-sprout-forms/commit/f22e05f6774df916a56c8208efee24cf95543cab) 😎

**Comment by brandonkelly** [comment]
Doh! @BenParizek I had missed the `: bool` for that function.

**Comment by BenParizek** [comment]
Thanks @engram-design. Fixed in the latest.

I take the responsibility. He who merges... I had, in fact, just fixed the issue as we ported that migration to another plugin, and overlooked fixing it here too.
