### ISSUE TITLE
Tabs overflow not scrolling in form entry view. 

### ISSUE THREAD

**Issue by Gnative** [barrelstrength/craft-sprout-forms#309]
### Description (screenshots, logs, ...)

Tabs are not scrolling in a forms entry view like they do for 'editing' a form. 

If i'm honest i think the scrolling way to handle multiple tabs is not particularly friendly.  Would be more readable, easier to use and in style with 'Craft' if there was an accordion style UI similar to how Matrix blocks collapse and expand.

Thanks for the great plugin otherwise.

<img width="1447" alt="Screenshot 2019-07-04 at 16 32 07" src="https://user-images.githubusercontent.com/1758875/60674209-e9aa6300-9e79-11e9-8352-bad2c10778dc.png">

### Steps to reproduce

1. Create a form and add multiple tabs with longer titles so there is an overflow.
2. Submit an entry to this form.

### Additional info

- Craft version: 3.1.33
- PHP version: 7.3.5
- Database driver & version:  MySQL 5.7.25
- Plugins & versions: Spout Form 3.3.0 Pro Trial

**Comment by BenParizek** [comment]
Thanks for reporting @Gnative.

Looks like Brandon says in this thread that they may implement a dropdown option for this. Perhaps consider adding your vote there too: https://github.com/craftcms/cms/issues/3073

I think it'd be a good direction. We'll probably solve this bug in the same way we solve it on the Form edit page for now, as it's less code for us to maintain that deviates from Craft, but once Craft implements the dropdown we will plan to switch over to that to stay consistent with the Craft UI.

I'll update you here once we get a fix in place for this.

**Comment by Gnative** [comment]
Thanks @BenParizek , didn't realise this was the "Craft" way, your solution is tidy for the problem.
Vote added, See how that pans out with Craft.

**Comment by BenParizek** [comment]
@Gnative We just released v3.3.3 which addresses this issue.
