### ISSUE TITLE
Users cannot edit fields due to permissions

### ISSUE THREAD

**Issue by ccchapman** [barrelstrength/craft-sprout-forms#310]
### Description

A user with the "Edit forms" permission is expected to be able to edit a field in a form.

### Steps to reproduce

1. Login as a user that has the "Edit forms" permission but not the "Edit form entries" permission
2. Navigate to an individual form
3. Hover over any field and click the pencil icon
4. The front-end displays a "An unknown error occurred." message while the `/index.php?p=admin/actions/sprout-forms/fields/edit-field` request returns a 403 `{"error":"User is not permitted to perform this action"}`

### Additional info

- Sprout Forms version: 3.3.0
- Craft version: 3.1.33
- PHP version: 7.2

**Comment by BenParizek** [comment]
Thanks for reporting @ccchapman, we'll let you know when we have a fix out.

**Comment by BenParizek** [comment]
@ccchapman We just released v3.3.3 which addresses this issue.
