### ISSUE TITLE
Can't add fields to a new form

### ISSUE THREAD

**Issue by darylknight** [barrelstrength/craft-sprout-forms#311]
### Description (screenshots, logs, ...)
I just installed Sprout Forms (free version) to replace Freeform on an existing client site, and I can't add any fields to the new form.

### Steps to reproduce

1. Install Sprout Forms Free
2. Create a new form
3. Try to drag fields from the sidebar on to the form. Nothing happens

### Additional info

- Craft version: 3.2.0
- PHP version: 7.3
- Database driver & version: MySQL
- Plugins & versions: Sprout Forms 3.3.2

**Comment by BenParizek** [comment]
@darylknight Do you see any errors in the console or on the Network tab?

**Comment by darylknight** [comment]
No, there are no console errors - it's like I'm just trying to drag it onto part of the page that just isn't interactable. I also tested this on a fresh install, on both 3.1.x and 3.2 and got the same results with no other plugins.

**Comment by andrelopez** [comment]
Hi @darylknight 

We're unable to recreate this issue, we may need more info to start debugging. 

- Could you please confirm us from what browsers have you tested?
- Are you testing as admin?

**Comment by darylknight** [comment]
Sorry team, looks like I can't replicate this today. Goodness knows what caused it but it seems to be fine on the plain Craft site I have for testing after deleting vendor, composer.lock and the database then starting from scratch. Will let you know if it crops up again.

**Comment by BenParizek** [comment]
Thanks for the update @darylknight
