### ISSUE TITLE
sprout-forms/notifications broken

### ISSUE THREAD

**Issue by darylknight** [barrelstrength/craft-sprout-forms#316]
### Description (screenshots, logs, ...)

I just tried to visit clientsite.test/admin/sprout-forms/notifications and got an invalid route error:
![image](https://user-images.githubusercontent.com/1250017/61369181-3ccbdf00-a898-11e9-8aaa-42ff4b21620b.png)

It works on my vanilla Craft install, so I'm wondering if a migration has gone wrong somewhere? Any idea where to fix this?

### Additional info

- Craft version: 3.1.34
- PHP version: 7.3
- Database driver & version:  MySQL
- Plugins & versions: Sprout forms 3.3.0

_For some issues, we may request that you send the following items to Support <sprout@barrelstrengthdesign.com>. If you feel your issue may fall in that category, feel free to send things over after you post this issue and reference the issue in your email._

- `composer.json`
- `storage/logs/web.log` (or a zip of the whole log folder)
- An export of your database (or, if you can't share the whole db, the specific Sprout tables)

**Comment by andrelopez** [comment]
Hi @darylknight 

Could you please update Sprout Forms to v3.3.5 and let us know if that fixes this issue?

**Comment by darylknight** [comment]
Yep, that fixes it. Thanks Andre - for some reason, nothing past 3.3.3 was showing up in my Utilities menu, but `composer update` has patched it and it works now.

**Comment by darylknight** [comment]
FYI, there's still nothing showing up in my Updates section for anything past Sprout Forms 3.3.0 on other sites

**Comment by jmcgaha** [comment]
I am currently on Craft 3.1 for some specific plugin reasons and am running into this issue because I can only go to Forms 3.3.0 since anything above that requires Craft 3.2.
Is there any way to get a release that fixes this for Craft 3.1?

I also tried downgrading Sprout to 3.0 which I think was the latest release without this issue but that just breaks everything.

**Comment by BenParizek** [comment]
@jmcgaha I'll try to take a look this coming week and see what our options are.

**Comment by jmcgaha** [comment]
I finally tracked it down, looks like I had run composer update and it also updated sprout-base-email to a newer version.

I went back to the 3.3.0 release and saw what version of sprout-base-email was installed then and locked it in on my composer file. That seemed to fix everything.

Here is what I added to composer:
`"barrelstrength/sprout-base-email": "1.1.1",`

**Comment by BenParizek** [comment]
Good catch @jmcgaha.

Thanks for sharing the solution.
