### ISSUE TITLE
Cannot enable plugin

### ISSUE THREAD

**Issue by kculmback** [barrelstrength/craft-sprout-forms#322]
### Description (screenshots, logs, ...)
When attempting to enable plugin I get an error `No plugin exists with the handle "sprout-forms".` This happens when I try to install the plugin via composer as well as when I try to install via the plugin store.

I was able to successfully install sprout-reports.

### Steps to reproduce

1. Run `craft require barrelstrength/sprout-forms`
2. Go to Admin -> Settings -> Plugins -> Install Sprout Forms
3. Get error page

### Additional info

- Craft version: 3.1.30
- PHP version: 7.3

**Comment by andrelopez** [comment]
Hi @kculmback 

Could you please install the last version available for Craft 3.1.x?

`composer require barrelstrength/sprout-forms:3.3.0`

Please let us know if that works

**Comment by kculmback** [comment]
Apologies @andrelopez, I was able to figure this out late last night. Trick was to run the following command:

`./craft project-config/rebuild`

Something must have went wrong when I first tried to install it. After running the command I was able to successfully enable the plugin.

**Comment by andrelopez** [comment]
Thanks for the update @kculmback
