### ISSUE TITLE
`Save data` option appearing on forms

### ISSUE THREAD

**Issue by engram-design** [barrelstrength/craft-sprout-forms#323]
A new setting has appeared on our forms - "Save data" which is actually false. We always want to save all form data to the database, as has been the case for a long time with Sprout Forms.

There's a config setting that enables this globally, but also "Enable Save Data settings on a per-form basis". I would've thought that disabling this option wouldn't even show this as a switch on each form?

I'm not really sure if data is being saved for forms (and maybe just a visual thing), but I'd rather it to be there at all to save confusion. This seems to be a recent change in Sprout Forms.

See attached screenshots of settings.

<img width="352" alt="Screen Shot 2019-07-29 at 9 51 13 pm" src="https://user-images.githubusercontent.com/1221575/62046497-66e3b080-b24b-11e9-83b0-bbfa9778d030.png">
<img width="659" alt="Screen Shot 2019-07-29 at 9 51 05 pm" src="https://user-images.githubusercontent.com/1221575/62046498-677c4700-b24b-11e9-957b-ec862dd813b2.png">

**Comment by BenParizek** [comment]
@engram-design We're looking into this. That setting should not be displaying or affecting anything if your global settings are set the way your screenshot shows. Will update this thread when we get things corrected.

**Comment by engram-design** [comment]
No problem, and not urgent if working as expected, just saw this field with the 'wrong' state and was concerned!

**Comment by BenParizek** [comment]
@engram-design This is resolved in the latest release v3.4.0
