### ISSUE TITLE
php 7.2 count() error

### ISSUE THREAD

**Issue by pieter-janDB** [barrelstrength/craft-sprout-forms#329]
Hi,

Using Craft 2.7.10 and sproutforms 2.6.0 and php 7.2.

Since I am using php 7.2 (now supported in craft 2.7.10) I can no longer save new forms.

Getting error:

> count(): Parameter must be an array or an object that implements Countable

In formController line 75 
`if (count($deletedFields) > 0)`
needs to be replaced with
`if (!is_null($deletedFields) && count($deletedFields) > 0)`
since $deletedFields == null when there are none..

**Comment by BenParizek** [comment]
@pieter-janDB The releases feed may not indicate there are more recent versions of Sprout Forms but it looks like you are not on the latest. Can you upgrade to v2.6.4 and let me know if that resolves things? I think that may have been addressed in v2.6.2.

https://github.com/barrelstrength/craft-sprout-forms/releases/tag/v2.6.4

**Comment by pieter-janDB** [comment]
Updated to 2.6.4 but problem persists. 
I have had same errors in Sprout emails 3.1.0 where you use count but don't check for null.

**Comment by BenParizek** [comment]
@pieter-janDB 2.6.4 is checking for an array before executing the code above, so I believe it would not be throwing the same error: https://github.com/barrelstrength/craft-sprout-forms/blob/v2/controllers/SproutForms_FormsController.php#L81

Upgrading to Sprout Email v3.1.4 should fix some similar issues and I'll need more info.

I'm considering these solved for now but please re-open with more details if we still need to track something down.
