### ISSUE TITLE
CSS classes added to fields in CP not showing

### ISSUE THREAD

**Issue by TomDeSmet** [barrelstrength/craft-sprout-forms#335]
### Description (screenshots, logs, ...)
When adding CSS classes to the field from within the CP, they don't show up in the code.

When we add this code to the `field.twig` template (when overriding it with a custom one) it works:
`{%- if field.cssClasses %} {{ field.cssClasses }}{% endif -%}`

### Additional info

- Craft version: 3.2.10
- PHP version: 7.2
- Database driver & version:  MySQL
- Plugins & versions: 3.4.1 (Free and Pro)

**Comment by TomDeSmet** [comment]
I'm using the Basic templates idd, sorry I forgot to mention that.

Using the Accessible templates together with Webpack gives some other errors unfortunately. I'll put up a separate bug request for that soon.

**Comment by BenParizek** [comment]
@TomDeSmet This has been addressed in the latest release.
