### ISSUE TITLE
Unable to save entry with a sprout forms field when "validate related elements" is checked

### ISSUE THREAD

**Issue by jowhannez** [barrelstrength/craft-sprout-forms#349]
### Description (screenshots, logs, ...)

https://i.ibb.co/CWhKh3V/error.png

Unable to save entry with a sprout forms field when "validate related elements" is checked in the fields settings.

### Steps to reproduce

1. Create a "Forms (Sprout Forms)" field
2. Check "validate related elements"
3. Make a form
3. Add field to an entry
4. Go to entry and select the form
5. Try to save entry

### Additional info

- Craft version: Craft Pro 3.3.4.1
- PHP version: 7.1.26
- Database driver & version: MySQL 5.5.5

**Comment by BenParizek** [comment]
Thanks for reporting @jowhannez. Added to our list and we'll let you know when we have an update.

**Comment by andrelopez** [comment]
Hi @jowhannez We're unable to recreate this issue could you please confirm us your Sprout Forms version?

**Comment by BenParizek** [comment]
We are still unable to recreate this. Please re-open if the issue persists and we'll need to get more information about how to recreate. Following the steps above seems to work in our tests, so perhaps something else is at play.
