### ISSUE TITLE
“A form submission failed the Duplicate Submission test.“

### ISSUE THREAD

**Issue by klick** [barrelstrength/craft-sprout-forms#350]
Form fails to submit with `A form submission failed the Duplicate Submission test.` and `OnBeforeSaveEntryEvent is not valid` although form contents are unique. Immediately submitting it a second time works.

### Steps to reproduce

1. Fill out form
2. Press submit
3. Page just reloads with form pre-filled

### Additional info

- Craft version: 3.3.9
- PHP version: 7.2
- Database driver & version:  Mysql 5
- Plugins & versions: Sprout Forms 3.5.0

**Comment by BenParizek** [comment]
@klick I can recreate this. 

You can update and disable the Duplicate Spam check in `Settings->Spam Protection` area if that helps get around this issue in the short term.

I'll update this thread once we have a solution.

**Comment by klick** [comment]
Thanks Ben, that does it for now.

**Comment by BenParizek** [comment]
@klick In a second round of testing, I'm no longer able to recreate this. 

If this persists for you, can you share what Form Templates you are using and, if possible, share the code of your form.twig template if you are overriding the default templates?

**Comment by klick** [comment]
Hi Ben. Thanks for getting back. 

That behavior now disappeared here as well instead another issue appeared: Forms aren’t being submitted when the Javascript-Option on the Spam protection settings page is active. It just redirects to the thank you-page.

The form in question: https://www.temedos.de/buchen-sie-ihren-persoenlichen-gesundheitscheck?utm_source=check-modul&utm_medium=check-modul&utm_campaign=Kurz-Check&active_price_form_entry=1

The logs say: 

```
2019-10-15 15:40:53 [-][2862][-][error][barrelstrength\sproutforms\captchas\JavascriptCaptcha::verifySubmission] A form submission failed because the user did not have Javascript enabled.
2019-10-15 15:40:53 [-][2862][-][error][barrelstrength\sproutforms\services\Entries::saveEntry] OnBeforeSaveEntryEvent is not valid
2019-10-15 15:40:53 [-][2862][-][error][barrelstrength\sproutforms\controllers\EntriesController::redirectWithErrors] []
2019-10-15 15:40:53 [-][2862][-][info][application] $_GET = [
    'p' => 'buchen-sie-ihren-persoenlichen-gesundheitscheck'
    'utm_source' => 'check-modul'
    'utm_medium' => 'check-modul'
    'utm_campaign' => 'Kurz-Check'
    'active_price_form_entry' => '1'
]
```

Note that all of these appeared after updating Craft to Version 3 from 2. I am not using any form templates, I have just put the fields manually in the template.

Best
Marcus

**Comment by andrelopez** [comment]
Hi @klick 

Could you please share the code of how are you displaying manually the fields in the form? In Craft3 is required to have the following line (required for spam workflow) inside your `<form>` tag:

`{% hook 'sproutForms.modifyForm' %}`

Best,

**Comment by klick** [comment]
Hi @andrelopez.

> In Craft3 is required to have the following line (required for spam workflow) inside your <form> tag {% hook 'sproutForms.modifyForm' %}

That I did not know and it seems to resolve the issues. RTFM I guess. ^^

Thank you!
