### ISSUE TITLE
Updating to 3.5.0 looses Default Form Templates setting

### ISSUE THREAD

**Issue by engram-design** [barrelstrength/craft-sprout-forms#351]
Updating from 3.4.3 => 3.5.0 resets the "Default Form Templates" setting back to Accessible Templates. We were using custom templates, and occurred on two sites now.

**Comment by engram-design** [comment]
This is because the setting variable was changed. This field was called `templateFolderOverride` and is now called `formTemplateDefaultValue`, but there is no migration of this setting.

**Comment by BenParizek** [comment]
Thanks for reporting @engram-design. We'll update this thread once we release a fix.

**Comment by BenParizek** [comment]
@engram-design This should be solved in the latest release v3.5.1
