### ISSUE TITLE
Entry not saving after hooking after save event.

### ISSUE THREAD

**Issue by welford-media-ops** [barrelstrength/craft-sprout-forms#352]
We are using Sprout forms in order to capture details prior to redirecting users off site to a payment gateway.

Hooking into the EVENT_AFTER_SAVE and performing the redirect with "$this->redirect($redirect);" the form entry is never saved, I assume because of the redirect off site. This suggests that this event is not actually called "After Save".

### Steps to reproduce

1. Create a form
2. Hook into the EVENT_AFTER_SAVE and perform a redirect offsite

### Additional info

- Craft version: Craft Pro 3.2.9
- PHP version: 7.2.23
- Database driver & version:  MySQL 10.3.18 (MariaDB)
- Plugins & versions: Sprout Forms 3.3.9

**Comment by BenParizek** [comment]
@welford-media-ops 

There are two "after save" events and, in both cases, Sprout Forms is extending Craft's Element class behavior for those events. 

The Element's [EVENT_AFTER_SAVE](https://github.com/craftcms/cms/blob/3.3.9/src/services/Elements.php#L1975) happens within the save transaction and should use this class as it's trigger:
`barrelstrength\sproutforms\elements\Entry::EVENT_AFTER_SAVE`

The Element Service's [EVENT_AFTER_SAVE_ELEMENT](https://github.com/craftcms/cms/blob/3.3.9/src/services/Elements.php#L2037) happens after the transaction is complete:
craft\services\Elements::EVENT_AFTER_SAVE_ELEMENT

There is a third scenario if you are not saving data to the Craft database where we call the `EVENT_AFTER_SAVE` event manually in the EntriesController, but, as you are trying to save data to the database I don't think this one would apply here.

I believe updating your event to use the Element Service's `EVENT_AFTER_SAVE_ELEMENT` Event will resolve the unwanted behavior.
