### ISSUE TITLE
Notification test can say it was successfull when it actually failed

### ISSUE THREAD

**Issue by OscarBarrett** [barrelstrength/craft-sprout-forms#353]
### Description (screenshots, logs, ...)
This may be specifically related to using SES or a similar email service that can respond with 554.

<img width="451" alt="image" src="https://user-images.githubusercontent.com/3511332/67350157-88b7af80-f57c-11e9-9d05-d6f3bfeb5ed2.png">
<img src="https://user-images.githubusercontent.com/3511332/67350227-c1f01f80-f57c-11e9-8dc7-c4e0d319b3d6.png">

### Steps to reproduce

1. Configure Craft to send emails via SES with valid credentials
2. Create a notification with a from address that is not verified
3. Trigger the notification test

### Additional info

- Craft version: 3.3.4.1
- PHP version: 7.3.9
- Database driver & version:  MySQL 5.7.21
- Plugins & versions: Sprout Forms 3.5.1

_For some issues, we may request that you send the following items to Support <sprout@barrelstrengthdesign.com>. If you feel your issue may fall in that category, feel free to send things over after you post this issue and reference the issue in your email._

- `composer.json`
- `storage/logs/web.log` (or a zip of the whole log folder)
- An export of your database (or, if you can't share the whole db, the specific Sprout tables)

**Comment by BenParizek** [comment]
@OscarBarrett Can you confirm where you are seeing that error message?

In general, when we say an email has been successfully sent from Craft we can only know that it has been successfully handed off to the service defined in the email settings. It is possible additional deliverability issues occur at that next layer. 

We can look into correcting the message there if that's a Craft/Yii error message.

**Comment by OscarBarrett** [comment]
The warning is in the request log on the POST request.

Looking into it further, it's hitting [this](https://github.com/barrelstrength/craft-sprout-base-email/blob/91bb5d92a69cf9d3a30434cc22643a120636d58e/src/mailers/DefaultMailer.php#L210) case in sprout-base-email.

The warning should be available from the [afterSend event](https://github.com/craftcms/cms/blob/004ab9ede036aa22bddd3f2b472c16e11bd8d55d/src/mail/Mailer.php#L177) (it looks like you actually requested the addition of that event 😄 ). And I found this issue which you may be using to track this? https://github.com/barrelstrength/craft-sprout-email/issues/77

**Comment by BenParizek** [comment]
Just a note: I can confirm this is happening, however, all of the potential errors are returned remain quite inconsistent (Templates, Email Addresses, Deliverability). We'll be revisiting this along with the entire error workflow so it may be a bit longer before we address this but when we do, we'll be looking at the whole picture and re-considering if we should be piggybacking on top of Craft here or going through Yii or SwiftMailer directly.

**Comment by BenParizek** [comment]
Issue moved to [barrelstrength/craft-sprout-email #147](https://github.com/barrelstrength/craft-sprout-email/issues/147) via [**ZenHub**](https://www.zenhub.com/)
