### ISSUE TITLE
Rename generic hidden class to prevent conflicts

### ISSUE THREAD

**Issue by nickcobley** [barrelstrength/craft-sprout-forms#354]
### Description (screenshots, logs, ...)

When using the simple method to output the form, eg {{ craft.sproutForms.displayForm('myForm') }}, it's rendering this style to inline into the page:

```
<style>    .hidden{

display: none !important;
 }
</style>
```

Trouble with this is it's using a generic class name, "hidden" which runs a pretty big risk of clashing with other styles. For example in our use case we are using Tailwind CSS, which also uses hidden, the two clash and in this case it hides my site navigation when it shouldn't be hidden.

Can I suggest that this class be renamed to something like "sprout-hidden"?

**Comment by BenParizek** [comment]
@nickcobley Yes, it's a good idea and has been on my mind, but this gets it on the list.

In the meantime, you can use the [Template Override](https://sprout.barrelstrengthdesign.com/docs/forms/template-overrides.html) feature to set a folder for the global form templates for your site and copy over the form.twig file to update that to whatever you need.

**Comment by BenParizek** [comment]
@nickcobley 

This should be resolved in the latest release (v3.6.1) now available in the Plugin Store. Class has been updated to `sprout-hidden` and you may need to update that manually in any custom templates as described in the update notes: https://sprout.barrelstrengthdesign.com/docs/forms/installing-and-updating-craft-3.html#form-templates-2
