### ISSUE TITLE
Entries index blank, despite database records

### ISSUE THREAD

**Issue by engram-design** [barrelstrength/craft-sprout-forms#358]
### Description (screenshots, logs, ...)
For some reason, the entries index is completely blank - https://d.pr/free/i/pvg6mR. This is despite having records in `sproutforms_entries` - https://d.pr/free/i/B3Ylv8

These elements haven't been deleted.

### Additional info

- Plugin version: 3.5.1

**Comment by engram-design** [comment]
So the clue here is that there are elements, but no rows in the content table. This made me look at each form's settings, which showed the issue.

https://d.pr/free/i/lxKg5B

Note my global settings for the plugin:
https://d.pr/free/i/t5fce7

I believe this is related to https://github.com/barrelstrength/craft-sprout-forms/issues/351 where this was messed up. Some migration has either taken place, or hasn't where its not updated these settings per-form. These were all working fine before the update to 3.5.0.

Now have to go into each form and re-save these settings, but have now lost form entry content for the past few weeks.

**Comment by BenParizek** [comment]
@engram-design This should be resolved in the updates with the latest release v3.6.1

Let us know if any other issues arise.
