### ISSUE TITLE
Deleting a duplicated form also deletes fields from original form

### ISSUE THREAD

**Issue by jerome2710** [barrelstrength/craft-sprout-forms#360]
### Description (screenshots, logs, ...)

The rows of `craft_fields` seem to be shared through multiple form copies. When deleting one of the forms, the corresponding fields get deleted leaving all other remaining forms corrupt.

### Steps to reproduce

1. Create form A and add some fields
2. Create form B by saving form A as a copy
3. Delete form B
4. All fields of form A are gone

### Additional info

- Craft version: 3.3.13
- PHP version: 7.2.22
- Database driver & version: MySQL 5.5.64
- Plugins & versions: Sprout Forms 3.5.1

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_13dkz)

**Comment by BenParizek** [comment]
@jerome2710 Thanks for reporting this.

This should be resolved in the latest release (v3.6.1) now available in the Plugin Store.
