### ISSUE TITLE
General template override not working since latest update

### ISSUE THREAD

**Issue by TomDeSmet** [barrelstrength/craft-sprout-forms#364]
### Description (screenshots, logs, ...)
When overriding the templates in general settings, it just doesn't work.
When I override it on a per form basis, with the same templates, it does work.

### Additional info

- Craft version: 3.3.15 Pro
- PHP version: 7.3
- Database driver & version:  MySQL
- Plugins & versions: 3.5.1 Pro

**Comment by BenParizek** [comment]
Looking into it @TomDeSmet

**Comment by BenParizek** [comment]
@TomDeSmet We've updated this behavior so the General Form Template setting should work again. A previous update changed the way that setting behaved to just define the default template selected when creating a form. 

We reverted that and added a new "Default Form Template" option when creating a new form that just dynamically uses that global setting unless you choose to override it and be more specific.
