### ISSUE TITLE
Missing UI element to change multiple attribute on category field

### ISSUE THREAD

**Issue by Skartz** [barrelstrength/craft-sprout-forms#365]
### Description (screenshots, logs, ...)

When using the "Categories" field, the "multiple" attribute is output on the select element. There is  no UI element allowing the modification of this setting.

![image](https://user-images.githubusercontent.com/16026365/68797073-200aa280-0611-11ea-97ce-868eff62c77b.png)

![image](https://user-images.githubusercontent.com/16026365/68797156-49c3c980-0611-11ea-9362-ea3059676a4e.png)

### Steps to reproduce

1. Add categories field to form and check front end output for multiple attribute on select element
2. Category group can have one or more categories to duplicate this output

### Additional info

- Craft version: 3.3.15
- PHP version: 7.2.8
- Database driver & version:  MySQL
- Plugins & versions: 3.5.1 Pro

**Comment by BenParizek** [comment]
Thanks @Skartz. We'll update this thread once we have a fix!

**Comment by BenParizek** [comment]
@Skartz I've looked into this and as we are extending the Craft Categories field behavior for this field type, we are not able to set a limit (the Categories field type does not enable the Element `limit` setting.

I've added a few more comments on this thread for potential workarounds:
https://github.com/barrelstrength/craft-sprout-forms/issues/395

At this point in time, I would recommend considering the workarounds and we'll keep our eye out for an opportunities to address this in a different way.
