### ISSUE TITLE
Potential Craft 2-3 migration issue with user field

### ISSUE THREAD

**Issue by jaydensmith** [barrelstrength/craft-sprout-forms#368]
### Description (screenshots, logs, ...)
I'm not sure if this is an issue with Sprout Forms or if the field is no longer supported. I can't find any info anywhere on this, however. I can see the value of the field in the entries but I can't edit the field or even delete it or change it to another field type.

![Screen Shot 2019-11-19 at 2 51 20 pm](https://user-images.githubusercontent.com/16344913/69115348-539b7000-0adc-11ea-8fbf-4e103aa6f3d6.png)

**Comment by BenParizek** [comment]
@jaydensmith In Craft 2, Sprout Forms extended the Craft Field API and supported receiving data from Craft Fields but not all of those fields were officially supported. Generally, we didn't support any fields that required javascript on the front-end, however adding them to the templates manually could be done. 

Users was one of those fields that could be submitted but had to be done so in a custom way. 

In Craft 3, we added a Form Field API and have not yet added support for a Users field, so, right now, a custom Field (or PR) would need to be created to add support for the Users field. It's something we'd like to add, I just can't promise when we'll get to it.

I've created an issue for Adding a Users Field here:
https://github.com/barrelstrength/craft-sprout-forms/issues/369

**Comment by BenParizek** [comment]
If you do need to create a custom field for this, here are the docs for [Custom Form Fields](https://sprout.barrelstrengthdesign.com/docs/forms/custom-form-fields.html).

And you may be able to use the existing Entries, Categories, or Tags Form Fields as starting points.

**Comment by BenParizek** [comment]
@jaydensmith We've added a Users relation form field in v3.8.2 along with a migration if a custom `craft\elements\Users` field was being used in Craft 2. The migration does not trigger when updating to the latest, but will trigger when migrating from Craft 2 anew.
