### ISSUE TITLE
Updating search index from the command line fails due to access to session

### ISSUE THREAD

**Issue by mklishevych** [barrelstrength/craft-sprout-forms#376]
### Description (screenshots, logs, ...)
Running craft queue from the command line results in the error for the Updating Search Indexes job. The cause is Invisible field implementation, which accesses session component, which is not available in the CLI environment. 

barrelstrength/sprout-forms/src/fields/formfields/Invisible.php:160

```php
    public function normalizeValue($value, ElementInterface $element = null)
    {
        $invisibleValue = Craft::$app->getSession()->get($this->handle);
        // ...
    }
```

### Steps to reproduce

1. Save the form with Invisible field 
2. Run craft queue from CLI

### Additional info

- Craft version: 3.3.15
- PHP version: 7.2
- Database driver & version:  
- Plugins & versions: Sprout Forms 3.6.2

**Comment by BenParizek** [comment]
Thanks @mklishevych We'll get this fixed.

**Comment by BenParizek** [comment]
@mklishevych This should be resolved in the latest release.
