### ISSUE TITLE
Report for Sprout Form Entries generates wrong id, dateCreated and dateUpdated

### ISSUE THREAD

**Issue by away86** [barrelstrength/craft-sprout-forms#384]
### Description (screenshots, logs, ...)
The report for Entries - Spourt Forms gives wrong data for the following columns:
- id
- dateCreated
- dateUpdated

For id, all the rows show: 1
For dateCreated and dateUpdated, all the rows show: 2019-02-15 00:56:22

The records in corresponding table in the database shows correct data, so it's just the report somehow display incorrect values.

### Steps to reproduce

1. Create a new report (Entries - Sprout Forms)
2. Run report

### Additional info

- Craft version: Craft Pro 3.3.16.3
- PHP version: 7.3.11 (also tested on 7.1.29, same issue)
- Database driver & version:  MySQL 5.5.5
- Plugins & versions:

Sprout Fields - 3.4.4
Sprout Forms - 3.6.4
Sprout Reports - 1.2.11
Google reCAPTCHA for Sprout Forms - 1.0.6

_For some issues, we may request that you send the following items to Support <sprout@barrelstrengthdesign.com>. If you feel your issue may fall in that category, feel free to send things over after you post this issue and reference the issue in your email._

- `composer.json`
- `storage/logs/web.log` (or a zip of the whole log folder)
- An export of your database (or, if you can't share the whole db, the specific Sprout tables)

**Comment by BenParizek** [comment]
Thanks for reporting @away86. This is resolved in the latest release v3.6.6
