### ISSUE TITLE
Add Limit setting to Category Relations field

### ISSUE THREAD

**Issue by jaydensmith** [barrelstrength/craft-sprout-forms#395]
You can no longer seem to be able to set a selection limit on categories, it wil always show a multiple select combo box.

**Comment by BenParizek** [comment]
This hasn't yet been possible in Sprout Forms. Categories in the Craft CP have a Branch Limit and we hadn't decided on the best way to address this on the front-end. I'll add this to our list and revisit it when I can.

**Comment by BenParizek** [comment]
If limiting category selection is needed, the best way to address this will be to override the Categories field template for a specific Form and display a different input where you manage how the field is limited on the front-end. Or to update the Category Elements you have to instead use an Entries Elements that provides a Limit option.

As it is expected that Craft will be merging the Entry and Category Element concepts in Craft 4, we will be holding off on any more specific solution for this right now until we understand how that will be implemented and will plan to update Form Field support to embrace the concepts that the new format supports.

On the back-end, we're extending the Craft field behavior and the only limit option provided is a "Branch Limit" which limits the number of different top-level branches in a category structure hierarchy that can be selected. This may feel like the same as a "limit" when using one level category structures but does not behave the same way for multi-level category structures and would not be clear in the front-end UI what was being limited unless additional front-end styling was added to toggle the various selected states while a user was interacting with the field.
