### ISSUE TITLE
Email field type doesn't use html5 email input type

### ISSUE THREAD

**Issue by darylknight** [barrelstrength/craft-sprout-forms#397]
If you create an email field on a form, it outputs this on the frontend:

`<input type="text" name="fields[email]" id="fields-email" class="email" required="" aria-required="true">`

That should be 

`<input type="email" name="fields[email]" id="fields-email" class="email" required="" aria-required="true">`

The result is that if someone enters an invalid email address, the site crashes (Internal server error) and Sprout Forms logs this:

    2020-01-08 10:22:40 [-][1][3f05aa88dcc54d9ddff7948d5570f7e6][error][barrelstrength\sproutforms\services\Entries::saveEntry] Failed to save element: Address in mailbox given [test] does not comply with RFC 2822, 3.6.2.
    2020-01-08 10:22:40 [-][1][3f05aa88dcc54d9ddff7948d5570f7e6][error][Swift_RfcComplianceException] Swift_RfcComplianceException: Address in mailbox given [test] does not comply with RFC 2822, 3.6.2. in /srv/users/serverpilot/apps/lwa-website/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php:355

If this was set to an email field type, that wouldn't happen as the browser would catch it first.

**Comment by BenParizek** [comment]
Thanks for the heads up @darylknight 

We'll get this in the queue. Until we get that released, you can create a template override and update that email field input, if you'd like:
https://sprout.barrelstrengthdesign.com/docs/forms/template-overrides.html

**Comment by darylknight** [comment]
Thanks Ben - I'm aware of the overrides; just flagging that as there is an email input type, it should probably be used by default for the email field. Cheers!

**Comment by BenParizek** [comment]
@darylknight Can you confirm the field in question is an Email field and not just a Single Line field named "Email"? Or that you don't happen to be already overriding this particular field with an older version of the email template somewhere?

It appears both the Accessible and Basic Form Templates provided are using the `email` input type:

https://github.com/barrelstrength/craft-sprout-forms/blob/v3.6.8/src/templates/_components/formtemplates/accessible/fields/email/input.twig#L16
https://github.com/barrelstrength/craft-sprout-forms/blob/v3.6.8/src/templates/_components/formtemplates/basic/fields/email/input.twig#L16

**Comment by darylknight** [comment]
Yes - as far as I can tell

![image](https://user-images.githubusercontent.com/1250017/72202122-9c303380-3464-11ea-8ab7-80c0bfae8c2f.png)

![image](https://user-images.githubusercontent.com/1250017/72202123-9f2b2400-3464-11ea-8fcc-56eda2e51022.png)

**Comment by BenParizek** [comment]
@darylknight Can you confirm what version of Sprout Forms you are using? We had a bug that was fixed in v3.6.7 where the "Field Type" setting was just outputting the same value as the "Name" of the field. So, if your Field was named "Email" it might appear to be the "Email" Field Type where it could really be the "Single Line" field under the hood.

**Comment by darylknight** [comment]
Ah, that was it. I was on 3.6.6. I've just updated to 3.6.9 and it was a single-line field. I've updated this to an email field type and all correct now. Thanks Ben!
