### ISSUE TITLE
Can't write; duplicate key in table 'craft_sproutforms_integrations_log'

### ISSUE THREAD

**Issue by TomDeSmet** [barrelstrength/craft-sprout-forms#402]
All websites that have Sprout forms before 3.6.5 (the migration bug see #377) are affected I believe.
Whenever I deploy the DB (with Capistrano) I get the error

`Can't write; duplicate key in table 'craft_sproutforms_integrations_log'`

When I look into the local database the table is empty, when I check the deployed database, the table doesn't even exist (neither does craft_sproutforms_rules).

So I don't understand why it complains about duplicate keys and stops updating the database...
Only 'solution' I found is creating a new database on the server and deploy the local DB to the new empty one.

**Comment by BenParizek** [comment]
@TomDeSmet Can you give me a few more details

What version of Sprout Forms are you on? What steps are you taking to trigger the error? Can you clarify for me what is happening when you deploy your database? I need to understand how to try to recreate this. Are you dropping the existing tables before you deploy the new db? Are you trying to overwrite the tables? Do you have a custom migration script?

**Comment by TomDeSmet** [comment]
Initial Sprout version: 3.5.1

**Steps to reproduce:**
1. Install Sprout version 3.5.1 on local dev (Valet)
2. Update Sprout to latest version on local dev
3. GIT push changes to production branch
4. Deploy GIT files to production
5. Deploy DB to production

**What is happening to the DB**
DB changes are applied, but with the exception for some tables in Sprout forms (as stated above) which breaks Sprout forms plugin. The above error is returned.

**Steps to deploy DB**
Our SQL files are dropping all tables if they exist, re-create them and insert the new data.

**Migration**
We don't have a custom migration script.

**Comment by BenParizek** [comment]
@tomdavies First, just to note it I don't think this has anything to do with #377. That issue related to fieldLayoutIds being assigned incorrectly around duplicate forms. 

The error message here is a MySQL data constraint error pertaining to the relationship between the `sproutforms_integrations_log` and how it's metadata defines it's column's relationship to other columns in the database that are defined as keys. It does appear we're defining the foreign keys on these tables in a similar way that we've done on other tables in the plugins, so I'm not sure what is different here. Please bear with me as we try to figure that out.

Could you share the CREATE TABLE statement that is being generated in your SQL file that throws the error when being imported? And, could you confirm what database and database version you are using locally and remotely? MySQL, MariaDB, v?

As an example, my database export gives me the following DROP TABLE / CREATE TABLE syntax. When I run this command on an existing database with Sprout Forms installed, I do not get any errors. 

```
DROP TABLE IF EXISTS `craft_sproutforms_integrations_log`;

CREATE TABLE `craft_sproutforms_integrations_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `entryId` int(11) DEFAULT NULL,
  `integrationId` int(11) NOT NULL,
  `success` tinyint(1) DEFAULT 0,
  `status` enum('pending','notsent','completed') NOT NULL DEFAULT 'pending',
  `message` text DEFAULT NULL,
  `dateCreated` datetime NOT NULL,
  `dateUpdated` datetime NOT NULL,
  `uid` char(36) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `craft_sproutforms_log_entryId_fk` (`entryId`),
  KEY `craft_sproutforms_log_integrationId_fk` (`integrationId`),
  CONSTRAINT `craft_sproutforms_log_entryId_fk` FOREIGN KEY (`entryId`) REFERENCES `craft_sproutforms_entries` (`id`) ON DELETE CASCADE,
  CONSTRAINT `craft_sproutforms_log_integrationId_fk` FOREIGN KEY (`integrationId`) REFERENCES `craft_sproutforms_integrations` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

Perhaps looking more closely at how your schema is defined and, in particular, the Foreign Keys between your two database environments, we can narrow down why things are behaving differently.

**Comment by BenParizek** [comment]
@TomDeSmet It's also possible this issue is caused after the CREATE TABLE code run and the INSERT statement is adding something to the database. So if you could share whatever the INSERT statement you are running to populate the `sproutforms_integrations_log` we can take a look at that too.

**Comment by TomDeSmet** [comment]
Hi Ben,

I'm using MySQL 5.7 locally and on staging/production.

This is my current DROP TABLE / CREATE TABLE but it dates from **after** updating the plugin, I don't have one from before unfortunately. I will try to find an older project that may have an older plugin version.

```
--
-- Table structure for table `craft_sproutforms_integrations_log`
--

DROP TABLE IF EXISTS `craft_sproutforms_integrations_log`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `craft_sproutforms_integrations_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `entryId` int(11) DEFAULT NULL,
  `integrationId` int(11) NOT NULL,
  `success` tinyint(1) DEFAULT '0',
  `status` enum('pending','notsent','completed') NOT NULL DEFAULT 'pending',
  `message` text,
  `dateCreated` datetime NOT NULL,
  `dateUpdated` datetime NOT NULL,
  `uid` char(36) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `craft_sproutforms_log_entryId_fk` (`entryId`),
  KEY `craft_sproutforms_log_integrationId_fk` (`integrationId`),
  CONSTRAINT `craft_sproutforms_log_entryId_fk` FOREIGN KEY (`entryId`) REFERENCES `craft_sproutforms_entries` (`id`) ON DELETE CASCADE,
  CONSTRAINT `craft_sproutforms_log_integrationId_fk` FOREIGN KEY (`integrationId`) REFERENCES `craft_sproutforms_integrations` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `craft_sproutforms_integrations_log`
--

LOCK TABLES `craft_sproutforms_integrations_log` WRITE;
/*!40000 ALTER TABLE `craft_sproutforms_integrations_log` DISABLE KEYS */;
/*!40000 ALTER TABLE `craft_sproutforms_integrations_log` ENABLE KEYS */;
UNLOCK TABLES;
```

I can't seem to find any INSERTS (tables are empty in the DB anyway)

**Comment by BenParizek** [comment]
@TomDeSmet 

From our two CREATE TABLE syntaxes, I don't see anything significantly different that would cause the issue you're describing. While I don't know enough to rule out Sprout Forms here (It is suspicious that it's just this table), I also don't think we can rule out other factors that may be causing this at the database level that we haven't identified yet. 
 
Can you run the following command in both of your DBs and see if you see anything that can help us in the results? Constraints need to be unique in the entire database so the command is just going to list out the constraints that this CREATE TABLE statement is trying to insert to see if there may be another one by a similar name somewhere. We would expect the results to just list the two constraints defined by the CREATE TABLE statement.

```
SELECT `TABLE_SCHEMA`, `TABLE_NAME`
FROM `information_schema`.`KEY_COLUMN_USAGE`
WHERE `CONSTRAINT_NAME` IN (
  'craft_sproutforms_log_entryId_fk',
  'craft_sproutforms_log_integrationId_fk'
);
```

If that doesn't shed any light, would you be able to send over your full db (or if that's not possible, all of your sprout tables to sprout@barrelstrengthdesign.com)?

**Comment by BenParizek** [comment]
As we need more info to proceed here and we don't have any other reports of this issue, I'm closing this out for now. Please drop us a note with more details if you'd like to re-open.
