### ISSUE TITLE
Array offset error in existing form with Address field after recent update, Dev Mode on, PHP 7.4

### ISSUE THREAD

**Issue by matthisamoto** [barrelstrength/craft-sprout-forms#405]
### Description (screenshots, logs, ...)

Receiving error when trying to view form using address field locally on front-end, or to save the form in the back-end, even without actual changes.

`yii\base\ErrorException: Trying to access array offset on value of type null in [craft root]/vendor/barrelstrength/sprout-base-fields/src/services/Address.php:491`

### Steps to reproduce

1. Dev mode on
THEN
2. Save form with address field
OR 
2. View form with address field on front-end of site

### Additional info

PHP version	7.4.1
OS version	Darwin 19.2.0
Database driver & version	MySQL 5.5.5
Image driver & version	GD 7.4.1
Craft edition & version	Craft Pro 3.3.20.1
Yii version	2.0.31
Twig version	2.12.3
Guzzle version	6.5.1
Imagine version	1.2.3-dev

**Comment by BenParizek** [comment]
Thanks for reporting @matthisamoto 

I just released v3.5.4 which should address this issue. We haven't overly tested on PHP 7.4 yet so let me know if you run into anything else.
