### ISSUE TITLE
Craft 3.4 Issue

### ISSUE THREAD

**Issue by jaydensmith** [barrelstrength/craft-sprout-forms#407]
I'm sure you're on it already, but with the release of 3.4 just around the corner it's worth pointing out that the form editor interface doesn't work at all in the RC.

Thanks!

**Comment by BenParizek** [comment]
On it! I currently believe we're on course to have things ready next week, but still working through a few things that need updating.

**Comment by TomDeSmet** [comment]
Any new ETA on this?

**Comment by BenParizek** [comment]
@tomdavies Soon.

The big change in the Craft 3.4 UI for us was that Craft now handles overflow tabs in a way that broke how we handled re-ordering Form Tabs in the UI. We've refactored that and been able to add several other improvements in the process, but it's taken a bit longer than anticipated. At this point, the updates are mostly complete and I'm testing and polishing a few related releases.

**Comment by BenParizek** [comment]
@jaydensmith @TomDeSmet We just released v3.8.0 which adds Craft 3.4 support.

The biggest change for Sprout Forms turned out to be Craft's addition of the overflow tab behavior, which forced us to refactor the Page reordering and Form Builder Field Layout UI in several ways. Enjoy!

**Comment by TomDeSmet** [comment]
@BenParizek Great, thanks. Still a small (large) issue on Firefox and on Chrome with the 'upgrade to Pro' button.

![Screen Shot 2020-02-06 at 09 06 38 AM](https://user-images.githubusercontent.com/16959207/73917750-54b09200-48c0-11ea-809e-f8436abd6187.png)
![Screen Shot 2020-02-06 at 09 07 15 AM](https://user-images.githubusercontent.com/16959207/73917753-58441900-48c0-11ea-87df-33bfaadadc5f.png)

**Comment by BenParizek** [comment]
Thanks @TomDeSmet. Looks like we overlooked loading a resource on that index page. I've just pushed v3.8.0.1 which should correct the issue.
