### ISSUE TITLE
Error message shows after save field

### ISSUE THREAD

**Issue by feijian** [barrelstrength/craft-sprout-forms#409]
### Description (screenshots, logs, ...)
When I create/edit form in back end. Every time when I edit field and save. Craft will show error message 'An unknown error occurred.' Also after this any new added field will not save.

### Steps to reproduce
1. Edit field details (e.g. Name, Required etc) or do nothing and click save. 
2. Add new field (Any field e.g. Single Line)
3. Craft CMS show error message 'An unknown error occurred.'
4. Save the form. New field is not been saved.

### Additional info

- Craft version: 3.3.17
- PHP version: 7.3.5
- Database driver & version:  Mysql 5.0.12-dev
- Plugins & versions: 
Sprout Forms - 3.7.1.1
Sprout Reports - 1.2.11
Sprout Fields - 3.5.4

**Comment by BenParizek** [comment]
@feijian This issue will be resolved in our next release, which we'll have out soon.

Until then, you may be able to work around the issue by saving the form between your actions such as after adding or after editing a field.

**Comment by feijian** [comment]
@BenParizek Thanks! :)

**Comment by BenParizek** [comment]
@feijian We just released Sprout Forms v3.8.0 which adds Craft 3.4 support and addresses this issue.
