### ISSUE TITLE
Unable to add fields to new form

### ISSUE THREAD

**Issue by dwaring** [barrelstrength/craft-sprout-forms#410]
### Description (screenshots, logs, ...)

I've just installed the Sprout Forms trial to test the plugin and am seeing the same issue as reported in [issue #311](https://github.com/barrelstrength/craft-sprout-forms/issues/311).

On creation of a new form and attempting to add fields, I'm unable to add a field.

![image](https://user-images.githubusercontent.com/288552/73814188-3ac86e00-4832-11ea-96f5-530feb519e56.png)

### Steps to reproduce

1. Installed Sprout Forms trial
2. Added a new form
3. Attempted to add a field by dragging a field type and nothing happens. 

### Additional info

- Craft version: 3.4.3
- PHP version: 7.4
- Database driver & version:  MySQL 5.7
- Plugins & versions: Sprout Forms (Lite) 3.7.1.1

**Comment by BenParizek** [comment]
@dwaring We'll have a release out soon with Craft 3.4 compatibility updates. I'll update this thread when we do.

**Comment by BenParizek** [comment]
@dwaring We just released Sprout Forms v3.8.0 which adds Craft 3.4 support.
