### ISSUE TITLE
Entries getting marked as spam, failing Duplicate Submission Captcha

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-forms#415]
Caching seems to be the culprit.Entries getting marked as spam, failing Duplicate Submission Captcha

The simple fix to this right now is to disable the Duplicate Submission Captcha until we get a fix out. 

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1cscj)

**Comment by BenParizek** [comment]
This appears to also happen with other Captchas, such as the Javascript Captcha. 

Will be addressed in https://github.com/barrelstrength/craft-sprout-forms/issues/392

**Comment by SophietjesCode** [comment]
We have the same issue even with Duplicate submission captcha turned off. We only have Google Captcha. 
When will this get fixed please?

**Comment by BenParizek** [comment]
@SophietjesCode On the Form Entries that are getting marked as spam, what is the reason they say they are being marked as spam? When you edit one of these Entries in the control panel, you should see some information on why the given Entry was marked as Spam in the right sidebar.

**Comment by SophietjesCode** [comment]
["Google reCAPTCHA can't be blank."] but they do eventually validate the checkbox and the form is being submitted but flagged as spam. 
I also found out that IE11 doesn't show the Google Captcha and forms submitted via IE11 are being all flagged as spam.

**Comment by BenParizek** [comment]
The JS Captcha should be resolved in v3.8.6.  Still looking into the others.

**Comment by jeremyfrank** [comment]
We also were getting reports of submissions that we were not able to find in the admin, and later found them in server logs flagged as a duplicate submission. Does 3.8.6 fix this or does the duplicate submission setting still need to be turned off?

**Comment by BenParizek** [comment]
@jeremyfrank v3.8.6 fixes a bug in the Javascript Captcha validation. Probably best to test your particular use case right now regarding the other captchas. 

@SophietjesCode One scenario that may be happening to cause what you are seeing could be if you have some additional javascript listening to the form's `submit` event. Right now, with the current implementation of the reCAPTCHA plugin, it is watching for the submit event so if you have a second script also watching for the submit event the second script can submit the form before reCAPTCHA has a chance to validate – triggering the spam flag that you are seeing.

I'm currently working on a solution which includes refactoring how we handle the submit and making a few javascript events available so that dependent JS can rely on the custom Sprout Forms javascript events rather than fighting for the same submit handler. I'll update this thread when I have that ready.

**Comment by BenParizek** [comment]
@SophietjesCode @jeremyfrank 

Broadly stated, this issue was one of a few similar issues caused by a couple different scenarios taking place with some recent updates to the Sprout Forms spam tracking and submit workflows.

If you haven't already, please update to the latest version of Sprout Forms and make sure to review and make the updates noted in the upgrade notes:
https://sprout.barrelstrengthdesign.com/docs/forms/installing-and-updating-craft-3.html#upgrading-to-forms-v3-10-0

I believe the majority of these scenarios have been solved so I'm going to close this out and ask that if you are still running into anything that you open a new ticket specific to your scenario.

**Comment by besimhu** [comment]
Sorry to bring this issue back up. 

I have the exact same issue with 3.12.2. I keep seeing `["Google reCAPTCHA can't be blank."]` as a reason it is under SPAM. I also only have Google reCAPTCHA as the only form of SPAM protection. 

I have tested with invisible and regular "I am not a robot" CAPTCHA and I keep getting the same result. 

What's more interesting is that it is only happening with one form.

**Comment by SophietjesCode** [comment]
We have the exact same issue as @besimhu . It is mostly 1 of the forms that gets flagged for no reason. I'm not talking about the occasional misclassification... . We had to save the spam's so that we can check regularly the wrongly spamflagged entries and resave them not as spam. :(

**Comment by BenParizek** [comment]
@besimhu @SophietjesCode 

I'm going to need more info to help troubleshoot. Can you please open a new ticket and provide information about what templates you are using, examples of the custom templates you are using if you are using custom templates, what other settings you have in place for the form causing the issue (any other captchas, any other submit behaviors?), and any custom javascript you might be using on the template pages?

New Bug Report:
https://github.com/barrelstrength/craft-sprout-forms/issues/new?template=bug-report.md
