### ISSUE TITLE
Getting unknown property: barrelstrength\sproutforms\elements\Entry::typeId when including form in layout

### ISSUE THREAD

**Issue by sfdrummer** [barrelstrength/craft-sprout-forms#420]
I'm including my Sprout form in my main layout template which is extended by other templates.  This is done in the normal way with `{{ craft.sproutForms.displayForm('contactForm') }}`.

Craft is erroring with Unknown Property – yii\base\UnknownPropertyException - Getting unknown property: barrelstrength\sproutforms\elements\Entry::typeId.

### Steps to reproduce

1.  Add Sprout form to page
2.  Load page

### Additional info

- Craft version:  3.4.5
- PHP version: 7.3.9
- Database driver & version:  MySQL 5.7.27
- Plugins & versions:
CKEditor  1.0.0-beta.2
Cookie Consent Banner 1.2.5
Expanded Singles  1.0.8
Position Fieldtype  1.0.14
SEO 3.6.3
Sprout Forms  3.8.0.2
Width Fieldtype 1.0.6

**Comment by BenParizek** [comment]
@sfdrummer Can you test outputting the form via the `displayForm` tag in a blank template where you don't extend any other template and let me know if you still see the error?

Do you happen to be using the Entry Integration? The only place I see `typeId` referenced in our codebase is in the Entry Element integration while it is being submitted, so I wouldn't expect that to be throwing an error on page load. But the question is: what is trying to reference `typeId` on the Form Entry Element during the page load?

Are you using custom templates or did you happen to create and/or delete any fields with the name `typeId` at any point?

**Comment by sfdrummer** [comment]
@BenParizek It looks like the form is working fine now, and I did nothing.  Perhaps it was a stale cache?  I have just done an update.

I'll reopen this issue if it happens again, thanks for getting back to me so quickly!

**Comment by sfdrummer** [comment]
@BenParizek I actually discovered that it was the CraftCMS Cookie Consent Banner plugin (https://plugins.craftcms.com/cookie-consent-banner) that was causing this issue.  Saw a reference to it in the stack trace and have now uninstalled it and the site is working fine now.  I'll probably open a ticket with that plugin to see whats going on.

**Comment by BenParizek** [comment]
@sfdrummer Feel free to link to this ticket in your other one if it helps figure things out.
