### ISSUE TITLE
Unable to preview notifications

### ISSUE THREAD

**Issue by jaydensmith** [barrelstrength/craft-sprout-forms#421]
The preview button for notifications seems to go to the wrong URL.
![Screen Shot 2020-02-12 at 4 26 21 pm](https://user-images.githubusercontent.com/16344913/74305604-82ac3f80-4db4-11ea-916e-3d1eb865e438.png)

**Comment by BenParizek** [comment]
Thanks @jaydensmith. I just released v8.3.1 that should address this issue.
