### ISSUE TITLE
Error when opening reports page in admin

### ISSUE THREAD

**Issue by rauwebieten** [barrelstrength/craft-sprout-forms#422]
### Description (screenshots, logs, ...)

After a server crash, we needed to restore a previous database. We now have the following error in the logs, when visiting /admin/sprout-forms/reports

2020-02-17 17:31:46 [-][1][latkqrne15qk1np5c0i3450sho][error][yii\db\Exception] PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'sproutreports_reports.emailColumn' in 'field list' in PhpstormProjects\inaras-octopus-craft\vendor\yiisoft\yii2\db\Command.php:1290

### Additional info

- Craft version: Craft CMS 3.3.20.1
- PHP version: 7.1.26
- Database driver & version:  
- Plugins & versions: "barrelstrength/sprout-forms": "3.6.9",

**Comment by rauwebieten** [comment]
The reports table looks like this:
https://pasteboard.co/IV7IYo0.png

**Comment by BenParizek** [comment]
@rauwebieten This suggests a migration was not run at some point. Did you update any plugins to more recent versions as you restored?

One scenario where this could occur may be if there was some sort of mismatch between the version of the sproutreports_reports table in the database and the installed version of the Sprout Forms files.

**Comment by rauwebieten** [comment]
Hey, thanks for the quick reply.

Was the email column added/removed somewhere between 3.6.9 and the current release?

Is there a way to force migration updates, without loosing data?

**Comment by rauwebieten** [comment]
I managed to fix the installation by upgrading craft and all plugins.
Thanks for the support
