### ISSUE TITLE
File Upload field throws "defaultUploadLocation" error in CP

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-forms#432]
Introduced in Craft commit: https://github.com/craftcms/cms/commit/cb16a389a34d2d92f00a6e0b546c6ab3cfcb5273

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1dwhv)

**Comment by JJefferyDev** [comment]
Hi Ben, while the file uploads are now visible on the direct form entries and inside the asset folder, they still don't translate through the Integrations.

**Comment by BenParizek** [comment]
Thanks for reporting @JJefferyDev 

I've opened a new ticket to track this item as it seems to relate to Relations field more generally: 
https://github.com/barrelstrength/craft-sprout-forms/issues/434

I'll add a note here once we have a fix out.

**Comment by BenParizek** [comment]
The Entry Element Integration mapping issue for File Upload fields noted above has been fixed in v3.8.5.
