### ISSUE TITLE
File upload field db column missing

### ISSUE THREAD

**Issue by jeremyfrank** [barrelstrength/craft-sprout-forms#433]
### Description

We've have a file upload field on our form for some time, but the db column for this field is missing.

![image](https://user-images.githubusercontent.com/283397/75356220-a58f2700-587d-11ea-9a59-8c1a48de2dac.png)

![image](https://user-images.githubusercontent.com/283397/75356398-e850ff00-587d-11ea-8df9-de1e5e06e424.png)

The field does display on the front-end, and the files are uploaded to the asset source.

![image](https://user-images.githubusercontent.com/283397/75356955-9f4d7a80-587e-11ea-9783-4f9bee54afb7.png)

![image](https://user-images.githubusercontent.com/283397/75357056-c441ed80-587e-11ea-8986-273596ed3917.png)

When adding some new fields to the form, they all save new db columns except for the file upload field.

![image](https://user-images.githubusercontent.com/283397/75356735-5695c180-587e-11ea-8441-0733ed5baba6.png)

![image](https://user-images.githubusercontent.com/283397/75356823-7331f980-587e-11ea-9846-ef1cf0085710.png)

### Additional info

- Craft version: 3.3.20.1
- PHP version: 7.2.24
- Database driver & version: MySQL 5.7.29
- Plugins & versions:
  - "barrelstrength/sprout-fields": "3.4.4",
  - "barrelstrength/sprout-forms": "3.7.1.1",

**Comment by BenParizek** [comment]
@jeremyfrank This is expected. the File Upload field is a Relations field, so the data is stored in the `craft_relations` table and just tracks the relationship between the Element ID of your Form Entry and the Element ID of the Craft Asset that was uploaded. The specific details around the Asset itself will be stored in the Craft asset tables. You will see similar behavior with the other relations fields as well, and in a few other cases, some other fields may also store data in a related table – like the Address Field.

That said, there is a bug in the latest release when viewing Entries with Asset fields. We'll have a fix out for that shortly:
https://github.com/barrelstrength/craft-sprout-forms/issues/432

**Comment by jeremyfrank** [comment]
Gotcha. I didn't consider that the data for this would be in a separate relations table. Thanks. I'll look out for that upcoming fix.

**Comment by BenParizek** [comment]
Just to note it as we discussed it here, the fix for #432 has been released. It will only affect installs using Craft 3.4 where the bug existed and does not apply to the situation being discussed in this thread as it pertains to Craft 3.3.
