### ISSUE TITLE
Relations Field no longer map in Entry Element integration

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-forms#434]
Confirmed with Entries and File Upload fields.

### Notify

- https://github.com/barrelstrength/craft-sprout-forms/issues/432#issuecomment-591609567

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1dz5v)

**Comment by JJefferyDev** [comment]
Existing Integrations no longer populate on form submission with v3.8.5.  The form entry exists, but its integration copy no longer gets created.

**Comment by BenParizek** [comment]
See: https://github.com/barrelstrength/craft-sprout-forms/issues/440
