### ISSUE TITLE
Integrations no longer populate on form submission with v3.8.5

### ISSUE THREAD

**Issue by JJefferyDev** [barrelstrength/craft-sprout-forms#440]
### Description (screenshots, logs, ...)

Integrations no longer work with v3.8.5.  An Integration set to create an entry when a form entry is created no longer works.

### Steps to reproduce

1. Create any type of Integration
2. Submit a form entry through the form front end

### Additional info

- Craft version: Craft Pro 3.4.8
- PHP version: 7.3.15
- Database driver & version:  MySQL 8.0.16
- Plugins & versions:
Sprout Forms | 3.8.5
Sprout Fields | 3.6.1

(I can't share db due to security reasons)

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1elkz)

**Comment by JJefferyDev** [comment]
Hi @BenParizek I sent you an email last week with my web.log and db files related to this bug.

**Comment by BenParizek** [comment]
@JJefferyDev I can confirm receipt. We're a bit backlogged right now catching up on several changes that were introduced in Craft 3.4.

I consider this a critical bug and we will get to it as soon as we can and I will update you and this thread when we do.

**Comment by BenParizek** [comment]
@JJefferyDev I think this may relate to another bug related to [Form Entries getting marked as Spam when they shouldn't be](https://github.com/barrelstrength/craft-sprout-forms/issues/415).

I believe the Integration will work if you disable all of the Captchas in the Spam Settings. The Integrations never get created if an item is marked as spam. Any submitted items Form Entries that didn't appear to go through may appear under the Form Entries Spam sidebar item.

I'm working on a fix to address these items as soon as I can this week. In my tests, outside of this, Integrations are working as expected so if you are still seeing any issues with Integrations after disabling the Spam checks, please let me know and I'll likely need more info on how you have things configured to try to recreate that.

**Comment by JJefferyDev** [comment]
@BenParizek I'll try that fix and get back to you.  However, I didn't have the Captchas or Spam filters set up or changed from the base settings.

**Comment by JJefferyDev** [comment]
@BenParizek I've just installed v3.8.7 of Sprout Forms and disabled all Spam and Captcha settings and the Entry Integrations are still not working.  Would you like me to email you my database?

**Comment by richardwiggins** [comment]
Hi @BenParizek, I'm having this same issue, as discussed on Discord. A fresh local install of Craft 3.4.16 and Forms 3.9.0.1.

Save Data is set to DB and form submissions are being saved, it's just not creating entries in the _integrated_ entry type. Send Rule is set to _always_.

Here's the setting for the integration:
<img width="1209" alt="Screenshot 2020-04-28 at 16 12 20" src="https://user-images.githubusercontent.com/940047/80504474-141a5f00-896b-11ea-9dbd-4ff5fd9e05a5.png">

**Comment by richardwiggins** [comment]
Any news on this @BenParizek?

**Comment by BenParizek** [comment]
@richardwiggins Thanks for the details. I'm finally getting to this. I can recreate the error now and it seems to have to do with the Post Date setting. Craft recently changed the behavior of how we set some variables on Element Models so I'll look into what we need to adjust there to get this resolved.

**Comment by BenParizek** [comment]
@JJefferyDev @richardwiggins I've just released v3.11.6 which fixes at least once scenario which may have been breaking things here which was the mapping of the Post Date value.

Please let me know if this resolves this. Jessica, it appears one of your forms had a postDate but not the other, so let me know if this resolves the one that you were having issues with. In general, the submission behavior is working so if any problems continue, I believe they are going to be specific to a particular setting in your configuration which we'll need to track down.

In the case you do have any additional issues, a screenshot like the one provided above is a handy way for me to have a better understanding of what to try to test to recreate an issue, and please note that when an Element Integration is set up, any submitted Entries should show an Integrations section in the sidebar of the submitted Form Entry that may show an error message if the integration fails.

https://share.barrelstrength.co/nOu84vdj

----

Richard, just a short note on your screenshot. It appears you are mapping both the Form ID and Entry ID as the `slug` of the Entry you are creating. Only one of those values is going to get mapped (probably the one that gets set second while populating the Entry Slug value) and this will result in your URL just having a number, like `website.com/123`. Just wanted to note that in case any of that is undesired behavior.

I'm going to close this out for now, but we can re-open if any issues persist.

**Comment by richardwiggins** [comment]
@BenParizek Thanks for getting it sorted. I unfortunately had go a different route as I hadn't heard and needed to get it working.
