### ISSUE TITLE
Feature Request: Return class short name in getFields()

### ISSUE THREAD

**Issue by daltonrooney** [barrelstrength/craft-sprout-forms#445]
### The problem (description, use case, screenshots...)

I'm trying to dynamically build a form with Vue by looping through each field and selecting the correct component in Vue. I created a JSON object using something like this

```
{% set form = craft.sproutForms.form(formHandle) %}
{% set fields = form.getFields %}
{{fields|json_encode()|raw}}
```
which I thought would give me all the necessary information I need to construct the form.

The only thing I'm missing from each field is the name of the component to load. text, email, textarea, etc.

### The solution (that feature you'd like to see)

Digging through some of the source code I found the getFieldInputFolder() function, which returns exactly what I need. Is there any way to add that to the to the output of the getFields() function? I believe this would hold me over until the GraphQL implementation is worked out.

**Comment by BenParizek** [comment]
@daltonrooney I believe you can get what you need with a slightly modified building of your array in Twig:

``` twig
{% set form = craft.sproutForms.form('contact') %}
{% set fields = form.getFields() %}
{% set fieldsModified = [] %}
{% for field in fields %}
    {% set folder = field.getFieldInputFolder() %}
    {% set field = field|merge({
        'folder': folder,
    }) %}
    {% set fieldsModified = fieldsModified|merge([field]) %}
{% endfor %}
{{fieldsModified|json_encode()|raw}}
```

Alternatively, you could build the JSON you are using via the [Element API](https://plugins.craftcms.com/element-api) plugin and get that value in PHP too.

Below is an example of the `config/element-api.php` file defining an endpoint to get any of your forms by its ID (i.e. `api/sproutforms/123.json`). This is a quick example so you can probably structure the data better but the "folder" value should be what you are looking for.

``` php
return [
    'endpoints' => [
        'api/sproutforms/<formId:\d+>.json' => function($formId) {
            return [
                'elementType' => Form::class,
                'criteria' => ['id' => $formId],
                'one' => true,
                'transformer' => function(Form $form) {
                    foreach ($form->getFieldLayout()->getTabs() as $tab) {
                        foreach ($tab->getFields() as $field) {
                            $fields[] = [
                                'field' => $field,
                                'folder' => $field->getFieldInputFolder()
                            ];
                        }

                        $tabs[] = [
                            'title' => $tab->name,
                            'fields' => $fields
                        ];
                    }

                    return [
                        'handle' => $form->handle,
                        'tabs' => $tabs
                    ];
                },
            ];
        }
    ]
];
```

**Comment by daltonrooney** [comment]
Got it - that's so simple, thanks!
