### ISSUE TITLE
Invisible reCAPTCHA takes over the form submit behavior

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-forms#448]
Review how the javascript could be extended here. In the case where the user wants to handle the submit form behavior, it would be nice if they could disable the reCAPTCHA submit behavior and use their own.

Conversation in Craft Discord: https://discordapp.com/channels/456442477667418113/456442867163070466/690231643935473771

**Comment by thisisjamessmith** [comment]
To clarify further, this issue prevents us from doing ajax submissions when recaptcha is on, because it creates a race condition where Sprout's JS is firing at the same time as our own (as they both rely on the form's `submit` event).

**Comment by BenParizek** [comment]
@thisisjamessmith Sprout Forms v3.9.0 adds native support for AJAX submissions (`Forms->[Form Name]->Settings->Templates`) improves the JS workflow around the form submission for standard and AJAX form submissions. We have also added several [Javascript Events](https://sprout.barrelstrengthdesign.com/docs/forms/javascript-events.html#beforesproutformssubmit) that can be used to extend the default functionality more easily.

The Invisible reCAPTCHA has been refactored to watch the new `onSproutFormsSubmit` event and hands back responsibility to complete the form submission after it completes its validation. 

Let me know if you have any additional feedback.
