### ISSUE TITLE
FR: Custom confirmation message per form

### ISSUE THREAD

**Issue by daltonrooney** [barrelstrength/craft-sprout-forms#449]
### The problem (description, use case, screenshots...)

There's an option to redirect to a thank you page after a user submits a form. But when submitting via AJAX, we'd rather show an inline confirmation message than redirect the page. 

### The solution (that feature you'd like to see)

Ideally this would be a WYSIWYG field in the general form settings that could contain variables based on the form submission. It would be amazing if it could then be returned as part of a JSON response after successfully posting to /actions/sprout-forms/entries/save-entry (with the interpolated variables). 

### Alternatives you've considered

I've created an invisible field called "confirmation" and am using the instructions field to hold the success message, but this feels like a kluge and I'd rather have it be part of the form settings.

**Comment by BenParizek** [comment]
@daltonrooney I'll bump this up on our list. Before our settings were on separate pages there was no easy way to add this to the interface. Now, we should have the room to make this happen.

**Comment by BenParizek** [comment]
Related: https://github.com/barrelstrength/craft-sprout-forms/issues/269

**Comment by BenParizek** [comment]
@daltonrooney Success and Error Message settings have been added in Sprout Forms v3.9.0. They can include variables from the submission and then render as Markdown.

Please see the [Upgrade Notes](https://sprout.barrelstrengthdesign.com/docs/forms/installing-and-updating-craft-3.html#upgrading-to-forms-v3-9-0) in the docs if you want to add support to existing templates.  Forms using the default form templates should work out of the box.

Thanks for the clear feature request.
