### ISSUE TITLE
Entries marked as spam even when Captchas are turned off for specific form

### ISSUE THREAD

**Issue by daltonrooney** [barrelstrength/craft-sprout-forms#450]
### Description (screenshots, logs, ...)

I have **Duplicate Submission Captcha** and **Javascript Captcha** enabled globally, but **Enable Captchas** turned off for a specific form. Form entries are being marked as spam anyway, having triggered both Captchas. These entries are being submitted via Javascript to /actions/sprout-forms/entries/save-entry, so the Javascript Captcha is even more mysterious.

### Additional info

- Craft version: 3.4.9
- PHP version: 7.3.14
- Database driver & version:  MySQL 5.7.29
- Plugins & versions: Sprout Forms 3.8.5

**Comment by BenParizek** [comment]
@daltonrooney I'll be digging into this shortly. Something seems to be up here but there are a few moving parts that are making it hard for me to pin down. I'll update this thread when I have more.

**Comment by thisisjamessmith** [comment]
Seeing the same problem with Google ReCAPTCHA enabled globally but disabled on a particular form.

**Comment by BenParizek** [comment]
@daltonrooney Just to note, regarding the Javascript captcha, it looks like you may be on a version of Sprout Forms just before we fixed a bug with that Captcha in (v3.8.6).

**Comment by daltonrooney** [comment]
@BenParizek You're right, I updated to the latest and now the Javascript Captcha is not being triggered. The Duplicate Submission Captcha is still catching entries even when disabled for the form, but I've disabled that globally for now.

**Comment by daltonrooney** [comment]
Just tested with the latest version and it looks like captchas are disabled per-form as expected. Thanks!

**Comment by BenParizek** [comment]
This ticket relates to a couple scenarios. I'm closing this out as I believe we've address these scenarios in the latest releases. If you are still running into any issues, please open a new ticket with details around that specific issue.
