### ISSUE TITLE
Custom notification email - style problem

### ISSUE THREAD

**Issue by SamLNL** [barrelstrength/craft-sprout-forms#453]
### Description (screenshots, logs, ...)
Since `update 7.1.1.1` I'm having problems sending notifications with my custom email templates. After some debugging, I noticed the problem; the css in the custom email template.

It looks like some style linter is checking the custom email template when sending a notification.
After uncommenting a lot of css, I received my expected notification.

**Some style that's causing a problem:**

```
.ExternalClass, .ExternalClass p, .ExternalClass td, .ExternalClass div, .ExternalClass span, .ExternalClass font {
  line-height: 100%;
}

table {
  mso-table-lspace: 0;
  mso-table-rspace: 0;
}
```

**Some style that's causing no problems:**
```
p, a, li, td, body, table, blockquote {
  -ms-text-size-adjust: 100%;
  -webkit-text-size-adjust: 100%;
}

a[x-apple-data-detectors] {
  color: inherit !important;
  text-decoration: none !important;
  font-size: inherit !important;
  font-family: inherit !important;
  font-weight: inherit !important;
  line-height: inherit !important;
}
```

Full email template: 
[email.twig.zip](https://github.com/barrelstrength/craft-sprout-forms/files/4375360/email.twig.zip)

Is there any sort of style linter that is causing my notifications to fail?

### Additional info
Craft version: 3.4.10.1
PHP version: 7.1.33
Database driver & version: MySQL 5.7.24
Plugins & versions: Sprout Forms 3.8.8

**Comment by MisterMike** [comment]
I have the same issue. I have tried several email templates. None worked really until I removed the styles section.

**Comment by BenParizek** [comment]
Hi Folks. I'll be looking into this as soon as I have a chance this week.

**Comment by BenParizek** [comment]
@SamLNL @MisterMike We've just released v3.9.x that updates how Email Templates are processed. In my tests, styles are working so please let me know if you continue to run into any issues. 

This update also makes the Email Template API more flexible and with Custom Templates you can now use `{% extends %}` or `{% include %}` anywhere within the top-level /templates folder.

**Comment by MisterMike** [comment]
Thank you so much Ben, the template I intended to use (based on Cerberus) now works! Cheers:)

**Comment by SamLNL** [comment]
Works! Thanks @BenParizek
