### ISSUE TITLE
Internal Server Error for Notifications

### ISSUE THREAD

**Issue by jonlongnecker** [barrelstrength/craft-sprout-forms#462]
### Description (screenshots, logs, ...)
Recently my notifications stopped working, and users are redirected to page that says "Internal Server Error" after submitting a form. I haven't changed anything, so I don't understand why this is happening now.

I get the same internal server error if I try to preview the notification through the control panel.

The form does go through, and the email notification does come through, but all my potential clients think my website is broken which very bad for business.

This is from the log:

````
2020-04-20 15:00:16 [-][1][lquslod6d61ap4urb0lve6jb68][error][TypeError] TypeError: Argument 1 passed to craft\web\View::renderTemplate() must be of the type string, null given, called in /home/forge/site.com/vendor/barrelstrength/sprout-base-email/src/base/EmailTemplates.php on line 145 and defined in /home/forge/site.com/vendor/craftcms/cms/src/web/View.php:376
Stack trace:
#0 /home/forge/site.com/vendor/barrelstrength/sprout-base-email/src/base/EmailTemplates.php(145): craft\web\View->renderTemplate(NULL, Array)
#1 /home/forge/site.com/vendor/barrelstrength/sprout-base-email/src/base/EmailTemplates.php(101): barrelstrength\sproutbaseemail\base\EmailTemplates->processEmailTemplates()
#2 /home/forge/site.com/vendor/barrelstrength/sprout-base-email/src/services/NotificationEmails.php(186): barrelstrength\sproutbaseemail\base\EmailTemplates->getTextBody()
#3 /home/forge/site.com/vendor/barrelstrength/sprout-base-email/src/services/NotificationEmails.php(170): barrelstrength\sproutbaseemail\services\NotificationEmails->showPreviewEmail(Object(barrelstrength\sproutbaseemail\elements\NotificationEmail), 'txt')
#4 /home/forge/site.com/vendor/barrelstrength/sprout-base-email/src/controllers/NotificationsController.php(592): barrelstrength\sproutbaseemail\services\NotificationEmails->getPreviewNotificationEmailById('10868', 'text')
#5 [internal function]: barrelstrength\sproutbaseemail\controllers\NotificationsController->actionViewSharedNotificationEmail('10868', 'text')
#6 /home/forge/site.com/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#7 /home/forge/site.com/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#8 /home/forge/site.com/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('view-shared-not...', Array)
#9 /home/forge/site.com/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('view-shared-not...', Array)
#10 /home/forge/site.com/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('sprout-base-ema...', Array)
#11 /home/forge/site.com/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('sprout-base-ema...', Array)
#12 /home/forge/site.com/vendor/craftcms/cms/src/web/Application.php(276): yii\web\Application->handleRequest(Object(craft\web\Request))
#13 /home/forge/site.com/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#14 /home/forge/site.com/public/index.php(21): yii\base\Application->run()
#15 {main}
````

### Additional info

- Craft version: 3.4.15
- PHP version: 7.3.5 
- Sprout version: 3.9.0.1

**Comment by BenParizek** [comment]
@jonlongnecker 

I believe I found the issue here and need to get through a few other bugs before I can get it released.

If you'd like to test the fix, you can edit the Custom Template class in the `barrelstrength/sprout-base-email` module and update the `getTemplateRoot()` method to the following:

https://github.com/barrelstrength/craft-sprout-base-email/blob/v1/src/emailtemplates/CustomTemplates.php#L39

```
public function getTemplateRoot(): string
{
    return Craft::$app->path->getSiteTemplatesPath();
}
```

**Comment by jonlongnecker** [comment]
@BenParizek I just made this change, but I'm still getting the same Internal Server Error on form submit. I edited `vendor/barrelstrength/sprout-base-email/src/emailtemplates/CustomTemplates.php`

**Comment by BenParizek** [comment]
@jonlongnecker Ok. I'll dig into this more as soon as I can. I understand it's pressing.

As a not-ideal short-term workaround, if you happen to be using Custom Templates, you may be able to switch back to the Basic Templates for a simpler email. I realize my first answer assumed you might be using Custom Templates as we recently had a bug around those. 

Another thing to consider, that could contribute to an error in the template is that our most recently release changed how the root path works with Email Templates. Previously, you identified an Email Folder and the only templates available were those templates within that folder. In the latest update, we now treat the /templates folder as the root folder and your Email Template is just a folder somewhere within that. 

If you happen to be using any `include`, `extends`, or `import` tags in email templates, you may want to check if they are resolving correctly now.  I will add a better example to the docs around this update.

For example, say you have this folder structure:

```
templates/_emails/newsletter/_layout.twig
templates/_emails/newsletter/email.twig
```

If you previously had an email in a `_emails/newsletter` folder that extended a layout within that folder you would treat the email folder as the root: `{% extends "_layout" %}`:

However, after the recent updates the `templates` folder is treated as the root so you'd need to: `{% extends "_emails/newsletter/_layout" %}`.

**Comment by jonlongnecker** [comment]
Hey @BenParizek thanks for the detailed explanation. Unfortunately I'm not using custom templates for my email notifications (just the `Basic Notification (Sprout Forms)`). 

However, when I went to look at my notifications to make sure I wasn't using any custom templates I found 3 similar email notifications. I only created one so I'm not sure why there were extra ones in there. Once I deleted those extra notifications, things seem to be working again. They must have been conflicting with each other.

I'm really confused as to how those other notifications got created, though...

**Comment by BenParizek** [comment]
@jonlongnecker Glad you got it solved. I'll explore whether we might be doing something funny in the template selection logic.

The unidentified Notification template question sounds like a question for your Git History!

**Comment by jonlongnecker** [comment]
@BenParizek They weren't notification templates, just additional notifications. Like if I went to Forms > Notifications they were in that table. Almost like they got created on form submits or something. No git history unfortunately!

**Comment by BenParizek** [comment]
I believe this is resolved so I'm closing this out. Please re-open if any mysteries persist.
