### ISSUE TITLE
Failed to upgrade sprout form from 3.8.8 to 3.9.0.1.

### ISSUE THREAD

**Issue by caroldq55** [barrelstrength/craft-sprout-forms#463]
### Description (screenshots, logs, ...)

We would like to upgrade sprout from to 3.9.0.1 which is used in our craft CMS, but when I tried it on my local I can't have access to our cms admin page anymore.

I have tried `composer install` inside container, docker down and up but didn't work.

Here is the screenshot and error message:

<img width="1158" alt="Screen Shot 2020-04-22 at 12 14 48 pm" src="https://user-images.githubusercontent.com/44183456/79938765-d0be7d00-84a0-11ea-8df7-5c38a0da1404.png">

```
Status: OK

Response: > update in {{%sproutformscontent_healthcareprofessionalregistration}} ... done (time: 0.001s)
> update in {{%sproutformscontent_healthcareprofessionalregistration}} ... done (time: 0.003s)
> update in {{%sproutformscontent_healthcareprofessionalregistration}} ... done (time: 0.002s)
> update in {{%sproutformscontent_healthcareprofessionalregistration}} ... done (time: 0.001s)
> update in {{%sproutformscontent_healthcareprofessionalregistration}} ... done (time: 0.006s)
> update in {{%sproutformscontent_healthcareprofessionalregistration}} ... done (time: 0.001s)
> update in {{%sproutformscontent_healthcareprofessionalregistration}} ... done (time: 0.001s)
{"error":"One of Sprout Forms’s migrations failed.","errorDetails":"Database Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'swisse_craft.sproutemail_campaignemails' doesn't exist\nThe SQL being executed was: ALTER TABLE sproutemail_campaignemails ADD listSettings varchar(255) AFTER recipients\n\nMigration: barrelstrength\\sproutforms\\migrations\\m180314_161540_craft2_to_craft3\n\nOutput:\n\n > add column listSettings string AFTER recipients to table {{%sproutemail_campaignemails}} ...Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'swisse_craft.sproutemail_campaignemails' doesn't exist\nThe SQL being executed was: ALTER TABLE sproutemail_campaignemails ADD listSettings varchar(255) AFTER recipients (/var/www/html/vendor/yiisoft/yii2/db/Schema.php:674)\n#0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1298): yii\\db\\Schema->convertException(Object(PDOException), 'ALTER TABLE sp...')\n#1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1093): yii\\db\\Command->internalExecute('ALTER TABLE sp...')\n#2 /var/www/html/vendor/yiisoft/yii2/db/Migration.php(377): yii\\db\\Command->execute()\n#3 /var/www/html/vendor/barrelstrength/sprout-base-email/src/migrations/m181128_000000_add_list_settings_column.php(28): yii\\db\\Migration->addColumn('{{%sproutemail_...', 'listSettings', Object(craft\\db\\mysql\\ColumnSchemaBuilder))\n#4 /var/www/html/vendor/barrelstrength/sprout-forms/src/migrations/m180314_161540_craft2_to_craft3.php(142): barrelstrength\\sproutbaseemail\\migrations\\m181128_000000_add_list_settings_column->safeUp()\n#5 /var/www/html/vendor/craftcms/cms/src/db/Migration.php(52): barrelstrength\\sproutforms\\migrations\\m180314_161540_craft2_to_craft3->safeUp()\n#6 /var/www/html/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\\db\\Migration->up(true)\n#7 /var/www/html/vendor/craftcms/cms/src/db/MigrationManager.php(153): craft\\db\\MigrationManager->migrateUp(Object(barrelstrength\\sproutforms\\migrations\\m180314_161540_craft2_to_craft3))\n#8 /var/www/html/vendor/craftcms/cms/src/services/Updates.php(233): craft\\db\\MigrationManager->up()\n#9 /var/www/html/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(510): craft\\services\\Updates->runMigrations(Array)\n#10 /var/www/html/vendor/craftcms/cms/src/controllers/UpdaterController.php(203): craft\\controllers\\BaseUpdaterController->runMigrations(Array, 'restore-db')\n#11 [internal function]: craft\\controllers\\UpdaterController->actionMigrate()\n#12 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)\n#13 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(157): yii\\base\\InlineAction->runWithParams(Array)\n#14 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(178): yii\\base\\Controller->runAction('migrate', Array)\n#15 /var/www/html/vendor/yiisoft/yii2/base/Module.php(528): craft\\web\\Controller->runAction('migrate', Array)\n#16 /var/www/html/vendor/craftcms/cms/src/web/Application.php(291): yii\\base\\Module->runAction('updater/migrate', Array)\n#17 /var/www/html/vendor/craftcms/cms/src/web/Application.php(646): craft\\web\\Application->runAction('updater/migrate')\n#18 /var/www/html/vendor/craftcms/cms/src/web/Application.php(243): craft\\web\\Application->_processUpdateLogic(Object(craft\\web\\Request))\n#19 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): craft\\web\\Application->handleRequest(Object(craft\\web\\Request))\n#20 /var/www/html/web/index.php(33): yii\\base\\Application->run()\n#21 {main}\n","options":[{"label":"Restore database","nextAction":"restore-db","status":"Restoring database…"},{"label":"Troubleshoot","url":"https://craftcms.com/guides/failed-updates"},{"label":"Send for help","email":"support@craftcms.com","subject":"Sprout Forms update failure"}],"data":"feb5b1155ce03e3eee75838df970831a4a6b8a73a5b7807bd66e7803600a73bf{\"migrate\":[\"sprout-forms\"],\"returnUrl\":\"\",\"postPrecheckState\":{\"nextAction\":\"backup\",\"status\":\"Backing-up database…\"},\"dbBackupPath\":\"/var/www/html/storage/backups/swisse-au_200422_035313_b3xmbrcqkg_v3.4.13.sql\"}"}
```

### Additional info

- Craft version: 3.4.13
- PHP version: 7.4
- Database driver & version:  MySQL 5.7.27
- Sprout Form (currently): 3.8.8

**Comment by BenParizek** [comment]
@caroldq55 The migration that appears to be filing is `m180314_161540_craft2_to_craft3` which should only be running when migrating from Craft 2 to Craft 3.

You mention that you are currently upgrading from 3.8.8 to 3.9.0.1. Can you share a bit more about when and how you migrated from Craft 2 to Craft 3? Did you upgrade Sprout Forms to the latest version before upgrading to Craft 3? Is there any chance you deleted any migrations from the craft_migrations table? While we can troubleshoot this issue if the plugin wasn't updated to the latest on Craft 2 we may run into other issues after this.

That said, it also appears we can improve the logic of the migration causing an issue and check to confirm that table exists before attempting to add the column which is throwing the error.

I can get this into the next release but it may be a few days. If you want to test out this fix, you can edit the migration that exists in `vendor/barrelstrength/sprout-base-email/src/migrations/m181128_000000_add_list_settings_column` and try to rerun things. Again, I don't know if this will solve the deeper question of why this migration is even running during your current upgrade, which could still have other implications.

OLD:

```
$table = '{{%sproutemail_campaignemails}}';

if (!$this->db->columnExists($table, 'listSettings')) {
    $this->addColumn($table, 'listSettings', $this->string()->after('recipients'));
}
```

NEW
```
$table = '{{%sproutemail_campaignemails}}';

if ($this->db->tableExists($table) && !$this->db->columnExists($table, 'listSettings')) {
    $this->addColumn($table, 'listSettings', $this->string()->after('recipients'));
}
```

**Comment by caroldq55** [comment]
> @caroldq55 The migration that appears to be filing is `m180314_161540_craft2_to_craft3` which should only be running when migrating from Craft 2 to Craft 3.
> 
> You mention that you are currently upgrading from 3.8.8 to 3.9.0.1. Can you share a bit more about when and how you migrated from Craft 2 to Craft 3? Did you upgrade Sprout Forms to the latest version before upgrading to Craft 3? Is there any chance you deleted any migrations from the craft_migrations table? While we can troubleshoot this issue if the plugin wasn't updated to the latest on Craft 2 we may run into other issues after this.
> 
> That said, it also appears we can improve the logic of the migration causing an issue and check to confirm that table exists before attempting to add the column which is throwing the error.
> 
> I can get this into the next release but it may be a few days. If you want to test out this fix, you can edit the migration that exists in `vendor/barrelstrength/sprout-base-email/src/migrations/m181128_000000_add_list_settings_column` and try to rerun things. Again, I don't know if this will solve the deeper question of why this migration is even running during your current upgrade, which could still have other implications.
> 
> OLD:
> 
> ```
> $table = '{{%sproutemail_campaignemails}}';
> 
> if (!$this->db->columnExists($table, 'listSettings')) {
>     $this->addColumn($table, 'listSettings', $this->string()->after('recipients'));
> }
> ```
> 
> NEW
> 
> ```
> $table = '{{%sproutemail_campaignemails}}';
> 
> if ($this->db->tableExists($table) && !$this->db->columnExists($table, 'listSettings')) {
>     $this->addColumn($table, 'listSettings', $this->string()->after('recipients'));
> }
> ```

Thanks sooo much, it works 🎉!

**Comment by BenParizek** [comment]
This update has been added to the latest release v3.10.0
