### ISSUE TITLE
Can't open notifications in latest update

### ISSUE THREAD

**Issue by jaydensmith** [barrelstrength/craft-sprout-forms#464]
### Description (screenshots, logs, ...)
Hey @BenParizek, there's an issue in the latest update that causes an error when opening a notification if you don't have the `barrelstrength/sprout-sent-email` plugin installed.

I've been able to reproduce on two sites today, one was an old Craft 2 site that was updated to Craft 3 some time ago, the other was built on Craft 3.

```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'northerntasmania_craft.sprout_settings' doesn't exist
The SQL being executed was: SELECT `settings`
FROM `sprout_settings`
WHERE `model`='barrelstrength\\sproutbaseemail\\models\\Settings'
LIMIT 1
```

**Comment by BenParizek** [comment]
@jaydensmith Thanks for reporting. I've just released v3.10.0.1 which should resolve this issue.
