### ISSUE TITLE
'-' character doesn't work in regular expressions for Regular Expression field.

### ISSUE THREAD

**Issue by mrunkel** [barrelstrength/craft-sprout-forms#465]
I'm trying to use the following regex `[\d,\-,\(,\),\s]*` with the Regular Expression field and I couldn't get the field to accept `-` as an acceptable character.

After much head scratching, testing, etc.  I decided to do some spelunking and I found https://github.com/barrelstrength/craft-sprout-forms/blob/ff7dc6da2b3c28f4a5661ac177e16c4f887ad4aa/src/fields/formfields/RegularExpression.php#L137

I'm not sure what exactly the intent was with that code, because the comment references HTML5, but HTML5 pattern attributes use JavaScript and `-` definitely needs to be escaped in order to use `-` as a literal.   If you look at the supplied escapeRegExp function at:  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#Escaping you will see that they escape `-` as well.

If I uncomment that line, my regex of course works.

**Comment by BenParizek** [comment]
Thanks @mrunkel. I'll review your PR and let you know when we have a fix out.

**Comment by BenParizek** [comment]
@mrunkel This update has been included in Sprout Forms v3.11.4

**Comment by mrunkel** [comment]
Thanks @BenParizek .
