### ISSUE TITLE
Email Preview 404

### ISSUE THREAD

**Issue by jaydensmith** [barrelstrength/craft-sprout-forms#469]
Email preview button loads a 404.

**Comment by BenParizek** [comment]
Thanks @jaydensmith.

We'll have a fix out shortly. If you need to correct things before we do, see this commit: https://github.com/barrelstrength/craft-sprout-forms/commit/a895ba05be43f6b23c8a9c2ce7dbfaaefbbaa3c3

**Comment by BenParizek** [comment]
This is resolved in release v3.11.3
