### ISSUE TITLE
Unable to save Custom Template Folders

### ISSUE THREAD

**Issue by riusi88** [barrelstrength/craft-sprout-forms#474]
After recently updating Sprout Forms, we are unable to save Custom Template Folders for our Notifications. The update seems to have also removed all of our saved Custom Template Folders across all our Notifications, preventing any emails from being sent out and causing an Internal Server error upon form submission.  

### Steps to reproduce

1. Create or Select a Notification
2. Attempt to save Custom Template Folder
3. Custom Template is not saved and the Templates field is reset to "Basic Notification"

### Additional info

- Craft version: Craft Pro 3.4.18
- PHP version: 7.1.33
- Plugins:
`    "aelvan/imager": "v2.4.0",
    "anubarak/craft-relabel": "1.3.5.1",
    "barrelstrength/sprout-email": "4.4.0",
    "barrelstrength/sprout-fields": "3.8.0",
    "barrelstrength/sprout-forms": "3.11.3",
    "barrelstrength/sprout-forms-google-recaptcha": "1.3.0",
    "bymayo/pdf-transform": "1.0.2",
    "craftcms/cms": "3.4.18",
    "craftcms/contact-form": "2.2.7",
    "craftcms/contact-form-honeypot": "1.0.2",
    "craftcms/feed-me": "4.2.2",
    "craftcms/redactor": "2.6.1",
    "craftconditions/conditions": "1.0.3",
    "dolphiq/jsonclient": "1.0.3",
    "fruitstudios/linkit": "1.1.11",
    "fruitstudios/searchit": "1.0.8",
    "matt-west/craft-recaptcha": "1.4.0",
    "nystudio107/craft-cookies": "1.1.12",
    "nystudio107/craft-retour": "3.1.37",
    "nystudio107/craft-seomatic": "3.3.2",
    "pennebaker/craft-architect": "2.3.3",
    "rias/craft-contact-form-extensions": "1.2.0",
    "spicyweb/craft-fieldlabels": "1.1.10",
    "spicyweb/craft-neo": "2.7.10",
    "supercool/tablemaker": "2.0.1",
    "verbb/field-manager": "2.1.5",
    "verbb/navigation": "1.3.14",
    "vlucas/phpdotenv": "^3.4.0"
`

Error:

After submitting a form, it triggers this Internal server error:

`TypeError: Argument 1 passed to craft\web\View::renderObjectTemplate() must be of the type string, null given, called in /.../craft3/vendor/barrelstrength/sprout-base-email/src/base/Mailer.php on line 186 and defined in /.../craft3/vendor/craftcms/cms/src/web/View.php:584
Stack trace:
#0 /.../craft3/vendor/barrelstrength/sprout-base-email/src/base/Mailer.php(186): craft\web\View->renderObjectTemplate(NULL, Object(barrelstrength\sproutforms\elements\Entry))
#1 /.../craft3/vendor/barrelstrength/sprout-base-email/src/base/Mailer.php(137): barrelstrength\sproutbaseemail\base\Mailer->renderObjectTemplateSafely(Object(barrelstrength\sproutbaseemail\elements\NotificationEmail), 'defaultBody', Object(barrelstrength\sproutforms\elements\Entry))
#2 /.../craft3/vendor/barrelstrength/sprout-base-email/src/mailers/DefaultMailer.php(105): barrelstrength\sproutbaseemail\base\Mailer->getMessage(Object(barrelstrength\sproutbaseemail\elements\NotificationEmail))
#3 /.../craft3/vendor/barrelstrength/sprout-base-email/src/services/NotificationEmails.php(115): barrelstrength\sproutbaseemail\mailers\DefaultMailer->sendNotificationEmail(Object(barrelstrength\sproutbaseemail\elements\NotificationEmail))
#4 /.../craft3/vendor/barrelstrength/sprout-base-email/src/services/NotificationEmailEvents.php(227): barrelstrength\sproutbaseemail\services\NotificationEmails->sendNotificationViaMailer(Object(barrelstrength\sproutbaseemail\elements\NotificationEmail))
#5 /.../craft3/vendor/barrelstrength/sprout-base-email/src/services/NotificationEmailEvents.php(153): barrelstrength\sproutbaseemail\services\NotificationEmailEvents->handleDynamicEvent('barrelstrength\\...', Object(barrelstrength\sproutforms\events\OnSaveEntryEvent), Object(barrelstrength\sproutforms\integrations\sproutemail\events\notificationevents\SaveEntryEvent))
#6 [internal function]: barrelstrength\sproutbaseemail\services\NotificationEmailEvents::barrelstrength\sproutbaseemail\services\{closure}('barrelstrength\\...', Object(barrelstrength\sproutforms\events\OnSaveEntryEvent), Object(barrelstrength\sproutforms\integrations\sproutemail\events\notificationevents\SaveEntryEvent))
#7 /.../craft3/vendor/barrelstrength/sprout-base-email/src/services/NotificationEmailEvents.php(123): call_user_func(Object(Closure), 'barrelstrength\\...', Object(barrelstrength\sproutforms\events\OnSaveEntryEvent), Object(barrelstrength\sproutforms\integrations\sproutemail\events\notificationevents\SaveEntryEvent))
#8 [internal function]: barrelstrength\sproutbaseemail\services\NotificationEmailEvents::barrelstrength\sproutbaseemail\services\{closure}(Object(barrelstrength\sproutforms\events\OnSaveEntryEvent))
#9 /.../craft3/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(barrelstrength\sproutforms\events\OnSaveEntryEvent))
#10 /.../craft3/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('barrelstrength\\...', 'afterSave', Object(barrelstrength\sproutforms\events\OnSaveEntryEvent))
#11 /.../craft3/vendor/barrelstrength/sprout-forms/src/services/Entries.php(294): yii\base\Component->trigger('afterSave', Object(barrelstrength\sproutforms\events\OnSaveEntryEvent))
#12 /.../craft3/vendor/barrelstrength/sprout-forms/src/services/Entries.php(177): barrelstrength\sproutforms\services\Entries->callOnSaveEntryEvent(Object(barrelstrength\sproutforms\elements\Entry), true)
#13 /.../craft3/vendor/barrelstrength/sprout-forms/src/controllers/EntriesController.php(251): barrelstrength\sproutforms\services\Entries->saveEntry(Object(barrelstrength\sproutforms\elements\Entry))
#14 [internal function]: barrelstrength\sproutforms\controllers\EntriesController->actionSaveEntry()
#15 /.../craft3/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#16 /.../craft3/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#17 /.../craft3/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('save-entry', Array)
#18 /.../craft3/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-entry', Array)
#19 /.../craft3/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('sprout-forms/en...', Array)
#20 /.../craft3/vendor/craftcms/cms/src/web/Application.php(559): craft\web\Application->runAction('sprout-forms/en...', Array)
#21 /.../craft3/vendor/craftcms/cms/src/web/Application.php(270): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#22 /.../craft3/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#23 /.../craft3/web/index.php(42): yii\base\Application->run()
#24 {main}
`

**Comment by riusi88** [comment]
It may also be related but a 404 error also occurs when previewing a notification:

`yii\web\NotFoundHttpException: Template not found: sprout-email/notifications/preview/181944 in /.../craft3/vendor/craftcms/cms/src/controllers/TemplatesController.php:90
Stack trace:
#0 [internal function]: craft\controllers\TemplatesController->actionRender('sprout-email/no...', Array)
#1 /.../craft3/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#2 /.../craft3/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#3 /.../craft3/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('render', Array)
#4 /.../craft3/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#5 /.../craft3/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('templates/rende...', Array)
#6 /.../craft3/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#7 /.../craft3/vendor/craftcms/cms/src/web/Application.php(276): yii\web\Application->handleRequest(Object(craft\web\Request))
#8 /.../craft3/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#9 /.../craft3/web/index.php(42): yii\base\Application->run()
#10 {main}`

**Comment by riusi88** [comment]
@tplassman submitted an issue that may be the root problem:
https://github.com/barrelstrength/craft-sprout-base-email/issues/3

**Comment by BenParizek** [comment]
Thanks @riusi88. I'm catching up on a few issues and will look into this as soon as I can.

**Comment by garycrane** [comment]
+1 with this issue. Can't seem to select a custom template in the email notification.

Craft CMS 3.4.19.1
PHP 7.2.30
MySQL 5.6.47

**Comment by BenParizek** [comment]
@riusi88 @garycrane There are two things going on here:

1. The Email Template setting saving issue has been resolved in the latest release
2. There was a bug in an earlier migration that could overwrite any shared settings between Sprout plugins. The only way to fix this if you need to preserve the settings you had before would be to roll back and re-run the update

If you need to review what the settings are, we are currently using a different method to save settings that Craft does with the Project Config. The Sprout Settings would be in the `craft_sprout_settings` and the below SQL statement reflects what they should roughly look like for Sprout Forms (they are email and report related, as Sprout Forms shares email and report functionality with other Sprout plugins)

```
INSERT INTO `craft_sprout_settings` (`id`, `model`, `settings`, `dateCreated`, `dateUpdated`, `uid`) VALUES
('1', 'barrelstrength\\sproutbasereports\\models\\Settings', '{\"pluginNameOverride\":\"\",\"defaultPageLength\":\"50\",\"defaultExportDelimiter\":\";\"}', '2019-08-31 20:08:13', '2020-05-16 16:19:34', 'baa4d16d-32e5-43d1-8135-278e14cbc2ea'),
('3', 'barrelstrength\\sproutbasesentemail\\models\\Settings', '{\"pluginNameOverride\":\"\",\"enableSentEmails\":\"1\",\"sentEmailsLimit\":\"5000\",\"cleanupProbability\":\"1000\"}', '2020-05-16 15:29:27', '2020-05-16 16:16:42', '37ef68ad-9f77-41dd-a3ce-013bec6b1b65'),
('4', 'barrelstrength\\sproutbaseemail\\models\\Settings', '{\"pluginNameOverride\":\"\",\"enableNotificationEmails\":\"1\",\"emailTemplateId\":\"\",\"enablePerEmailEmailTemplateIdOverride\":\"\"}', '2020-05-16 15:29:27', '2020-05-16 16:06:09', 'eac7828c-c42a-4f7a-b705-10e2d3329103');
```

_Note: For reasons I won't go into here, we currently manage some settings in this non-standard way (as the default way doesn't solve all the needs for our particular plugin use-case with some shared features between plugins). I recognize that this abstraction has caused more problems than are ideal and we're currently exploring ways to update the way settings are handled in our plugins to figure out how we can solve these issue and get things working in a more Craft-native way._

**Comment by garycrane** [comment]
Working for me now. Thanks for the update.
