### ISSUE TITLE
Support for form asset upload to DigitalOcean Spaces

### ISSUE THREAD

**Issue by j-greig** [barrelstrength/craft-sprout-forms#478]
Just wondering if this is possible?

If not will just use S3 - just finding the initial fixed price tier of Spaces quite appealing for my next project : )

**Comment by BenParizek** [comment]
@j-greig I haven't tried, but theoretically possible. Sprout Forms' File Upload field is just a wrapper around Craft's Asset fields and will upload things wherever Craft's Asset Volumes tell it to upload things.

While DO Spaces isn't supported by default, Craft does support custom volume types and there is a plugin that appears to integrate Craft with DO spaces:
https://plugins.craftcms.com/dospaces

To give it a go, install that plugin, configure whatever volume you are using to point to DO spaces, and you should be able to manage any assets in Sprout Forms File Upload fields in DO along with the rest of your assets.

**Comment by j-greig** [comment]
Thanks Ben, it works! 👌
