### ISSUE TITLE
Migration error after updating

### ISSUE THREAD

**Issue by StijnCoolen** [barrelstrength/craft-sprout-forms#480]
### Description (screenshots, logs, ...)

After upgrading sprout-forms (using `composer update barrelstrength/sprout-forms`) running `craft migrate/all` gives the following error: `PHP Fatal Error 'yii\base\ErrorException' with message 'Trait 'barrelstrength\sproutbase\base\BaseSproutTrait' not found'`

### Steps to reproduce

1. Update sprout forms
2. Run migrations

### Additional info

- Craft version: 3.4.15
- PHP version: 7.4.2
- Database driver & version:  MySQL 5.7.29
- Plugins & versions: sprout-forms": "^3.8.8" (base is at 5.2.0)

_For some issues, we may request that you send the following items to Support <sprout@barrelstrengthdesign.com>. If you feel your issue may fall in that category, feel free to send things over after you post this issue and reference the issue in your email._

- `composer.json`
- `storage/logs/web.log` (or a zip of the whole log folder)
- An export of your database (or, if you can't share the whole db, the specific Sprout tables)

**Comment by BenParizek** [comment]
@StijnCoolen It looks like the composer packages are out of sync here.

The latest version of Sprout Forms is v3.11.6 which requires Sprout Base `^6.0.1`. Sprout Base 5.2 is not going to have the class the application is looking for.

Is there some reason you can't update to the latest?

**Comment by StijnCoolen** [comment]
@BenParizek I manually changed Sprout Base to 6.0.1, migration now seems to fail at another point: Exception: Trying to access array offset on value of type null (.../vendor/barrelstrength/sprout-seo/src/migrations/m200420_000000_update_settings_model.php:40)

**Comment by BenParizek** [comment]
@StijnCoolen Is there a reason you don't want to update to the latest for both Forms and SEO? The simplest path here is going to be to update to the latest of both all at once. The latest for Forms is v3.11.6 and SEO is v4.6.1 

Both Forms and SEO will need to be updated together to get upgraded to Sprout Base ^6.x, as that dependency was a major release that both plugins depend on. Updating one or the other at a time should always throw an error, and trying to target certain versions before the latest could potentially pull in the wrong dependencies (the initial error) so if you need to target something that is not the latest release we may need to hard code the versions of all the related dependencies the plugins need to get that to work.

Can you revert to the last working repo and db before the initial migration error and re-run an update making sure to update both plugins at once? (similar to the "Update All" option in the CP). These recent releases made some changes to the structure of the settings which may affect both the db and the project config file so you'll want to make sure those were the same state as before the update when trying to migrate again.

**Comment by StijnCoolen** [comment]
@BenParizek removing the plugins and installing them again both at the same time seems to be the fix.
