### ISSUE TITLE
defaultBody field gets processed when value is null

### ISSUE THREAD

**Issue by nathannerdymind** [barrelstrength/craft-sprout-forms#481]
### Description (screenshots, logs, ...)
After updating to version 4.4.2 all of my notifications have stoped working and they show an Internal Server Error after a user submit a form on the site. They also show the same error when you try to test the notification in the admin panel through the test button. I am using a custom template and I have updated the settings page to match the same setting before the update. I can preview the notification and it pull in the template and shows correctly. Just can not send any notifications. 

### Steps to reproduce

1. Update to version 4.4.2
2. Click the test button to test a notification or submit a form that sends that notification. 

### Additional info

- Craft version: 3.4.20
- PHP version: 7.3
- Database driver & version:  5.7.30
- Plugins & versions:
`aelvan/imager: ^2.1,
    barrelstrength/sprout-email: 4.4.2,
    barrelstrength/sprout-reports: 1.5.3,
    clubstudioltd/craft-asset-rev: ^6.0,
    craftcms/aws-s3: 1.2.8,
    craftcms/cms: 3.4.20,
    craftcms/mailgun: ^1.4,
    craftcms/redactor: 2.6.1,
    doublesecretagency/craft-cpcss: ^2.1,
    doublesecretagency/craft-inventory: ^2.0,
    doublesecretagency/craft-upvote: ^2.0,
    enovatedesign/craft-style-inliner: 2.0.1,
    jalendport/craft-queuemanager: 1.2.0,
    league/csv: ^8.0,
    nystudio107/craft-retour: ^3.1,
    nystudio107/craft-seomatic: 3.3.3,
    olivierbon/craft-concierge: ^2.1,
    page-8/craft-manytomany: 1.0.2.2,
    sebastianlenz/linkfield: ^1.0,
    solspace/craft-freeform: 3.6.8,
    solspace/craft3-calendar: 3.0.3,
    spicyweb/craft-neo: 2.7.10,
    superbig/craft3-bugsnag: ^2.0,
    topshelfcraft/wordsmith: ^3.0,
    trendyminds/isolate: ^1.1,
    verbb/image-resizer: ^2.0,
    verbb/super-table: ^2.1,
    vlucas/phpdotenv: ^2.4.0`

**Comment by BenParizek** [comment]
@nathannerdymind We recently had a migrations bug and it sounds like you got affected by it. It's resolved now but the only way to fix it (aside from manually) would be to go back to the original db you updated from and re-run the update to the latest version of all the sprout plugins.

Here's the discussion of the bug in another thread: 
https://github.com/barrelstrength/craft-sprout-seo/issues/205#issuecomment-630238776

It looks like you have Email and Reports installed so you'll need to restore the following settings tables:

- barrelstrength\sproutbasereports\models\Settings
- barrelstrength\sproutbasesentemail\models\Settings
- barrelstrength\sproutbaseemail\models\Settings

If you're on Craft Discord and would like to talk this through, please ping me at @BenParizek

**Comment by BenParizek** [comment]
This is due to a bug where if you are using a Custom Field Layout for your email Sprout Email still tries to process the `defaultBody` field and if it is set to null in the database, fails.

The short-term workaround is to just set the `defaultBody` column in the db to a string, instead of null, and things will process correctly. We'll get a release out shortly that improves the logic here so that's not necessary.

**Comment by BenParizek** [comment]
This is resolved in Sprout Forms v3.11.8
