### ISSUE TITLE
URL field not validating?

### ISSUE THREAD

**Issue by j-greig** [barrelstrength/craft-sprout-forms#487]
I have a standard URL field that is reporting an invalid URL for any website link.

What could be causing this?

![image](https://user-images.githubusercontent.com/616194/82825018-58354c80-9ea2-11ea-90c4-c5dce52dfead.png)

Thanks!

----

Craft CMS Solo 3.4.20
Sprout Forms Lite 3.11.8

**Comment by BenParizek** [comment]
@j-greig I just tested a URL field locally and am not seeing the same behavior. Can you share more about how you have things setup and output? Are you experiencing this using the default templates output by the `craft.sproutForms.displayForm('formHandle')` tag? Can you share what settings you have in place and what HTML is being output for that Website field?

**Comment by j-greig** [comment]
Hi Ben, yes I'm just using `craft.sproutForms.displayForm` in my template.

(Is there anything else I should be including in terms of JS etc?)

I just deleted the form and made a new one with just a URL field, this is the HTML output:

```
<div id="fields-uRL1-field" class="field url uRL1-field required">
        <div class="heading">
                <label for="fields-uRL1">URL</label>
            </div>
        <div class="input">
            <input type="url" name="fields[uRL1]" id="fields-uRL1" required="" aria-required="true" oninvalid="setCustomValidity('URL\u0020must\u0020be\u0020a\u0020valid\u0020URL.')" oninput="setCustomValidity('')" pattern="" class="">
        </div>
</div>
```

And the field settings

![image](https://user-images.githubusercontent.com/616194/82829492-50c67100-9eab-11ea-8fcc-0fa2a8ebb665.png)

Thanks :)

**Comment by BenParizek** [comment]
@j-greig I can recreate this. It appears the "pattern" setting is being saved as an empty string instead of null, and the code is just checking for null. I will review this and other fields that use the HTML5 pattern behavior and update that logic.

**Comment by BenParizek** [comment]
@j-greig This is resolved in the default Form Templates we provide in v3.12.1.

If you happen to be overriding any templates for the fields URL, Email, Number, and Regular Expression, you'll want to update the logic in those templates as you see in this commit:
https://github.com/barrelstrength/craft-sprout-forms/commit/1cf7e5c79cab5aacac882830428dd3041f50a225
