### ISSUE TITLE
Migration from 3.10 to 3.11.8 fails: dataSourceId column 'sproutreports.users'

### ISSUE THREAD

**Issue by mrunkel** [barrelstrength/craft-sprout-forms#492]
### Description (screenshots, logs, ...)

I've just upgraded all the barrelstrength plugins to their latest versions.  When I try to execute `./craft migrate/all`

I get the following error:

```
root@05a1ca29558d:/var/www/app# ./craft migrate/all
Yii Migration Tool (based on Yii v2.0.35)

Array
(
    [0] => sprout-forms
)
520-1
after init
after obstart
First
Second
Branch-2
    > delete from {{%sproutreports_reports}} ...Exception: SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect DOUBLE value: 'sproutreports.users'
The SQL being executed was: DELETE FROM `sproutreports_reports` WHERE `dataSourceId`='sproutreports.users' (/var/www/app/vendor/yiisoft/yii2/db/Schema.php:674)
#0 /var/www/app/vendor/yiisoft/yii2/db/Command.php(1298): yii\db\Schema->convertException(Object(PDOException), 'DELETE FROM `sp...')
#1 /var/www/app/vendor/yiisoft/yii2/db/Command.php(1093): yii\db\Command->internalExecute('DELETE FROM `sp...')
#2 /var/www/app/vendor/yiisoft/yii2/db/Migration.php(300): yii\db\Command->execute()
#3 /var/www/app/vendor/barrelstrength/sprout-base-reports/src/migrations/m200520_000001_update_user_datasourceid.php(36): yii\db\Migration->delete('{{%sproutreport...', Array)
#4 /var/www/app/vendor/barrelstrength/sprout-forms/src/migrations/m200520_000001_update_user_datasourceid_sproutforms.php(20): barrelstrength\sproutbasereports\migrations\m200520_000001_update_user_datasourceid->safeUp()
#5 /var/www/app/vendor/craftcms/cms/src/db/Migration.php(52): barrelstrength\sproutforms\migrations\m200520_000001_update_user_datasourceid_sproutforms->safeUp()
#6 /var/www/app/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up(true)
#7 /var/www/app/vendor/craftcms/cms/src/db/MigrationManager.php(153): craft\db\MigrationManager->migrateUp(Object(barrelstrength\sproutforms\migrations\m200520_000001_update_user_datasourceid_sproutforms))
#8 /var/www/app/vendor/craftcms/cms/src/services/Updates.php(234): craft\db\MigrationManager->up()
#9 /var/www/app/vendor/craftcms/cms/src/console/controllers/MigrateController.php(259): craft\services\Updates->runMigrations(Array)
#10 [internal function]: craft\console\controllers\MigrateController->actionAll()
#11 /var/www/app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /var/www/app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#13 /var/www/app/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction('all', Array)
#14 /var/www/app/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#15 /var/www/app/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#16 /var/www/app/vendor/craftcms/cms/src/console/Application.php(87): yii\console\Application->runAction('migrate/all', Array)
#17 /var/www/app/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#18 /var/www/app/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#19 /var/www/app/craft(22): yii\base\Application->run()
#20 {main}
Exception 'craft\errors\MigrateException' with message 'An error occurred while migrating Sprout Forms.'

in /var/www/app/vendor/craftcms/cms/src/services/Updates.php:242

Stack trace:
#0 /var/www/app/vendor/craftcms/cms/src/console/controllers/MigrateController.php(259): craft\services\Updates->runMigrations(Array)
#1 [internal function]: craft\console\controllers\MigrateController->actionAll()
#2 /var/www/app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /var/www/app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /var/www/app/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction('all', Array)
#5 /var/www/app/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#6 /var/www/app/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#7 /var/www/app/vendor/craftcms/cms/src/console/Application.php(87): yii\console\Application->runAction('migrate/all', Array)
#8 /var/www/app/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#9 /var/www/app/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#10 /var/www/app/craft(22): yii\base\Application->run()
#11 {main}
root@05a1ca29558d:/var/www/app#
```
Note, there is some additional debugging output in there and I had to disable the `ob_start()` to get this display.

The problem seems to be this line:
```
            $this->delete('{{%sproutreports_reports}}', [
                'dataSourceId' => 'sproutreports.users'
            ]);
```
On my database, dataSourceId is an integer, so I'm pretty sure 'sproutreports.users' isn't the right search clause, or maybe I missed another migration somewhere?  

Prior to this upgrade, we had been running our own fork of the plugin because of the previous issue I filed.

### Additional info

- Craft version: 3.4.20
- PHP version: 7.4.4
- Database driver & version:  MySQL v8.0.19
- Plugins & versions:

_For some issues, we may request that you send the following items to Support <sprout@barrelstrengthdesign.com>. If you feel your issue may fall in that category, feel free to send things over after you post this issue and reference the issue in your email._

- `composer.json`
- `storage/logs/web.log` (or a zip of the whole log folder)
- An export of your database (or, if you can't share the whole db, the specific Sprout tables)

**Comment by BenParizek** [comment]
@mrunkel Not sure how to explain this just yet. I see you're using MySQL 8.0.19. I wonder if it treats certain data type behaviors differently. I did test this on Maria DB. I don't see where a datetime error comes out of the line `DELETE FROM `sproutreports_reports` WHERE `dataSourceId`='sproutreports.users'`.

----

In any case, there was an issue where that `sproutreports.users` value could get added to the `dataSourceId` column and another issue where the `dataSourceId` column could have historically been created using the varchar instead of the integer data type.

The migration throwing the error is trying to clean up the former and the next migration is trying to clean up the latter.

From the error and the code that is executing it seems that you don't appear to have the Users Data Source installed. 

One potential fix would be to go to the Data Sources tab in the old CP and install the Users Data Source and try the migration again. The current migration is not finding the Users Data Source ID from the list of installed data sources and is trying to clean up the issue by deleting the errant User reports because they can't be matched to an existing Data Source Type.

Alternatively, once adding the User Data Source you could manually update those user `dataSourceId` values to use an int of the Data Source ID and that code block should be skipped over.

**Comment by mrunkel** [comment]
I don't have a Data Sources tab? Or maybe I'm just looking in the wrong place? I'm only running the Sprout Forms, I don't have Sprout Reports installed.

Thanks for the quick response.

**Comment by BenParizek** [comment]
@mrunkel Ok. I'm not sure where the source of this came from but you shouldn't even have a reference to the Users Data Source in the Sprout Forms UI. The Data Sources tab doesn't exist in Sprout Forms, nor does the Users Data Source.

Another potential way to fix this may be to manually change the `dataSourceId` values of those `sproutreports.users` rows to an existing Data Source ID associated with the form plugin. That may break the reports (if they were ever intended to be reports) but could make them appear in the UI to delete before running the migration.

If that path doesn't work, I think I may need to ask you to just clean this up manually in the db in the short run. If you're uncomfortable with that, let me know, or hit me up at @BenParizek on Craft Discord and we can hop on a screen share and work through this.

Depending on your comfort level you may want to do that by briefly installing a trial of Sprout Reports getting that User Data Source added so you can delete things from the UI, or by deleting the offending Report rows from the DB directly (probably by identifying their Element IDs and deleting them from the elements table there if they exist, or from the reports table directly if they don't, but be careful down this path if you are not comfortable with doing that).

**Comment by BenParizek** [comment]
@mrunkel A colleague tells me this may be caused from your MySQL being run in strict mode and, since the bug that I'm trying to solve in this migration is to correct a mismatch in data types, that I may need to update this migration to CAST the int value as a varchar so that this error doesn't occur. I'll explore that path today.

**Comment by mrunkel** [comment]
okay, I'll poke around some.  I'm comfortable in making database changes directly.  Just didn't want to tear too much stuff in case you had a quick fix.   This is all on a local dev database, so nothing bad can happen (I can always download the production database again)...

I know that MySQL 8 made several big changes that resulted in a divergence from MariaDB's behavior.  

FYI I have only three `sproutreports_*` tables:
* sproutreports_datasources
* sproutreports_reportgroups
* sproutreports_reports

Except for datasources, they are empty.   datasources consists of:

```
INSERT INTO `sproutreports_datasources` (`id`, `viewContext`, `type`, `allowNew`, `dateCreated`, `dateUpdated`, `uid`) VALUES 
	(1,'sprout-forms','barrelstrength\\sproutforms\\integrations\\sproutreports\\datasources\\EntriesDataSource',1,'2020-03-17 14:36:29','2020-03-17 14:36:29','df125b12-94b8-4c4a-bb61-5dc6d36e905f'),
	(2,'sprout-forms','barrelstrength\\sproutforms\\integrations\\sproutreports\\datasources\\IntegrationLogDataSource',1,'2020-03-17 14:36:29','2020-03-17 14:36:29','5911cd8e-8d2d-457f-ae89-187713d9cd97'),
	(3,'sprout-forms','barrelstrength\\sproutforms\\integrations\\sproutreports\\datasources\\SpamLogDataSource',1,'2020-03-17 14:36:29','2020-03-17 14:36:29','de09c1ef-58ff-4210-ab71-a84ba60c6359');
```

**Comment by BenParizek** [comment]
@mrunkel Interesting. As you don't have any records, it seems this points to the error being entirely one of MySQL trying to resolve conflicting data types. That may suggest your easiest path to resolution in the short run is to simply comment out that code, as it wouldn't be updating any data anyways.

I'll update this once I get a fix out for the migration.

**Comment by vanburenx** [comment]
Seeing a similar issue after trying to upgrade to **v3.12.0** but on **PostgreSQL**. Thanks.

**System Information** 
- PHP version	7.2.31
- OS version	Linux 4.4.0-179-generic
- Database driver & version	PostgreSQL 9.5.21
- Craft edition & version	Craft Solo 3.4.20
- Sprout Forms 3.11.7

**Stack Trace**
```
Database Exception: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "sproutreports.users"
The SQL being executed was: DELETE FROM "craft_sproutreports_reports" WHERE "dataSourceId"='sproutreports.users'

Migration: barrelstrength\sproutforms\migrations\m200520_000001_update_user_datasourceid_sproutforms

Output:

> delete from {{%sproutreports_reports}} ...Exception: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "sproutreports.users"
The SQL being executed was: DELETE FROM "craft_sproutreports_reports" WHERE "dataSourceId"='sproutreports.users' (REPLACE_WITH_PATH/vendor/yiisoft/yii2/db/Schema.php:674)
#0 REPLACE_WITH_PATH/vendor/yiisoft/yii2/db/Command.php(1298): yii\db\Schema->convertException(Object(PDOException), 'DELETE FROM "cr...')
#1 REPLACE_WITH_PATH/vendor/yiisoft/yii2/db/Command.php(1093): yii\db\Command->internalExecute('DELETE FROM "cr...')
#2 REPLACE_WITH_PATH/vendor/yiisoft/yii2/db/Migration.php(300): yii\db\Command->execute()
#3 REPLACE_WITH_PATH/vendor/barrelstrength/sprout-base-reports/src/migrations/m200520_000001_update_user_datasourceid.php(32): yii\db\Migration->delete('{{%sproutreport...', Array)
#4 REPLACE_WITH_PATH/vendor/barrelstrength/sprout-forms/src/migrations/m200520_000001_update_user_datasourceid_sproutforms.php(18): barrelstrength\sproutbasereports\migrations\m200520_000001_update_user_datasourceid->safeUp()
#5 REPLACE_WITH_PATH/vendor/craftcms/cms/src/db/Migration.php(52): barrelstrength\sproutforms\migrations\m200520_000001_update_user_datasourceid_sproutforms->safeUp()
#6 REPLACE_WITH_PATH/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up(true)
#7 REPLACE_WITH_PATH/vendor/craftcms/cms/src/db/MigrationManager.php(153): craft\db\MigrationManager->migrateUp(Object(barrelstrength\sproutforms\migrations\m200520_000001_update_user_datasourceid_sproutforms))
#8 REPLACE_WITH_PATH/vendor/craftcms/cms/src/services/Updates.php(233): craft\db\MigrationManager->up()
#9 REPLACE_WITH_PATH/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(510): craft\services\Updates->runMigrations(Array)
#10 REPLACE_WITH_PATH/vendor/craftcms/cms/src/controllers/UpdaterController.php(203): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#11 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#12 REPLACE_WITH_PATH/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 REPLACE_WITH_PATH/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#14 REPLACE_WITH_PATH/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('migrate', Array)
#15 REPLACE_WITH_PATH/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#16 REPLACE_WITH_PATH/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('updater/migrate', Array)
#17 REPLACE_WITH_PATH/vendor/craftcms/cms/src/web/Application.php(646): craft\web\Application->runAction('updater/migrate')
#18 REPLACE_WITH_PATH/vendor/craftcms/cms/src/web/Application.php(243): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#19 REPLACE_WITH_PATH/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#20 REPLACE_WITH_PATH/web/index.php(21): yii\base\Application->run()
#21 REPLACE_WITH_PATH/.composer/vendor/cpriego/valet-linux/server.php(232): require('REPLACE_WITH_PATH/a...')
#22 {main}
```

**Comment by BenParizek** [comment]
@vanburenx The postgres issue should be resolved in v3.12.1

@mrunkel I believe the MySQL issue is also resolved but please let me know if you run into any more scenarios. I don't feel like I'm testing the exact scenario reported but have attempted to make the code consider the scenario.

**Comment by mklishevych** [comment]
Invalid datetime format: 1292 Truncated incorrect DOUBLE value: 'CAST('sproutreports.users' AS VARCHAR)'

**Comment by BenParizek** [comment]
@mrunkel @vanburenx @mklishevych I've gone ahead and removed this migration from the latest releases, so hopefully, that will put this to rest.

We have a niche case where the data type of a column may be incorrect and, in some cases (probably depending on your database configuration), may have a (probably unused) value that is of the incorrect data type in that column. This migration was trying to solve that, but as it's unlikely that issue will affect many people, we can handle those scenarios on a case by case if they even come up as I'm clearly not sure how to cast the correct data type for all scenarios in this migration.

The data type of the column in question is corrected in a subsequent migration, so I expect, users that are affected, using database configurations that are strict enough to care, will let us know if the issue exists/persists.

**Comment by vanburenx** [comment]
Hey Ben, sorry to be back again but here's the current error after trying to upgrade to **v3.12.2**. 

Thanks again for your patience with this and for creating/supporting this plugin in the first place.

**System Information**

PHP version 7.2.31
OS version Linux 4.4.0-179-generic
Database driver & version PostgreSQL 9.5.21
Craft edition & version Craft Solo 3.4.22.1
Sprout Forms 3.11.7

**Stack Trace**

```
Database Exception: SQLSTATE[25P02]: In failed sql transaction: 7 ERROR: current transaction is aborted, commands ignored until end of transaction block
The SQL being executed was: RELEASE SAVEPOINT LEVEL1

Migration: barrelstrength\sproutforms\migrations\m200520_000003_add_report_element_foreign_key_sproutforms

Output:

Exception: SQLSTATE[25P02]: In failed sql transaction: 7 ERROR: current transaction is aborted, commands ignored until end of transaction block
The SQL being executed was: RELEASE SAVEPOINT LEVEL1 (REPLACE_WITH_PATH/vendor/yiisoft/yii2/db/Schema.php:674)
#0 REPLACE_WITH_PATH/vendor/yiisoft/yii2/db/Command.php(1298): yii\db\Schema->convertException(Object(PDOException), 'RELEASE SAVEPOI...')
#1 REPLACE_WITH_PATH/vendor/yiisoft/yii2/db/Command.php(1093): yii\db\Command->internalExecute('RELEASE SAVEPOI...')
#2 REPLACE_WITH_PATH/vendor/yiisoft/yii2/db/Schema.php(397): yii\db\Command->execute()
#3 REPLACE_WITH_PATH/vendor/craftcms/cms/src/db/pgsql/Schema.php(65): yii\db\Schema->releaseSavepoint('LEVEL1')
#4 REPLACE_WITH_PATH/vendor/yiisoft/yii2/db/Transaction.php(172): craft\db\pgsql\Schema->releaseSavepoint('LEVEL1')
#5 REPLACE_WITH_PATH/vendor/craftcms/cms/src/db/Migration.php(56): yii\db\Transaction->commit()
#6 REPLACE_WITH_PATH/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up(true)
#7 REPLACE_WITH_PATH/vendor/craftcms/cms/src/db/MigrationManager.php(153): craft\db\MigrationManager->migrateUp(Object(barrelstrength\sproutforms\migrations\m200520_000003_add_report_element_foreign_key_sproutforms))
#8 REPLACE_WITH_PATH/vendor/craftcms/cms/src/services/Updates.php(233): craft\db\MigrationManager->up()
#9 REPLACE_WITH_PATH/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(510): craft\services\Updates->runMigrations(Array)
#10 REPLACE_WITH_PATH/vendor/craftcms/cms/src/controllers/UpdaterController.php(203): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#11 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#12 REPLACE_WITH_PATH/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 REPLACE_WITH_PATH/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#14 REPLACE_WITH_PATH/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('migrate', Array)
#15 REPLACE_WITH_PATH/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#16 REPLACE_WITH_PATH/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('updater/migrate', Array)
#17 REPLACE_WITH_PATH/vendor/craftcms/cms/src/web/Application.php(646): craft\web\Application->runAction('updater/migrate')
#18 REPLACE_WITH_PATH/vendor/craftcms/cms/src/web/Application.php(243): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#19 REPLACE_WITH_PATH/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#20 REPLACE_WITH_PATH/web/index.php(21): yii\base\Application->run()
#21 REPLACE_WITH_PATH/.composer/vendor/cpriego/valet-linux/server.php(232): require('REPLACE_WITH_PATH/a...')
#22 {main}
```

**Comment by RyVeata** [comment]
Also experiencing the same `RELEASE SAVEPOINT LEVEL1` error on my postgreSQL having tried to update my Sprout Forms from 3.11.3 to 3.12.2 this afternoon.  Tried upgrading in steps and have reached 3.11.7 but then end up not being able to upgrade because of the various SQL issues in this original thread which are resolved by the later updates.

**Comment by RyVeata** [comment]
Thanks for reopening the thread @BenParizek.  Do you have any additional suggestions as to how to get round the `RELEASE SAVEPOINT LEVEL1` issue on PostgreSQL?  My site's still stuck on 3.11.7 at the moment until I can get a working upgrade.  Would deleting the reports table as per the mentioned issue or removing the migration be a way round it? Thanks for all your work maintaining and developing the plugin.

**Comment by sjwarner-bp** [comment]
Believe that I am experiencing the same issue here.

Trying to upgrade from:

```
  CRAFT_SPROUT_EMAIL_PLUGIN_VERSION=4.0.8 \
  CRAFT_SPROUT_FORMS_PLUGIN_VERSION=3.7.2 \
  CRAFT_SPROUT_FIELDS_PLUGIN_VERSION=3.5.5 \
  CRAFT_SPROUT_SEO_PLUGIN_VERSION=4.2.12 \
```

to:

```
  CRAFT_SPROUT_EMAIL_PLUGIN_VERSION=4.4.8 \
  CRAFT_SPROUT_FORMS_PLUGIN_VERSION=3.13.1 \
  CRAFT_SPROUT_FIELDS_PLUGIN_VERSION=3.8.4 \
  CRAFT_SPROUT_SEO_PLUGIN_VERSION=4.6.5 \
```

(i.e. latest at the time of writing)

Get:

```
Output:

> alter column dataSourceId in table {{%sproutreports_reports}} to integer ...Exception: SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect INTEGER value: 'sproutreports.users'
The SQL being executed was: ALTER TABLE craft_sproutreports_reports CHANGE dataSourceId dataSourceId int(11) (/var/www/vendor/yiisoft/yii2/db/Schema.php:677)
#0 /var/www/vendor/yiisoft/yii2/db/Command.php(1298): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE cr...')
...
```

Did anyone find a way to progress with this issue? I can update more incrementally if necessary, but am hoping for some guidance on the best way to navigate this problem.

**Comment by BenParizek** [comment]
This migration issue should be addressed in the latest release of Sprout Forms. 

I'm catching up on several support tickets right now and working on a large update to improve the migration process that has been causing a lot of issues in our plugins. There will likely be several smaller updates coming out over the next couple of weeks so, if possible, and you can hold off on updating until we get Sprout Forms v4.0 out the door that should get things into a lot better shape and address a number of smaller issues all at once.

**Comment by jamesmacwhite** [comment]
FYI for anyone coming across this after the issue being closed. You can still hit this issue with MySQL 8 and strict mode, see https://github.com/barrelstrength/craft-sprout-forms/issues/589
