### ISSUE TITLE
Can't update sprout-forms 3.8.1 -> 3.12.2

### ISSUE THREAD

**Issue by wooge** [barrelstrength/craft-sprout-forms#495]
### Description (screenshots, logs, ...)
I'm attemptin to update sprout-forms but seemed to be locked in a loop of errors.

When I run ./craft update sprout-forms I get the following erors

`Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - barrelstrength/sprout-import 1.0.2 requires barrelstrength/sprout-base ^5.0.0 -> satisfiable by barrelstrength/sprout-base[5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.0.4, 5.0.5, 5.0.7, 5.0.9, 5.1.0, 5.1.1, 5.1.2, 5.1.3, 5.2.0] but these conflict with your requirements or minimum-stability.
    - barrelstrength/sprout-import 1.0.2 requires barrelstrength/sprout-base ^5.0.0 -> satisfiable by barrelstrength/sprout-base[5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.0.4, 5.0.5, 5.0.7, 5.0.9, 5.1.0, 5.1.1, 5.1.2, 5.1.3, 5.2.0] but these conflict with your requirements or minimum-stability.
    - barrelstrength/sprout-import 1.0.2 requires barrelstrength/sprout-base ^5.0.0 -> satisfiable by barrelstrength/sprout-base[5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.0.4, 5.0.5, 5.0.7, 5.0.9, 5.1.0, 5.1.1, 5.1.2, 5.1.3, 5.2.0] but these conflict with your requirements or minimum-stability.
    - Installation request for barrelstrength/sprout-import 1.0.2 -> satisfiable by barrelstrength/sprout-import[1.0.2].`

If I modify the `composer.json` file so that `sprout-base` is set to 5.0.1, I get this:

`Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for barrelstrength/sprout-forms 3.12.2 -> satisfiable by barrelstrength/sprout-forms[3.12.2].
    - barrelstrength/sprout-forms 3.12.2 requires barrelstrength/sprout-base ^6.0.1 -> satisfiable by barrelstrength/sprout-base[6.0.1] but these conflict with your requirements or minimum-stability.
`

Not sure how to resolve this. I tried deleting the barrelstrength folder in the vendor dir and re-ran ccomposer update, but there seems to be a version dependancy conflict of some kind. This seems to happen on any Ccraft CMS site I have sprout-forms installed.

### Additional info

- Craft version: 3.4.22.1
- PHP version: 7.1.33

Here's my composer.json file:

`{
  "require": {
    "barrelstrength/sprout-forms": "3.8.1",
    "barrelstrength/sprout-import": "1.0.2",
    "barrelstrength/sprout-base": "5.0.1",
    "carlcs/craft-deleteentryversions": "2.0.0",
    "carlcs/craft-redactorcustomstyles": "3.0.3",
    "craftcms/cms": "3.4.22.1",
    "craftcms/feed-me": "4.2.3",
    "craftcms/guest-entries": "2.3.0",
    "craftcms/redactor": "2.6.1",
    "dolphiq/iconpicker": "1.0.5",
    "doublesecretagency/craft-cpcss": "2.2.1",
    "enupal/backup": "1.4.0",
    "ether/logs": "3.0.3",
    "mikestecker/craft-videoembedder": "1.1.4",
    "nystudio107/craft-seomatic": "3.3.5",
    "putyourlightson/craft-dashboard-begone": "1.0.1",
    "solspace/craft-freeform": "3.6.10",
    "spicyweb/craft-embedded-assets": "2.2.6",
    "supercool/buttonbox": "2.0.4",
    "verbb/field-manager": "2.1.6",
    "verbb/super-table": "2.5.0",
    "vlucas/phpdotenv": "^2.4.0"
  },
  "autoload": {
    "psr-4": {
      "modules\\": "modules/"
    }
  },
  "config": {
    "sort-packages": true,
    "optimize-autoloader": true,
    "platform": {
      "php": "7.0"
    }
  },
  "scripts": {
    "post-root-package-install": [
      "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
    ]
  }
}
`

**Comment by wooge** [comment]
Ok I seem to have solved it by:

1) Removing the "barrelstrength/sprout-import" entry from my composer.json
2) Changing the version number for "barrelstrength/sprout-forms" to the latest "3.12.2"
3) Deleting the /vendor/barrelstrength folderr
4) running composer update from the crat root.

**Comment by BenParizek** [comment]
@wooge Glad you got things resolved.

Broadly speaking, currently, the Sprout plugins have several shared dependencies which can lead to scenarios where if a shared dependency has a major version release, all installed Sprout plugins need to be updated at the same time or there can be issues. In this case, I think the shared dependency was Sprout Import which we dropped support for several months ago and is no longer compatible with the latest versions of our plugins.

We are in the process of updating our application architecture so that there will be fewer composer dependency issues like this that may arise.
