### ISSUE TITLE
Cannot get Google reCAPTCHA settings to save

### ISSUE THREAD

**Issue by justinholtweb** [barrelstrength/craft-sprout-forms#497]
### Description (screenshots, logs, ...)

I cannot get Google reCaptcha settings to save, both from the settings in admin and also via a config setup. I enter the information including the keys from Google and upon save, the setting to enable reCaptcha is set back to inactive and none of the settings are retained.

### Steps to reproduce

1. Enable Google reCaptcha settings after installing plugin.
2. Enter reCaptcha keys and configure settings as needed.
3. Save settings from admin, check that settings are retained and that the reCaptcha setting is still enabled.

### Additional info

- Craft version: 3.4.0
- PHP version: 7.1.2
- Database driver & version:  MySQL 5.7.30
- Plugins & versions: Google reCAPTCHA for Sprout Forms 1.4, Sprout Forms Pro 3.12.2

_For some issues, we may request that you send the following items to Support <sprout@barrelstrengthdesign.com>. If you feel your issue may fall in that category, feel free to send things over after you post this issue and reference the issue in your email._

- `composer.json`
- `storage/logs/web.log` (or a zip of the whole log folder)
- An export of your database (or, if you can't share the whole db, the specific Sprout tables)

**Comment by BenParizek** [comment]
@justinholtweb One thing to note here that may not be clear in the interface is that if you override _any_ `captchaSettings` in the config overrides, that will overwrite the whole array of captcha settings in the CP.

Let me know if that helps solve it or if the issue persists. I'm unable to recreate the issue in a few tests. If it's easier to troubleshoot over a screen share, hit me up at @BenParizek on Craft Discord. Outside of that, we'll start having to explore more data points here on what other setting you have in place, if other captcha settings are saving, if other Form settings in general are saving, etc.

**Comment by justinholtweb** [comment]
@BenParizek That makes a lot of sense, I was kind of afraid that was what was happening. I'm really only running a local config for emails to overcome the current bug with Honeypot field referenced at https://github.com/barrelstrength/craft-sprout-forms/issues/491, as after a 3.12 update I ran into the same issue reported where the Spam Settings admin screen would not load. 

Here's what my current config looks like, minus the google keys (removed for security):

`return [
    

    // The probability that the Spam cleanup task will run each time a
    // Form Entry is saved. A lower probability will trigger a cleanup task
    // less often and the number of Spam Entries stored in the database may
    // be higher than the Spam Limit target until the cleanup task is triggered.
    //
    // 0 - None
    // 100000 - 1 in 10
    // 10000 - 1 in 100
    // 1000 - selected>1 in 1,000
    // 100 - 1 in 10,000
    // 10 - 1 in 100,000
    // 1 - 1 in 1,000,000
    'cleanupProbability' => 1000,

    // Individual captcha settings
    //
    // Additional Captchas can be found in the Plugin Store:
    // https://plugins.craftcms.com/sprout-forms-google-recaptcha
    //
    // Custom Captchas can be added via the Captcha API
    'captchaSettings' => [
        'barrelstrength\sproutforms\captchas\DuplicateCaptcha' => [
            'enabled' => true,
        ],
        'barrelstrength\sproutforms\captchas\JavascriptCaptcha' => [
            'enabled' => true,
        ],
        'barrelstrength\sproutforms\captchas\HoneypotCaptcha' => [
            'enabled' => true,
            'honeypotFieldName' => 'sprout-forms-hc',
            'honeypotScreenReaderMessage' => 'Leave this field blank'
        ],
        'sproutformsgooglerecaptcha-googlerecaptcha' => [

            // Enable the Captcha for use.
            'enabled' => true,

            // The type of reCAPTCHA to use when validating a form
            // Options: v2_checkbox, v2_invisible
            'recaptchaType' => 'v2_checkbox',

            // The siteKey from your reCAPTCHA settings: https://www.google.com/recaptcha/admin
            'siteKey' => '',

            // The secretKey from your reCAPTCHA settings: https://www.google.com/recaptcha/admin
            'secretKey' => '',

            // The language reCAPTCHA will use;use;use;use;. Default: 'en'.
            // For supported languages, see: https://developers.google.com/recaptcha/docs/language
            'language' => 'en',

            // The theme that reCAPTCHA will use
            // Options: light, dark
            'theme' => 'light',

            // The size the reCAPTCHA will use
            // Options: normal, compact
            // This setting only applies to the v2_checkbox captcha
            // See: https://developers.google.com/recaptcha/docs/display#render_param
            'size' => 'normal',

            // The position the reCAPTCHA will use
            // Options: bottomright, bottomleft, inline-badge, inline-text
            // This setting only applies to the v2_invisible captcha
            'badge' => 'bottomright',

            // Enable this setting if you wish to manage CSS manually
            'disableCss' => false
        ],
    ],
    

];`

**Comment by BenParizek** [comment]
@justinholtweb The issue might just be in the reCAPTCHA settings key. We have a typo in the example config file

`sproutformsgooglerecaptcha-googlerecaptcha` should be `barrelstrength\sproutformsgooglerecaptcha\integrations\sproutforms\captchas\GoogleRecaptcha`

**Comment by justinholtweb** [comment]
@BenParizek ah cool ok, i'll switch that out this morning and check the results and if it's all good after that will close the issue. Thanks for the quick reply! :)

**Comment by BenParizek** [comment]
If that doesn't solve it, if you can share your db to sprout@barrelstrengthdesign.com, I'd be happy to take a closer look. Not sure what the Spam Settings issue is but sounds like it's affecting multiple folks.

We are working on addressing our settings architecture (which has caused some annoying bugs lately) so we may address this in a larger sense shortly, but I'm not sure that will solve the discrepancy in the settings for others if the missing honeypot is caused by a migration issue that I'm not seeing yet.

**Comment by justinholtweb** [comment]
@BenParizek That did it, changing that key in the config got it to read and preserve the settings correctly. Thanks for your quick replies, gonna close this out now.

**Comment by ademers** [comment]
Just ran in to this https://github.com/barrelstrength/craft-sprout-forms-google-recaptcha/issues/24

Perhaps update the example in the config file as mentioned https://github.com/barrelstrength/craft-sprout-forms/issues/497#issuecomment-639490248?

**Comment by jerome2710** [comment]
I was having the same issue, the suggestion above would be helpful @BenParizek .
