### ISSUE TITLE
standard email template error: Impossible to invoke a method ("getFullNameExtended")

### ISSUE THREAD

**Issue by lexislav** [barrelstrength/craft-sprout-forms#504]
When Name field is in use, not required and left empty by user, there is an error in email template:
`Impossible to invoke a method ("getFullNameExtended") on a null variable.`

I have fixe in mine template by adjusting template like this:

`{% elseif field.getFieldInputFolder() == 'name' and value and value.getFullNameExtended() != '' %}`

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2vslp)

**Comment by BenParizek** [comment]
@lexislav I've tested this and it appears to be working when no value is submitted. I've been making several changes so it's possible I addressed this indirectly but let me know if the issue continues for you and we can dig in more to your scenario and figure it out.
