### ISSUE TITLE
entries field not listed in notifications standard template

### ISSUE THREAD

**Issue by lexislav** [barrelstrength/craft-sprout-forms#505]
Form contains entries field which is correctly saved to database and might be checked on Sprout forms/Entries in CP.

But notification email template shows „No response“.
Haven't figured out how to fix this yet.

**Comment by BenParizek** [comment]
@lexislav The relations field should output a list of the selected Titles in the Notification Email Template. In my tests this is working as expected so if you're still experiencing the above I may need to know more about your notification settings and if you're doing anything custom with your templates. The code that should be outputting the Entries field and other Relations fields is here:

https://github.com/barrelstrength/craft-sprout-forms/blob/97e59219357826b025feb79b8a98d65a476c88b5/src/templates/_integrations/sproutemail/emailtemplates/basic/email.twig#L132-L148

**Comment by lexislav** [comment]
Unfortunatelly we have been forced to switch from sprout forms. So, right now I can’t provide any info about this.
Take care

**Comment by BenParizek** [comment]
Understood. Thanks @lexislav.
