### ISSUE TITLE
Getting a template render error using standard email templates

### ISSUE THREAD

**Issue by justinholtweb** [barrelstrength/craft-sprout-forms#506]
### Description (screenshots, logs, ...)
Recently updated site to Craft 3.4.23 and Forms to 3.12.2 and now getting a Craft TypeError upon form submissions:

`Argument 1 passed to craft\web\View::renderTemplate() must be of the type string, null given, called in /Users/jholt/Sites/chalcedon-craft-3/vendor/barrelstrength/sprout-base-email/src/base/EmailTemplates.php on line 145`

Looking into that method, it seems like Sprout is unable to determine what the template is for the notification template, as it's not getting reset from its initial NULL value. 

We are using the Basic notification template from Sprout, and when I try to view any of them from the Notifications dashboard preview I get a 404. 

### Steps to reproduce

1. Create or use Notification, associate to a form.
2. Submit the form (with devmode turned on), get the TypeError.

### Additional info

- Craft version: 3.2.23
- PHP version: 7.1.2
- Database driver & version:  MySQL 5.7.30
- Plugins & versions: Sprout Forms 3.12.2, Sprout Sent Email 1.1.1

_For some issues, we may request that you send the following items to Support <sprout@barrelstrengthdesign.com>. If you feel your issue may fall in that category, feel free to send things over after you post this issue and reference the issue in your email._

- `composer.json`
- `storage/logs/web.log` (or a zip of the whole log folder)
- An export of your database (or, if you can't share the whole db, the specific Sprout tables)

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2vsnh)

**Comment by williamhibberd** [comment]
I am getting a very similar issue. I have just updated a site from Craft 2 to Craft 3.4.27. 
When trying to preview or send a notification with a custom notification template I run into the same error as above.

**Comment by justinholtweb** [comment]
@BenParizek Just checking in on this, seeing if you had any insight on a fix or troubleshooting info you might need that could help?

**Comment by BenParizek** [comment]
@justinholtweb @williamhibberd I'll have a fix out for this in the next release.

This was due to a migration bug where the Craft 2 Form Notification Email did not get updated and saved with an Email Template ID. If you'd like to fix this before then, resaving any Form Notification Emails should get the correct values saved in the db and correct this issue.

**Comment by BenParizek** [comment]
This should be addressed in the latest release of Sprout Forms. 

I'm catching up on several support tickets right now and working on a large update to improve the migration process that has been causing a lot of issues in our plugins. There will likely be several smaller updates coming out over the next couple of weeks so, if possible, I'd recommend holding off on updating until we get Sprout Forms v4.0 out the door which should get things into a lot better shape.
