### ISSUE TITLE
Attachments not being sent in Notifications when option to save data to databse is disabled

### ISSUE THREAD

**Issue by dean-yump** [barrelstrength/craft-sprout-forms#507]
When we have the save data option disabled (which is a requirement for this project), the attachments do not come through with the email. The email comes through without the attachments. Attachments work fine with the option enabled. Have attached server info, versions and entry in web.log after submitting the form. 

[web-excerpt.log](https://github.com/barrelstrength/craft-sprout-forms/files/4795897/web-excerpt.log)
[server-info.txt](https://github.com/barrelstrength/craft-sprout-forms/files/4795909/server-info.txt)

**Comment by BenParizek** [comment]
Thanks @dean-yump. We'll look into this and address that logic. Will update this thread when we have a fix.
