### ISSUE TITLE
Can't see name field data in notification email, it shows No Response

### ISSUE THREAD

**Issue by caroldq55** [barrelstrength/craft-sprout-forms#515]
### Description (screenshots, logs, ...)
I can see name data in form entry, and I add notification email when an entry is saved, but can't see name data in the email.

**form entry**
<img width="884" alt="Screen Shot 2020-07-17 at 3 31 37 pm" src="https://user-images.githubusercontent.com/44183456/87752002-aaf80880-c842-11ea-8075-d406f5378a70.png">

**notification email**
<img width="864" alt="Screen Shot 2020-07-17 at 3 32 41 pm" src="https://user-images.githubusercontent.com/44183456/87752054-cc58f480-c842-11ea-9c0a-f1ec3eac5831.png">

### Steps to reproduce

1. Create a new form with name field included in sprout form and use that form on front end
2. Create a new sprout notification connected with that form, and it will send email if entry is saved
3. Submit the form on frontend, then found name field is No response in the email

### Additional info

- Craft version: 3.4.13
- PHP version: 7.4.8
- Database driver & version:  MySQL 5.7.12
- Plugins & versions: sprout forms 3.12.2

_For some issues, we may request that you send the following items to Support <sprout@barrelstrengthdesign.com>. If you feel your issue may fall in that category, feel free to send things over after you post this issue and reference the issue in your email._

- `composer.json`
- `storage/logs/web.log` (or a zip of the whole log folder)
- An export of your database (or, if you can't share the whole db, the specific Sprout tables)

**Comment by BenParizek** [comment]
Thanks for reporting @caroldq55. We'll update this thread once we have a fix ready.

**Comment by BenParizek** [comment]
I've just released Sprout Forms v3.13.0 that adds support for the name field in the default Form email template:

https://github.com/barrelstrength/craft-sprout-forms/blob/v3/src/templates/_integrations/sproutemail/emailtemplates/basic/email.twig#L112
