### ISSUE TITLE
Craft 3.5 Sprout Settings Error

### ISSUE THREAD

**Issue by azaitar** [barrelstrength/craft-sprout-forms#519]
### Description (screenshots, logs, ...)
<img width="1460" alt="Bildschirmfoto 2020-08-05 um 20 16 44" src="https://user-images.githubusercontent.com/14804382/89523100-a17b1400-d7e2-11ea-86c5-a49e1bbbd51d.png">

### Steps to reproduce

1. Install Craft 3 latest Version (3.5)
2. Go to the Plugin Store Download Sprout Forms
3. go to "Plugins" and click on "Settings"
4. Json Error should be visible.

### Additional info

- Craft version: 3.5
- PHP version: 7.4.7
- Database driver & version:  MySQL 5.7.26
- Plugins & versions: no plugin installed only Sprout Forms

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_34365)

**Comment by JJefferyDev** [comment]
I'm also having this issue.  I'm going to try update everything else, uninstall Sprout, and reinstall it.

**Comment by BenParizek** [comment]
@azaitar @JJefferyDev I'll look into this and am also in the final stages of polishing up a new major release to Sprout Forms that is needed to address several of the migration issues we've had troubles with over the last months. 

I'll update this thread if I can provide a temporary solution before we get that next release out but we probably won't try to fully support Craft 3.5 with the current release outside of simple, temporary manually applied fixes our focus is on making the next release Craft 3.5 compatible.

**Comment by azaitar** [comment]
Thanks @BenParizek 

I have another Issue when upgrading any Craft like 3.2.x or 3.3.x to the latest Craft the following error appears.

Should i open another Issue or should i just let this comment here ? 

![Bildschirmfoto 2020-08-25 um 16 34 47](https://user-images.githubusercontent.com/14804382/91187854-e9f66500-e6f0-11ea-9f50-d5428c596d30.png)

**Comment by BenParizek** [comment]
@azaitar This will be addressed once we get the Craft 3.5 compatible release out.

**Comment by azaitar** [comment]
Any expected date for the new release ?

**Comment by BenParizek** [comment]
@azaitar I can't promise a date yet. Getting closer, but still lots of testing to do.

**Comment by wes-lawson** [comment]
@BenParizek any eta on the Craft 3.5 compatible release?

**Comment by BenParizek** [comment]
@wes-lawson et al. I've just released Sprout Forms v3.13.0 with Craft 3.5 support. 
https://plugins.craftcms.com/sprout-forms

Let me know if you run into any other issues. I will be turning my focus toward getting all migration issues resolved next.
