### ISSUE TITLE
Craft 3.5: Saving any form wipes out all fields, unable to edit that form again due to error

### ISSUE THREAD

**Issue by jrrdnx** [barrelstrength/craft-sprout-forms#521]
### Description (screenshots, logs, ...)

Recently upgraded to Craft 3.5/3.5.1 (occurs on both versions). When I make a change to an existing form and hit Save, it clears out all existing fields on that form and I am unable to edit that form again to fix the issue.

![Immediately after saving form. Note the Number of Fields column shows 0, previous value was 4](https://user-images.githubusercontent.com/4584671/89556853-f8cbb500-d7df-11ea-8ac5-9665fee4aa50.png)

![Attempting to edit the same form again shows this error](https://user-images.githubusercontent.com/4584671/89556926-10a33900-d7e0-11ea-9613-9bad1764ca85.png)

### Steps to reproduce

1. Edit an existing form, then hit Save.
2. Form no longer has any fields.

### Additional info

- Craft version: 3.5 - 3.5.1
- PHP version: 7.2.27
- Database driver & version:  MySQL 5.6.46
- Plugins & versions: Sprout Forms 3.12.2

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_30y4t)

**Comment by jrrdnx** [comment]
Just confirmed that this happens both with new forms created, and existing forms. Hitting Save saves the form successfully, but without any fields. Unable to edit any existing form due to the error.

**Comment by niels-vormenvorm** [comment]
I have the same issue, it also occurs on Craft 3.5.2

**Comment by jwrudzin** [comment]
Same issue here on Craft 3.5.3.

**Comment by MisterMike** [comment]
Same here. Since the DB table persists if you delete the damaged form, you cannot recreate it. There ist an error in the backend: "Key "0" does not exist as the array is empty" (for line 20 in /vendor/barrelstrength/sprout-forms/src/templates/forms/_editForm.twig)

**Comment by niallthompson** [comment]
Same issue here. Running Craft Pro 3.5.4

**Comment by BenParizek** [comment]
@jrrdnx @jwrudzin @niels-vormenvorm @niallthompson I'm looking into this and am also in the final stages of polishing up a new major release to Sprout Forms is needed to address several of the migration issues we've had troubles with over the last months. I'm not sure if I'll be able to address this before we get that next major release out but will update this thread when I have more info.

**Comment by joetunis** [comment]
Same issue here, and this is blocking some updates for a couple clients.  Commenting here to get notified when it is fixed.

**Comment by lexislav** [comment]
Same issue, any progress on fix this?

**Comment by nickcobley** [comment]
I've had to start looking at alternative form handlers as a result of this as of tonight, it's just taking too long. If a fix is close would be good to know.

**Comment by fhamon** [comment]
You guys have an ETA ? I really need to give a date to my clients who are affected by this.

**Comment by BenParizek** [comment]
Hi all. The current version of the Sprout plugins have not been tested on Craft 3.5. I'm working on a new major release for Craft 3.5 that will address this and several ongoing migration issues we've been having over the past couple of releases.

The short version is that a while back I made an architectural decision to break out some shared Sprout functionality into multiple composer packages. As time went on, with additional releases in various plugins we have that use the shared functionality, the complexity around this decision multiplied and at some point seemed to get exponential in the number of minor outlier and migration issues it created between the various plugins using the shared modules.

I've spent the last couple of months working on a new major release that consolidates all of the shared modules into a single package again. That is mostly done and I'm currently working through the migrations needed to try to get things back on track and less burdensome again, and my timeline has unfortunately been complicated by the release of Craft 3.5 and additional new bugs that have been introduced that need to get addressed.

While I do consider this a high priority, it's taking some time to get right as the fix isn't simply about a single error but the entire architecture of the Sprout plugins right now. Once I get through that, our issues should become more specific to what they appear to be about again.

**Comment by nickcobley** [comment]
@BenParizek 

Thanks for the update. Can I suggest you get this information into https://github.com/barrelstrength/craft-sprout-forms/blob/v3/README.md or somewhere prominent? As this is a risky one where even if you do a test upgrade of your production site, if you don't hit save on a form, you may never see this issue until it's too late. I have one production site now where going backwards is too hard, so now nobody can edit forms.

**Comment by extensibleseth** [comment]
Should composer.json be updated to require "craftcms/cms": "~3.4.0"?

**Comment by BenParizek** [comment]
@extensibleseth Yes. That's something I'll be considering. Generally speaking, non-major releases are not supposed to have breaking changes but that hasn't been the case for our plugins in several of Craft's releases 3.2, 3.3, 3.4. They are aware of this and I know they are making an effort to reduce these scenarios but with 3.5 we're running into this again, so it may make sense for us to move to constraining our releases to Craft's minor releases and intentionally making a release every time a minor release comes out to indicate that we can support it.

@nickcobley I'll see what I can do. I think the above suggestion is going to be the most clear during the upgrade process as it will potentially throw an error. As I centralize the modules again, I may also be able to create a more centralized upgrade notes area in our docs where I can flag something like this.

**Comment by MFFoX** [comment]
@BenParizek Thanks for all the useful information about this issue. I am glad to hear about this change as we've had a lot of problems with the split packages for a while.

In the meantime, do you have any kind of ballpark for the amount of time you're looking at for a 3.5 compatible release? Any information would be helpful for me as we have multiple sites scheduled to go out in the next coming weeks on 3.5. Is it looking like there could be something in the next couple of weeks? Or is it more in the month+ ballpark?

**Comment by exophunk** [comment]
I understand that this is a complicated issue that can not be fixed quickly.

I am also surprised, that there is no warning message or notice in any readme even 12 days later. The Sprout Forms Documentation states that the plugin is [compatible](https://sprout.barrelstrengthdesign.com/docs/forms/installing-and-updating-craft-3.html#requirements) with Craft 3.3+

Having all fields deleted on saving a form is a massive data loss. It also makes all existing form entries unavailable. We did not notice this before upgrading production. Because yes, we did not test "Saving an existing form" in detail. Who does?

Please: Add warning messages to the documentation / readme that Craft 3.5 is not supported and probably also add a 3.4 requirement to composer, because this is potentially a major issue for lots of users of your plugins.

**Comment by janklan** [comment]
@extensibleseth is right. It's been 7 weeks since the issue was reported and while I understand the resolution will take some time, I don't understand why composer.json still allows installing the plugin on Craft CMS 3.5?

**Comment by torgeirbeyer** [comment]
We're also experiencing this on a site with Craft 3.5.10.1 and Sprout Forms 3.12.2. Do you know when this problem will be fixed? our clients can't make new forms for their website. @BenParizek

**Comment by redzioch** [comment]
@BenParizek Same here... Any estimated fix timeline?

**Comment by tomdavies** [comment]
@BenParizek We've used (and paid for) your plugins for a long time, so it pains me to write this but, I've got to say I think it's pretty unacceptable for a commercial plugin not to put the fact that it's incompatible with the current Craft release front and centre of the promotional material / documentation. 

Failing to do so for this length of time, doubly so. This isn't going inspire trust from your customers or the wider Craft community.

It's fair enough if it's taking a while to migrate to supporting 3.5. It's even fair enough not to provide a timeline (I've missed my share of deadlines too), but not being open and honest about this pretty significant short coming at either the point of sale or in the documentation is a really bad idea.

Updating you documentation and sales pages ain't gonna take you much time, and would both help you retain good will and more importantly save your customers time and frustration. Heck, if you'll merge it I'll PR your docs for you today.

I would have thought you could also pretty easily publish a patch version that would fix the stated compatibility in `composer.json` too. Please consider spending that hour or so as soon as sanely possible.

**Comment by tomdavies** [comment]
Hi @BenParizek thanks for the considered reply. Sorry if I came off a bit brisk in my prev message.

**If you could update the documentation (or even just the repo readme) with a version of what you've just said,  I think that would ease a lot of the frustration you're seeing** - Craft devs tend to be a humane bunch and are likely to be realistic about the timeframe for a fix. We all make software for a living and understand how things take longer than planned / deadlines tend to go out of the window.

I personally can't risk the dev version on the production sites where we could do with a fix for this at the moment, but I appreciate you putting that option forward and will follow with interest how others get on with it.

Hope things ease up for you at work and elsewhere - I know all too well that it's no fun to be overcapacity.

**Comment by brandonkelly** [comment]
We just released Craft 3.5.13 which provides backwards compatibility with the old way of submitting field layout data, which solves the primary issue here. I’ve also submitted PR #537 which fixes similar issues, such as when saving a field’s settings.

If anyone wants to help test this, make the following changes to your `composer.json`:

- Change your `craftcms/cms` requirement to `"3.5.13" or `"^3.5.13"`.
- Change your `barrelstrength/sprout-forms` requirement to `"dev-craft-3.5"`.
- Add this repository config:

    ```json
    {
      "...": "...",
      "repositories": [
        {
          "type": "vcs",
          "url": "https://github.com/brandonkelly/craft-sprout-forms"
        }
      ]
    }
    ```

Then run `composer update`. (Note this will take longer than usual.)

**Comment by simonda86** [comment]
@brandonkelly I've tested this and it fixes the issue for me!

Thanks Brandon!

**Comment by redzioch** [comment]
> We just released Craft 3.5.13 which provides backwards compatibility with the old way of submitting field layout data, which solves the primary issue here. I’ve also submitted PR #537 which fixes similar issues, such as when saving a field’s settings.
> 
> If anyone wants to help test this, make the following changes to your `composer.json`:
> 
> * Change your `craftcms/cms` requirement to `"3.5.13" or `"^3.5.13"`.
> * Change your `barrelstrength/sprout-forms` requirement to `"dev-craft-3.5"`.
> * Add this repository config:
>   ```json
>   {
>     "...": "...",
>     "repositories": [
>       {
>         "type": "vcs",
>         "url": "https://github.com/brandonkelly/craft-sprout-forms"
>       }
>     ]
>   }
>   ```
> 
> Then run `composer update`. (Note this will take longer than usual.)

@brandonkelly 

It seems that saving Checkbox fields is broken now. I get an error "<field_name> is invalid", despite value. Changing field type to Multi-select solves the problem.

**Comment by brandonkelly** [comment]
@redzioch Sorry, just released 3.5.13.1 with a fix for that. FFR please report Craft-specific issues over at https://github.com/craftcms/cms/issues.

**Comment by stigzelm** [comment]
Any tips on how to get the fields back after they have disappeared?

**Comment by nicholashu** [comment]
> Any tips on how to get the fields back after they have disappeared?

From my experience they are lost in the ether, without some serious trawling through the database. However, the field references are still in the db so, you can't create a new field with the same handle. I found it easier to just delete the form (and remove it from the database table, if you need to reuse the handle) and start again..

**Comment by BenParizek** [comment]
@stigzelm I don't have a quick answer. The issue was related to a change in how the field layout tab was defined during the form submission. If you'd like to drop me a note at sprout@barrelstrengthdesign.com and share your database or arrange a time to share screens and look at what's in the database, happy to take a look.

**Comment by stigzelm** [comment]
@BenParizek Thanks. We ended up rebuilding the form. The only down side with this is that now all submissions to this form are empty. We will manage with this downside. Would have been nice if there was a easy way to restore the removed fields.
