### ISSUE TITLE
Changing the Primary Site removes all Sprout Forms data

### ISSUE THREAD

**Issue by andypullen** [barrelstrength/craft-sprout-forms#524]
### Description (screenshots, logs, ...)
All Sprout Forms data will vanish from the dashboard and be unavailable to Sprout Forms twig functions after changing the Primary Site in Craft.

### Steps to reproduce
1. Create multiple Sites
2. Install Sprout Forms
3. Build a form, make some entries, create notifications, etc.
4. Change the Primary Site from one Site to another
5. All Sprout Forms data will vanish from the admin GUI and will be unable to be referenced in twig

### Additional info

- Craft version: 3.4.x & 3.5.x at least
- PHP version: 7.4
- Plugin version: latest Sprout Forms plugin

**Comment by BenParizek** [comment]
@andypullen This looks like an oversight on our part. Sprout Forms (currently) just supports a single site in a multi-site install and saves its content based on the ID of that site.

We'll be looking into improved multi-site support at some point, but in your case (switching the primary site) the immediate fix may need to be done manually until we sort this out.

To do this I believe we'll need to update the `siteId` value for all Form and Form Entry elements in the db. This may also be necessary for Notifications and Reports (I'd have to look into how we are supporting those with multi-site in mind too).

Here's a starting point.

This query grabs all the IDs of Form and Form Entry Elements:

```
SELECT elements.id
FROM craft_elements AS elements
JOIN craft_elements_sites AS element_sites
	ON elements.id = element_sites.elementId
WHERE elements.type IN (
	'barrelstrength\\sproutforms\\elements\\Form',
	'barrelstrength\\sproutforms\\elements\\Entry'
	);
```

And this query would update the site IDs of any target element IDs:

```
UPDATE craft_elements_sites
SET siteId = 'barrelstrength\\sproutbase\\app\\email\\elements\\NotificationEmail'
WHERE elementId IN ( ELEMENT_IDS_HERE );
```

Combining those, I believe you could run this query (untested) to get all the Form and Form Entry element IDs updated:

```
UPDATE craft_elements_sites
SET siteId = 'barrelstrength\\sproutbase\\app\\email\\elements\\NotificationEmail'
WHERE elementId IN (
  SELECT elements.id
  FROM craft_elements AS elements
  JOIN craft_elements_sites AS element_sites
    ON elements.id = element_sites.elementId
  WHERE elements.type IN (
	'barrelstrength\\sproutforms\\elements\\Form',
	'barrelstrength\\sproutforms\\elements\\Entry'
  );
);
```

**Comment by brandonkelly** [comment]
Craft will automatically update all non-localizable elements’ `siteId`s when the primary site changes. If that’s not happening, it’s probably because the element type(s) aren’t [getting registered properly](https://craftcms.com/docs/3.x/extend/element-types.html#registration).

**Comment by BenParizek** [comment]
The latest release now registers Form and Entry elements as described above.
