### ISSUE TITLE
Spam protection not working

### ISSUE THREAD

**Issue by torgeirbeyer** [barrelstrength/craft-sprout-forms#527]
### Description (screenshots, logs, ...)
I've activated all three captchas (using Settings in the dashboard, not config file), but we're still getting a lot of spam requests through our contact form. Everything looks good in the frontend form. It is only a problem on one of our forms at the moment. No requests get saved in the spam folder.

### Additional info

- Craft version: 3.4.19.1
- PHP version: 7.2
- Database driver & version: mysql 5.8  
- Plugins & versions: Sprout forms 3.11.3

_For some issues, we may request that you send the following items to Support <sprout@barrelstrengthdesign.com>. If you feel your issue may fall in that category, feel free to send things over after you post this issue and reference the issue in your email._

- `composer.json`
- `storage/logs/web.log` (or a zip of the whole log folder)
- An export of your database (or, if you can't share the whole db, the specific Sprout tables)

**Comment by BenParizek** [comment]
@torgeirbeyer The default captchas are pretty simple. Have you taken a look at the reCAPTCHA plugin?:
https://plugins.craftcms.com/sprout-forms-google-recaptcha

reCAPCHA can be more robust based on Google's dataset and has additional settings in the Google interface to be more strict if you need to be.

Another step that can help in some scenarios is to use Cloudflare for your DNS and route things through their network. Cloudflare also attempts to filter traffic from known spam sources.
