### ISSUE TITLE
Error when editing form saved in Craft 3.5

### ISSUE THREAD

**Issue by john-dunkel** [barrelstrength/craft-sprout-forms#529]
### Description (screenshots, logs, ...)

After updating to Craft 3.5 Sprout Forms stopped working. As soon as you try to open a form that was created or at least saved in Craft 3.5, the following error appears:

<img width="837" alt="grafik" src="https://user-images.githubusercontent.com/50204846/91442150-ad9e4280-e871-11ea-8da8-20d091f0ba8e.png">

In the form overview, it also states that there are 0 fields in the form. Looks like a DB connection issue.
When trying to open Sprout Forms in the settings, another error appears: «Call to a member function getAcceptsJson() on string»

This issue also appears when installing sprout on a new Craft instance.

### Steps to reproduce

1. Update to Craft 3.5
2. Open existing form or create new form
3. Make sure the form has at least one field in it
4. Safe form and exit
5. Try to edit the form again

### Additional info

- Craft version: 3.5.6
- Plugins & versions: Sprout Forms 3.12.2, SEOmatic 3.3.17, Redactor 2.6.1

**Comment by darylknight** [comment]
Yeah I just saved a form on a 3.5.5 production site and it literally deleted all the fields.

**Comment by nickcobley** [comment]
This one is already open here https://github.com/barrelstrength/craft-sprout-forms/issues/521

Unfortunately, there is absolutely no indication when they are going to fix it

**Comment by BenParizek** [comment]
@john-dunkel @darylknight @nickcobley Sprout is not yet Craft 3.5 compatible and I'm working to address that.

I've posted a longer explanation of where things stand in the linked ticket:
https://github.com/barrelstrength/craft-sprout-forms/issues/521#issuecomment-685744505

**Comment by john-dunkel** [comment]
Closed this issue because of the redundancy with [#521](https://github.com/barrelstrength/craft-sprout-forms/issues/521)
