### ISSUE TITLE
Migration error: json syntax error

### ISSUE THREAD

**Issue by cakleimeier** [barrelstrength/craft-sprout-forms#533]
### Description
I'm trying to install Sprout Forms on a site that is newly-upgraded from Craft 2 and which also used Sprout Forms. During the migrations, I get the following error and the migration fails:

```
yii\base\InvalidArgumentException: Syntax error.

Migration: barrelstrength\sproutforms\migrations\m180712_000000_checkboxes_serialize

Output:

Exception: Syntax error.
```

The error looks to be coming from `vendor/yiisoft/yii2/helpers/BaseJson.php:133`

### Additional info

- Craft version: 3.5.5
- PHP version: 7.2.20
- Database driver & version: MySQL 5.7.62
- Plugins & versions:
  - "barrelstrength/sprout-base": "6.0.1",
   - "barrelstrength/sprout-base-reports": "1.5.6",
   - "barrelstrength/sprout-reports": "1.5.6",
   - "barrelstrength/sprout-base-fields": "1.4.3",
   - "barrelstrength/sprout-fields": "3.8.3",
   - "barrelstrength/sprout-base-email": "1.3.8",
   - "barrelstrength/sprout-base-sent-email": "1.1.2",
   - "barrelstrength/sprout-forms-google-recaptcha": "1.4.0",
   - "barrelstrength/sprout-forms": "3.12.2"

**Comment by cakleimeier** [comment]
After some review, I think this issue might be related to the issues detailed in [this comment](https://github.com/barrelstrength/craft-sprout-forms/issues/521#issuecomment-685744505).

**Comment by cakleimeier** [comment]
@BenParizek Is there any commit for Sprout _Forms_, specifically, that I could reference to get past this issue, as in this comment? https://github.com/barrelstrength/craft-sprout-reports/issues/98#issuecomment-685710988

**Comment by BenParizek** [comment]
@cakleimeier I'm catching up on support this week and next and working on a release with Craft 3.5 support. I'll update this thread once I get that out.

**Comment by cakleimeier** [comment]
@BenParizek Thanks for the update!

**Comment by BenParizek** [comment]
@cakleimeier If you still have your original db, could you share with me the value you see in the database column for the checkboxes field (or the multiple checkbox fields) in your form? It seems something stored in the database isn't what we are expecting it to be.

To find the custom fields in your database, you can look in the Form content table which is named using the `formHandle` and look for the column named after the checkboxes `fieldHandle`:

```
craft_sproutformscontent_formHandle.field_fieldHandle
```

**Comment by BenParizek** [comment]
I'm closing this out as I believe it had to do with a migration workflow which should now be addressed in the latest release.

Please drop me a note at sprout@barrelstrengthdesign.com or re-open with additional comments if the issue persists.
