### ISSUE TITLE
Can't run export directly

### ISSUE THREAD

**Issue by Nielsvdel** [barrelstrength/craft-sprout-forms#541]
When I want to run an export of a form it is only possible when I am in my admin account. If I switch to a user with the the same rights as the admin then I get an error saying I don't have permission. But when I click on "Run Report" and then on "Export" in the top right corner I can run the export. Hope you can help me out!

- Craft version: 3.4.30
- PHP version: 7.0
- Plugins & versions: 3.12.2

**Comment by BenParizek** [comment]
@Nielsvdel We're working on an update that should address this issue. I'll update this thread once we get that out.

**Comment by BenParizek** [comment]
Closing this out. Please follow duplicate issue for updates: https://github.com/barrelstrength/craft-sprout-forms/issues/541
