### ISSUE TITLE
Custom fields aren't available in entry element index

### ISSUE THREAD

**Issue by engram-design** [barrelstrength/craft-sprout-forms#543]
No custom fields appear for entries, when looking at "All Forms" or for any individual form:

![Screen Shot 2020-10-30 at 3 06 54 pm](https://user-images.githubusercontent.com/1221575/97658883-92de8900-1ac1-11eb-8a91-d6e4e92a7e1d.png)

Pretty sure this is due to Craft 3.5 updates. This should be a pretty easy fix, and also takes care of https://github.com/barrelstrength/craft-sprout-forms/issues/486

Refer to my PR https://github.com/barrelstrength/craft-sprout-forms/pull/544

### Additional info

- Craft version: 3.5.14
- PHP version: 7.2
- Database driver & version:  
- Plugins & versions: 3.13.0

**Comment by BenParizek** [comment]
Thanks @engram-design. Added in v3.13.1.
