### ISSUE TITLE
JavaScript Error, Uncaught TypeError: this.form is null

### ISSUE THREAD

**Issue by riusi88** [barrelstrength/craft-sprout-forms#547]
A Javascript error associated with Sprout forms is preventing certain form features from working properly. For instance the Address field is unable to swap between State and Province when selecting between United States and Canada as the Country field value. 

`Uncaught TypeError: this.form is null
    t https://polyurethanes.basf.us/cpresources/8e0de842/addressfield.js?v=1600981513:2
    <anonymous> https://polyurethanes.basf.us/contact/general-contact:103
    <anonymous> https://polyurethanes.basf.us/contact/general-contact:106
addressfield.js:2:12053`

### Link to page with error:
https://polyurethanes.basf.us/contact/general-contact

### Additional info

- Craft version: Tested on 3.4.22.1 & 3.5.15.1
- PHP version: 7.1.33
- Database driver & version:   MySQL 5.5.5
- Sprout: Tested with 3.12.2 & 3.13.0

**Comment by BenParizek** [comment]
Thanks @riusi88 

I'll look into this as soon as I can. Do you happen to be using custom template overrides?

If so, have you tested the Address field with the default templates to see if you experience the same behavior? The error message "this.form is null" suggests that the javascript might not be finding the Form by expected <form id="x"> value.

**Comment by riusi88** [comment]
Hey @BenParizek thank for looking into this. I have reset all the Form templates to the basic, and accessible defaults with no success as well.

**Comment by riusi88** [comment]
Hey @BenParizek I discovered a markup issue in the websites layout templates that triggered the JS error. There were some extra rouge closing `body` and `html` tags that I believe prevented the JS from functioning properly. Once I removed those extra closing tags the JS worked properly.
