### ISSUE TITLE
Renamed fields do not get attached to a form

### ISSUE THREAD

**Issue by MichaelWheldon** [barrelstrength/craft-sprout-forms#548]
### Description (screenshots, logs, ...)
Fields do not save and attach themselves to the form. The following is after creating a single line field and naming it "Contact name".

<img width="1440" alt="Screen Shot 2020-11-16 at 3 23 08 pm" src="https://user-images.githubusercontent.com/9004820/99212665-c8080c80-281f-11eb-854c-c21b9fe58614.png">

### Steps to reproduce
1. Create a new form
2. Drag over single line field
3. Rename this field
4. Save this field
5. Nothing is there per the above screenshot
6. Go to the form select screen and it will say it has 0 fields
7. Go back into the form and try adding the same field again, craft will complain that the field already exists

![image](https://user-images.githubusercontent.com/9004820/99212836-2f25c100-2820-11eb-91e6-8b3913747989.png)
![image](https://user-images.githubusercontent.com/9004820/99212846-364ccf00-2820-11eb-9efc-7283adfdff76.png)

### Additional info

- Craft version: Craft Pro 3.5.12.1
- PHP version: 7.4.6
- Database driver & version:  MySQL 5.7.30
- Plugins & versions: Pro Trial 3.12.2

**Comment by MichaelWheldon** [comment]
I’ll also add, saving a form with any field results in the following error:

<img width="1440" alt="Screen Shot 2020-11-16 at 3 34 15 pm" src="https://user-images.githubusercontent.com/9004820/99213261-3f8a6b80-2821-11eb-93f9-f78e7da89e00.png">

**Comment by BenParizek** [comment]
@MichaelWheldon It looks like you may be using the release just before we added Craft 3.5 support. Can you upgrade to Sprout Forms v3.13.0 and let me know if that gets things resolved for you?

https://github.com/barrelstrength/craft-sprout-forms/blob/v3/CHANGELOG.md#3130---2020-10-27

**Comment by MichaelWheldon** [comment]
@BenParizek will do! thanks for the speedy reply :)

**Comment by MichaelWheldon** [comment]
@BenParizek confirmed it now works with sprout 3.13.1 and latest craft + compose v2

thanks again for the help!
