### ISSUE TITLE
Changing default site causes forms/submissions to "disappear" in the CP / front end

### ISSUE THREAD

**Issue by tomdavies** [barrelstrength/craft-sprout-forms#551]
### Description

1. When using Craft 3.4.30 and Sprout Forms 3.12.2 on a Craft multi-site install, 
2. And where forms have been created with one default site set
3. Then the default site is changed
4. All the forms and submissions previously submitted are still present in the DB, but are no longer visible in the CP and no longer render on the front end
5. Changing the default site back to the original value restores the forms/submissions to functioning

I appreciate this bug report is for a (slightly) older version of Sprout Forms (v3.12.2), but it's a really unpleasant bug as it causes all of the forms on a site to stop working, so it's probably a good idea to check if it still exists in 3.13.x 

Unfortunately I don't have a 3.13.1 install running currently, and [I can't work out if it does from the diff](https://github.com/barrelstrength/craft-sprout-forms/compare/v3.12.2...v3.13.1). Until recently we've been prevented from updating Craft / Sprout forms by other issues around updating to 3.5 while using Sprout Forms

### Additional info

- Craft version: 3.4.30
- PHP version: 7.4.4
- Database driver & version:  MySQL 5.5.5
- Plugins & versions: Sprout Forms 3.12.2

**Comment by BenParizek** [comment]
@tomdavies I'm closing this out and will post updates on this in this other ticket here:
https://github.com/barrelstrength/craft-sprout-forms/issues/524

I'm currently working through all the Sprout Forms migration bugs and hope to have a release out that resolves all of these items as well as the underlying architectural decisions that are causing them around the release of Craft 3.6.

**Comment by tomdavies** [comment]
understood. Sorry I missed the existing issue!
