### ISSUE TITLE
Craft 3.6.3 Upgrade Issue

### ISSUE THREAD

**Issue by wes-lawson** [barrelstrength/craft-sprout-forms#558]
Issue after upgrading to Craft version 3.6.3.

When navigating to Forms or Reports I am receiving an error stating "A server error occurred."

My forms and reports never load in the admin panel. The form is still visible and functions properly on the website.

In my craft logs I am seeing this "Column 'name' in order clause is ambiguous". I recently implemented this fix for the reports https://github.com/barrelstrength/craft-sprout-forms/commit/2500a5d3c5649d51d166dec301adb8c11e258375.

Could they be related?

Thanks,
Wes

**Comment by engram-design** [comment]
@wes-lawson See my PR here https://github.com/barrelstrength/craft-sprout-forms/pull/559

**Comment by wes-lawson** [comment]
@engram-design thanks for this fix!

Looking at the reports issue, do you know what this line in "sprout-base-reports > source > elements > Report.php" needs to be updated to?

`'name' => Craft::t('sprout-base-reports', 'Name'),`

**Comment by BenParizek** [comment]
This has been fixed in the latest Sprout Forms and Sprout Reports.

https://github.com/barrelstrength/craft-sprout-reports/issues/106
