### ISSUE TITLE
Redirect page for multi-site

### ISSUE THREAD

**Issue by joelstrom** [barrelstrength/craft-sprout-forms#564]
### Description (screenshots, logs, ...)
I am having an issue getting the thank you page redirect to work when using one line Sprout Forms on a multi-sites Craft website.
The issue seems to be that the Redirect page field for each form is not translatable, which means that the url will be the same for all languages and domains. This is obviously an issue when working with multiple different languages as well as slightly differing url structures for different sites.

### Steps to reproduce

1. Add Redirect page value in the form's settings, eg. "/successful-form"
2. Submitting the form(s) on the primary domain and language work as expected, redirecting the user to domain.com/successful-form
3. Redirect does not work with other languages (domain.com/en, domain.com/ru etc.) as the redirect always goes to the primary language version of the website (instead of domain.com/en/successful-form).
4. Problem continues on the same installation when the domain structure is different for other sites (domain.com/en/domain-name)

I have not found a way to dynamically change the redirect page value when using one liner forms for a multi-site installation.
It would be great if one could send a redirect page value through the form options, but right now this does not seem to be possible? Tried looking through previous issues here but did not find anything about the subject, so I might be missing something as this feels like small yet important thing.

### Additional info

- Craft version: 3.5.18
- PHP version: 7.2
- Sprout Forms: 3.13.2.3

**Comment by BenParizek** [comment]
Hey @joelstrom 

A lot of folks using multi-site forms build a different form for each language, as that helps translate things and have different field or setting requirements. 

If you're able to use a single form for multiple sites and just need different redirects you can potentially override the default `form.twig` template and update the redirect logic in the template that gets output with the one-line `displayForm` tag.

To do this you can enable Custom Form Templates at the plugin level; set a custom folder for your custom form templates in the Form settings; and [copy the default form.twig file](https://github.com/barrelstrength/craft-sprout-forms/blob/v3.13.3/src/templates/_components/formtemplates/accessible/form.twig) into your custom folder so you can edit the default template. See a short description here:
https://sprout.barrelstrengthdesign.com/docs/forms/template-overrides.html

For example, you could replace the default redirect input with some of your own logic like the following:

```
{{ redirectInput(alias(currentSite.baseUrl) ~ '/thank-you') }}
```

That line assumes you are using aliases in your Site Base URL settings such as `@siteUrl`. If you have your Base URL settings hard coded in your Site settings, you can just reference them directly: `currentSite.baseUrl`

**Comment by joelstrom** [comment]
Thank you for your swift reply.

Creating separate forms for each language version just to change the redirect is too much work for sure, but your suggestion sounds like a good alternative. 
I do have experience from Custom Form Templates, so I am confident in getting it to work with your help without further hassles.
