### ISSUE TITLE
Entries Field not working when submitting value as hidden input

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-forms#566]
@espensgr reports: when i try to add this field as a hidden input in the form, as the user are not adding this themself, it is not added to the submission:

```
<input name="fields[prosjekt]" type="hidden" value="[{{ entryID }}]">
```

**Comment by espensgr** [comment]
Just going to add that the field in question is a Entries Relation field

**Comment by BenParizek** [comment]
@espensgr Thanks for saying that, I think I now understand what you are trying to do and this may relate to the other issue you had opened more than I realized initially.

While the data you are submitting for the Entries Relations field should be an array, the array will be defined by the input field `name` parameter, not in the `value` parameter as your example does above. If you ever needed to submit more than one Entries Relations value as a hidden input field you would do so using multiple input fields.

### Submit a single value to an Entries Relations field as a hidden input

```
<input type="hidden" name="fields[prosjekt][]" value="123">
```

### Submit multiple values to an Entries Relations field as hidden inputs

```
<input type="hidden" name="fields[prosjekt][]" value="123">
<input type="hidden" name="fields[prosjekt][]" value="456">
```

Let me know if that helps get things solved and even if that solves your initial ticket https://github.com/barrelstrength/craft-sprout-forms/issues/565

I expect I may have been misunderstanding where you were seeing the bug. I had thought it was when the page was loading where the error now makes sense if you were using the above `value` of `[{{ entryID }}]` and submitting the form.

**Comment by espensgr** [comment]
Well this don't relate to the other issue i think, but i do think this may fix this issue. Will give it a go and report back.
But this did work in Craft 2 though, so maybe this was the wrong way in Craft 2 too?

**Comment by BenParizek** [comment]
I'm assuming this was addressed where you said you got things working in this other thread (https://github.com/barrelstrength/craft-sprout-forms/issues/565#issuecomment-809417999)

Feel free to re-open if we need to follow up on anything else.
