### ISSUE TITLE
Form export - MS Excel does not understand it

### ISSUE THREAD

**Issue by mEsUsah** [barrelstrength/craft-sprout-forms#579]
### Description (screenshots, logs, ...)

Microsoft Excel does not open the CSV files that get exported by sprout forms. Does not automatically separate fields into table row cells. Have to use Yarn Reports to make it Excel-friendly.

### Steps to reproduce

1. Go to the CP page for sprout forms
2. Go to entries
2. Click on "Export" -> "No limit" -> "Export"
3. Open the csv file with MS Excel

### Additional info

- Craft version: 3.3.7
- PHP version: 7.1.26
- Database driver & version:  MySql
- Plugins & versions: Sprout Forms (Pro) 3.4.2

**Comment by BenParizek** [comment]
@mEsUsah This doesn't appear to be universal behavior, it might be a workflow issue. Can you take a look at the discussion here and see if anything mentioned about the workflow helps solve the issue you are seeing:
https://github.com/barrelstrength/craft-sprout-reports/issues/89#issuecomment-627827012

**Comment by BenParizek** [comment]
I just released v3.13.9 which adds unicode support for exported data which should play nicer with Excel. Let me know if that doesn't solve your issue.
