### ISSUE TITLE
Cannot create new form page after Craft 3.7 upgrade

### ISSUE THREAD

**Issue by JJefferyDev** [barrelstrength/craft-sprout-forms#582]
### Description (screenshots, logs, ...)
After upgrading to Craft 3.7.8 the pages on my sprout forms no longer display in tabs and I cannot create a new page in existing forms.  I can create a new form without issue.

Before Craft 3.7.8 upgrade:
![image](https://user-images.githubusercontent.com/3834326/129116479-3501bac9-c50c-4988-97d4-fdd003dc5185.png)

After Craft 3.7.8 upgrade:
![image](https://user-images.githubusercontent.com/3834326/129116406-0ae5c380-0ed4-4c05-8f21-3313b4d2a3b0.png)

### Steps to reproduce

1. Upgrade to Craft 3.7 from 3.6
2. Edit an existing sprout form
3. Try and add a page

### Additional info

PHP version: 7.3.15
OS: WINNT 10.0
Database: MySQL 8.0.16
Image Driver: GD 7.3.15
Craft: Craft Pro 3.7.8
Yii: 2.0.42.1
Twig: v2.14.6
Guzzle 7.3.0

**Comment by BenParizek** [comment]
@JJefferyDev I just released Sprout Forms v3.13.6 which addresses this issue.
