### ISSUE TITLE
CSS problem adding fields to forms in Sprout Forms 3.13.5

### ISSUE THREAD

**Issue by lancekuttner** [barrelstrength/craft-sprout-forms#584]
### Description (screenshots, logs, ...)
![Sprout CSS Issue](https://user-images.githubusercontent.com/11380153/129318289-c3651b81-8d12-487e-9d3f-7a5282f5ce89.png)

The above is what we are seeing when following the steps below.
Please refer to email support request "_Re: Sprout Forms CSS issues_" 03/08/2021 and subsequent response from Craft Support with temporary CSS fixes (which have been sufficient to enable us to continue, but not completely resolved addition of fields issues).

Note that this is probably a duplication of issue #582

### Steps to reproduce

1. Fresh build of Craft latest version and Sprout Forms latest version (as below) on AWS Linux and same on local Mac.
2. Sprout Forms > Forms > + New Form
3. Add fields to the form

### Additional info

- Craft version: 3.7.8
- PHP version: 7.4.21
- Database driver & version:  MySQL 5.5.0
- Plugins & versions: Sprout Forms 3.13.5

**Comment by BenParizek** [comment]
@lancekuttner I just released Sprout Forms v3.13.6 which I believe addresses these issues.
