### ISSUE TITLE
Craft 2 to 3 migration - Invalid datetime format

### ISSUE THREAD

**Issue by kevadamson** [barrelstrength/craft-sprout-forms#589]
Finally getting around to updating a website from Craft 2.9.2 to 3.7.13. I get this error installing the Sprout Forms plugin:

```
Database Exception: SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect DOUBLE value: 'barrelstrength\sproutreports\integrations\sproutreports\datasources\CustomQuery'
The SQL being executed was: UPDATE craft_sproutreports_reports SET dataSourceId=1 WHERE dataSourceId='barrelstrength\\sproutreports\\integrations\\sproutreports\\datasources\\CustomQuery'

Migration: barrelstrength\sproutforms\migrations\m180309_000000_update_data_sources

Output:

> update in {{%sproutreports_reports}} ...Exception: SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect DOUBLE value: 'barrelstrength\sproutreports\integrations\sproutreports\datasources\CustomQuery'
The SQL being executed was: UPDATE craft_sproutreports_reports SET dataSourceId=1 WHERE dataSourceId='barrelstrength\\sproutreports\\integrations\\sproutreports\\datasources\\CustomQuery' (/home/work/website/vendor/yiisoft/yii2/db/Schema.php:678)
#0 /home/work/website/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'UPDATE craft_s...')
#1 /home/work/website/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute('UPDATE craft_s...')
#2 /home/work/website/vendor/craftcms/cms/src/db/Migration.php(277): yii\db\Command->execute()
#3 /home/work/website/vendor/barrelstrength/sprout-base-reports/src/migrations/m180307_042132_craft3_schema_changes.php(203): craft\db\Migration->update('{{%sproutreport...', Array, Array, Array, false)
#4 /home/work/website/vendor/barrelstrength/sprout-base-reports/src/migrations/m180307_042132_craft3_schema_changes.php(56): barrelstrength\sproutbasereports\migrations\m180307_042132_craft3_schema_changes->prepExistingDataSourcesUsingOldDataSourceIdFormat()
#5 /home/work/website/vendor/barrelstrength/sprout-forms/src/migrations/m180309_000000_update_data_sources.php(34): barrelstrength\sproutbasereports\migrations\m180307_042132_craft3_schema_changes->safeUp()
#6 /home/work/website/vendor/craftcms/cms/src/db/Migration.php(52): barrelstrength\sproutforms\migrations\m180309_000000_update_data_sources->safeUp()
#7 /home/work/website/vendor/craftcms/cms/src/db/MigrationManager.php(232): craft\db\Migration->up(true)
#8 /home/work/website/vendor/craftcms/cms/src/db/MigrationManager.php(148): craft\db\MigrationManager->migrateUp(Object(barrelstrength\sproutforms\migrations\m180309_000000_update_data_sources))
#9 /home/work/website/vendor/craftcms/cms/src/services/Updates.php(251): craft\db\MigrationManager->up()
#10 /home/work/website/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(509): craft\services\Updates->runMigrations(Array)
#11 /home/work/website/vendor/craftcms/cms/src/controllers/pluginstore/InstallController.php(118): craft\controllers\BaseUpdaterController->runMigrations(Array)
#12 [internal function]: craft\controllers\pluginstore\InstallController->actionMigrate()
#13 /home/work/website/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#14 /home/work/website/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#15 /home/work/website/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('migrate', Array)
#16 /home/work/website/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('migrate', Array)
#17 /home/work/website/vendor/craftcms/cms/src/web/Application.php(277): yii\base\Module->runAction('pluginstore/ins...', Array)
#18 /home/work/website/vendor/craftcms/cms/src/web/Application.php(674): craft\web\Application->runAction('pluginstore/ins...')
#19 /home/work/website/vendor/craftcms/cms/src/web/Application.php(234): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#20 /home/work/website/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#21 /home/work/website/web/index.php(26): yii\base\Application->run()
#22 /home/.config/composer/vendor/cpriego/valet-linux/server.php(232): require('/home/work/...')
#23 {main}
```

### Additional info

- Craft version: 3.7.13
- PHP version: 7.2.34
- Database driver & version: MySQL 8.0.26

**Comment by BenParizek** [comment]
@kevadamson It seems like the CustomQuery data source is somehow getting migrated twice. I'm not sure why that would be. Perhaps there is a scenario where the two values existed before you started the migration.

If you'd like to try a workaround on your end, if you don't use the CustomQuery data source or if it's easy to migrate the reports you do use it for manually, you could try deleting it from your original DB before you upgrade and see if you get around the issue.

To help troubleshoot further, it might be best if you reach out to support@barrelstrengthdesign.com and either provide your db so I can take a closer look or propose a few times that we could connect on a short screen share to get it resolved.

**Comment by kevadamson** [comment]
Thanks @BenParizek 

Do I delete this:

![image](https://user-images.githubusercontent.com/1021744/134498165-9a68b4e4-4c7d-445d-b59d-68b354f51ffd.png)

from `craft_sproutreports_datasources`?

**Comment by BenParizek** [comment]
@kevadamson Yes, that's the one. 

I'm operating on limited context here, so be sure to back up your db first and you may not want to do that if you have any reports of that type as they'd be referring to that data source in the reports table via `craft_sproutreports_reports.dataSourceId` and that could cause new issues.

**Comment by kevadamson** [comment]
I "fixed" by one by deleting the migration files from the vendor folder that were erroring. Seems to have worked ...

**Comment by jamesmacwhite** [comment]
I'm still hitting this on MySQL 8 for a Craft 2 to 3 migration.

I've tried starting with completely blank sprout reports tables but the issue is migrations being called from different Sprout modules/plugins make it hard to try and patch around it. Deleting the migrations from vendor isn't ideal when you want to have a fully automated migration track.

The one fix that seems to work is making the dataSourceId column in Sprout Reports VARCHAR, but this gets changed back to int during the migrations and needs to be done multiple times. I read that this was apparently done, but I'm not sure due to MySQL still throwing the error.

I'm not sure what else to try. At this point I'd happily just start fresh with Sprout Reports and just manually re-create the correct reports in Craft 3 and import the DB data after migration, but I can't even get past the plugin migration path because of the invalid datetime error and because it's from the plugin migration track, mitigation in another track is tricky.

**Comment by jamesmacwhite** [comment]
Actually, temporarily disabling strict mode seems to allow the migrations to complete. Hooking a custom migration track before the plugins migration track can allow you to run a dbCommand to execute a SET SESSION sql_mode query to drop strict mode temporarily. It's not ideal, but it works and temporary.
