### ISSUE TITLE
Checkbox / Radio Buttons not translating using static file

### ISSUE THREAD

**Issue by DrewBold** [barrelstrength/craft-sprout-forms#592]
Hello,

Checkboxes and Radio Button labels are not translating using the static site.php file. I have also included and modified the sprout-forms.php file in the appropriate folder for craft site translations. 

/translations/fr/site.php
/traslations/fr/sprout-forms.php

EG: "Yes" => "Oui" 

### Additional info

- Craft version: 3.5.17.1
- PHP version: 7.3.16
- Database driver & version:  MySQL 5.6.22
- Plugins & versions: Sprout Forms Pro 3.13.6

**Comment by BenParizek** [comment]
Thanks for reporting @DrewBold. I've pushed a fix in Sprout Forms v3.13.8. You should be able to use the 'site' translation category for those labels now.

**Comment by DrewBold** [comment]
@BenParizek  Thank you!
