### ISSUE TITLE
Markup in Opt-in message field generates escaped HTML

### ISSUE THREAD

**Issue by wallacio** [barrelstrength/craft-sprout-forms#608]
### Description (screenshots, logs, ...)
Ussing Markup in an 'opt-in' message field causes HTML characters to be rendered in default Accessible Template

**Markup in field**
![image](https://user-images.githubusercontent.com/104447069/172001084-875de961-a59c-4ff1-8b3b-1433bd9c36c6.png)

**Output HTML**
![image](https://user-images.githubusercontent.com/104447069/172001038-682cd01f-5f21-430c-8c2e-528bbbe976a3.png)

**Source HTML**
![image](https://user-images.githubusercontent.com/104447069/172000998-80fd7893-195b-47da-947e-47467289a989.png)

### Steps to reproduce

1. Create a form which uses the default, accessible templates
2. Add Markup to "Opt-in message" field, e.g. `[Terms of Use](/terms-of-use)`

### Additional info

- Craft version: 3.7.43
- PHP version: 7.4.28
- Database driver & version:  MariaDB 10.6
- Plugins & versions: Sprout Forms 3.13.8

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_4pd3h)

**Comment by BenParizek** [comment]
Just released Sprout Forms v3.13.10 which fixes this.
