### ISSUE TITLE
Sprout Forms user permissions are invalid on Craft 2 to Craft 3 migration

### ISSUE THREAD

**Issue by jamesmacwhite** [barrelstrength/craft-sprout-forms#611]
### Description (screenshots, logs, ...)

I recently migrated a large Craft 2 site and some of the new type values set in the user permissions migration are not the correct values: 

https://github.com/barrelstrength/craft-sprout-forms/blob/v3/src/migrations/m190318_000000_updates_user_permissions_groups.php.

* View entries should be: `sproutForms-viewEntries`.
* The edit form permissions should be `sproutForms-editEntries`.

From a Craft 2 migration the previous view/edit permissions on a user or group set are lost entirely, because of the invalid type name.

**Comment by BenParizek** [comment]
This is fixed in Sprout Forms v3.13.10.
