### ISSUE TITLE
Google ReCaptcha Error - Forms Treated as SPAM

### ISSUE THREAD

**Issue by gdelorey** [barrelstrength/craft-sprout-forms#613]
We are using Sprout Forms with Google ReCaptcha enabled, and recently found out that form submissions from the Safari browser on Mac do not get recorded in Sprout. In doing some troubleshooting, the following is true:

1. This happens across all forms (existing and new for testing)
2. If I enable storage of spam submissions, we do see the entry arrive but marked as spam. The reason given by Sprout is: ["Google reCAPTCHA can't be blank."] This is after authenticating with ReCaptcha and receiving a green checkmark.
3. If I disable ReCaptcha, the forms arrive as expected.
4. This issue is not present in any other browser (Chrome, Edge, Firefox)

### Steps to reproduce

1. Create new form
2. Enable Google ReCaptcha
3. Submit form on Mac using Safari browser

### Additional info

- Craft version: Craft CMS 3.7.48
- Plugins & versions: Sprout Forms 3.13.8

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_4pczx)

**Comment by BenParizek** [comment]
Sprout Forms v3.13.12 fixes a bug where async form submissions were not properly wrapped in the promise chain which could have caused issues like this while processing Google ReCaptcha.

While I haven't been able to reproduce to confirm this is the same issue, as this is an older bug, I'm closing it out. If you runs into this again, please re-open with new comments.
