### ISSUE TITLE
Google ReCaptcha  - messages sent using Safari browser marked as SPAM

### ISSUE THREAD

**Issue by make-digital** [barrelstrength/craft-sprout-forms#623]
We are experiencing an issue using Sprout Forms with Google ReCaptcha enabled.

All form submissions from Mac Safari (desktop and mobile) are marked as spam.

We have set Sprout Forms to store spam messages to help debug this. The reason given by Sprout is: ["Google reCAPTCHA can't be blank."] This is after authenticating with ReCaptcha and receiving a green checkmark.

This seems to be an exact match for this closed bug report:
https://github.com/barrelstrength/craft-sprout-forms/issues/613#issue-1324701006

### Steps to reproduce
1. Create new form
2. Enable Google ReCaptcha
3. Submit form on Mac (desktop or mobile) using Safari browser

### Additional info

- Craft version: 3.8.1
- PHP version: 7.3.33
- Plugins & versions: 
Sprout Forms 3.13.18
Google reCAPTCHA for Sprout Forms 1.4.1

**Comment by BenParizek** [comment]
I just pushed another small change in Sprout Forms v3.13.19 which address a bug where synchronous submissions could be treated asyncronously - potentially leading to a scenario where the form submit complete more quickly than the recaptcha validation. Please update to the latest and let me know if that solves your issue.

As a side note, Sprout Forms for Craft 4 will integrate the ReCaptcha plugin and simplify some things about the current implementation that can get tricky in scenarios with custom javascript or caching. If the issue above persists after the update, I'll need more info about how you have your forms setup and anything custom about them or how they're implemented that you can share.

**Comment by make-digital** [comment]
Thanks @BenParizek 

I've updated to 3.13.20 and retested it. That seems to have resolved the issue.

Thanks for your help with the issue.
