### ISSUE TITLE
Saving Form Throws Error

### ISSUE THREAD

**Issue by mikestecker** [barrelstrength/craft-sprout-forms#72]
Each time I try and save a new form, I get the following error:

`count(): Parameter must be an array or an object that implements Countable`

The error is flagging line 89 of `vendor/barrelstrength/sprout-forms/src/controllers/FormsController.php`: `if (count($deletedFields) > 0) {`

It actually does save the form changes though each time. I'm able to click to another part of the admin, and go back to edit the same form and I see the changes.

I'm on Craft 3.0.0.2 and tried this on a fresh install of Sprout Forms 3.0.0-beta.3.

**Comment by BenParizek** [comment]
Thanks @mikestecker 

This is fixed in the latest release Sprout Forms v3.0.0-beta.4
