### ISSUE TITLE
Error when installing Sprout Forms

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-forms#82]
```Sprout Forms has been added, but an error occurred when installing it.

Unknown Property: Setting unknown property: barrelstrength\sproutbase\records\sproutreports\DataSource::pluginId```

**Comment by damonjentree** [comment]
Previously had beta5 installed then un-installed & removed via the CP. I then searched the plugin store for sprout forms to install the latest version. 

Was getting a Craft error (above) with an option to "remove", or "send for help". I have removed the entry from my `package.json` file, and did `composer update` to remove the package. 

After trying to install again, I am able to successfully install the plugin, but now get the above error as a twig-ish type error (vs craft system error)

**Comment by damonjentree** [comment]
When updating the _correct_ way via updates panel, everything works properly. I do not get any errors.
