### ISSUE TITLE
Not all comma-delimited recipients receive notification email when S3 file attachment is added

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-forms#83]
Craft CMS 2.6.3012
Sprout Forms 2.5.1
Sprout Invisible Captcha 0.8.3

Under Forms > Notifications > Email Recipients
We have approximately 7 recipients who receive an email, comma delimited.

Only the first recipient of the comma delimited list receives an email notification when an Amazon S3 attachment is included with the form submission. Confirmed this by changing the order of the comma delimited list, and confirmed that only the first person in the comma delimited list receives the notification when attachments are included.

When there is no Amazon S3 attachment, all recipients receive an email.

### Notify

- [x] [11812229347](https://app.intercom.io/a/apps/dfa024eb83c11784227312bba407fb3d35e00fa7/inbox/inbox/714050/conversations/11812229347)

**Comment by jerome2710** [comment]
I believe the fix of this bug causes another bug. When resetting the attachments-array on line 179 of the SproutFormsService (`$email->attachments = [];`), the attachments-array gets cleared every time an AssetsFieldType calls the function attachAssetFilesToEmailModel on line 119. This occurs when a form has multiple AssetsFieldTypes. Could you please verify & fix this? Thank you!

**Comment by BenParizek** [comment]
Thanks for reporting @jerome2710. We'll look into this.

**Comment by jerome2710** [comment]
Hi @BenParizek, could I get an update regarding this issue?

**Comment by BenParizek** [comment]
@jerome2710 This has been fixed in Sprout Forms v2.5.3: 
https://github.com/barrelstrength/craft-sprout-forms/releases/tag/v2.5.3

**Comment by jerome2710** [comment]
Can the [release feed](https://sprout.barrelstrengthdesign.com/craft-plugins/forms/releases.json) be update as well please, thank you.

**Comment by BenParizek** [comment]
Hi Jerome,

The latest version of Sprout Forms for Craft 2 updates the release feed, but you'll need to update it for it to work again (as we migrated the releases.json file to Github)

Ben

--
https://calendly.com/benparizek
707.653.5683


--- original message ---
On Fri, Jul 13, 2018 at 03:20 am, <notifications@github.com> Jerome Anker wrote:


Can the release feed be update as well please, thank you.

—

You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---
