### ISSUE TITLE
Email attachments not showing in email notification

### ISSUE THREAD

**Issue by ryangittings** [barrelstrength/craft-sprout-forms#85]
When using Craft 3 sprout forms, files uploaded via the form aren't attached to the notification email, however, the filename does show under the field name though.

Many thanks!

**Comment by BenParizek** [comment]
@andrelopez 

The form that was tested with is using Custom HTML. I've confirmed that the form is using `enctype="multipart/form-data"` and that the `Attach Files` setting was enabled in the Notification Email settings.

**Comment by ryangittings** [comment]
Just an update on this:

I seem to get intermittent issues with file uploads. I seem to be able to recreate it when posting a submission locally, then on the production version. If I then clear caches and try again it then works.

Not sure if that helps at all, or even if it's related.

**Comment by BenParizek** [comment]
@ryangittings We've just added support for email attachments in v3.0.0-beta.15.
