### ISSUE TITLE
Improve error if Title Format setting includes an incorrect handle

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-forms#96]
If the Title Format value is using a wrong handle, the form just fails and reloads blank. Can we display a more useful error to the user or in the log?

The situation where this can occur is if someone renames a field and forgets to update the Title Format handle. Perhaps we can try to update that form them whenever a field is renamed.

**Comment by andrelopez** [comment]
We added the error to the logs.
