### ISSUE TITLE
sprout-base ^2.0.3 -> no matching package found.

### ISSUE THREAD

**Issue by ryansnowden** [barrelstrength/craft-sprout-forms#99]
### Description
Updating from 3.0.0-beta.10 via craft3 updates and updating via single update button (not update all)

--
Composer was unable to install the updates.

Error: An error occurred

Output: Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

Problem 1
- Installation request for barrelstrength/sprout-forms 3.0.0-beta.14 -> satisfiable by barrelstrength/sprout-forms[3.0.0-beta.14].
- barrelstrength/sprout-forms 3.0.0-beta.14 requires barrelstrength/sprout-base ^2.0.3 -> no matching package found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
see for more details.
- It's a private package and you forgot to add a custom repository to find it

Read for further common problems.
Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.

### Steps to reproduce

Can also reproduce by doing a fresh install of the plugin.

### Additional info

- Craft version: 3
- PHP version: 7.2.1
- Database driver & version:
- Plugins & versions: 3.0.0-beta.10

**Comment by BenParizek** [comment]
Hi @ryansnowden 

I'm wondering if this could have been an issue with the timing of your update on Friday around when we were pushing several updates live. Sprout Base v2.0.3 is published and available: https://packagist.org/packages/barrelstrength/sprout-base

I've tested both installing fresh and updating and I'm not seeing any issues. Could you give it another test this week and let me know if you continue to run into the same issue?

**Comment by BenParizek** [comment]
Haven't heard from anybody else on this one so closing this out for now. Please re-open if the issue continues.
